### ISSUE TITLE
Is it abandoned?

### ISSUE THREAD

**Issue by sidferreira** [DylanVann/react-native-fast-image#1009]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior if possible, or a link to a reproduction repo:

**Expected behavior**

**Screenshots**

**Dependency versions**

- React Native version:
- React version:
- React Native Fast Image version:

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by mskarimi** [comment]
@DylanVann

**Comment by knro** [comment]
This project is abandoned. Any possible maintainers?

**Comment by pduggi-cf** [comment]
This project absolutely needs a maintainer, I see there are a lot of pull request. Please let me know if I can help in some way. I do not mind putting in 5 hours a week (Me or someone from my team).

**Comment by fleuverouge** [comment]
Hi @pduggi-cf  Looks like the creator has completely abandoned this repo. Do you mind forking into a new repo and continuing the maintenance?

**Comment by noumantahir** [comment]
any available alternative?.... facing image caching issues on iOS causing app to go out of memory even though we have fail sails in place...

**Comment by kunalchavhan** [comment]
I am interested in maintaining this repository.

**Comment by kunalchavhan** [comment]
[expo-image](https://www.npmjs.com/package/expo-image) is alternative library available. Has anyone used it?

**Comment by Harshizonnet** [comment]
> any available alternative?.... facing image caching issues on iOS causing app to go out of memory even though we have fail sails in place... 

Try this one works on both platforms.

import BlastedImage from 'react-native-blasted-image';

<BlastedImage 
  source={{ uri: 'https://example.com/image.png' }} 
  resizeMode="cover"
  width={200}
  height={200}
  style={{ borderRadius: 10 }}
/>

**Comment by Harshizonnet** [comment]
> [expo-image](https://www.npmjs.com/package/expo-image) is alternative library available. Has anyone used it?

Try this one bro. it works fine on both.

import BlastedImage from 'react-native-blasted-image';

<BlastedImage 
  source={{ uri: 'https://example.com/image.png' }} 
  resizeMode="cover"
  width={200}
  height={200}
  style={{ borderRadius: 10 }}
/>

**Comment by CavalcanteLeo** [comment]
> [expo-image](https://www.npmjs.com/package/expo-image) is alternative library available. Has anyone used it?

problem is that it does not cache the image

**Comment by yhl127** [comment]
> > [expo-image](https://www.npmjs.com/package/expo-image) is alternative library available. Has anyone used it?
> 
> problem is that it does not cache the image

I think there is a cachePolicy you can use https://docs.expo.dev/versions/latest/sdk/image/#cachepolicy

**Comment by deepanshushuklad11** [comment]
Dream11 has forked this repo and created new package .
 [@d11/react-native-fast-image](https://www.npmjs.com/package/@d11/react-native-fast-image)
Dream11 is actively maintaining this new package and will be fixing relevant and reproducible issues of this repository.

**Comment by duguyihou** [comment]
I created a new package. [react-native-turbo-image](https://github.com/duguyihou/react-native-turbo-image). It also works with new architecture.

**Comment by xerdnu** [comment]
Check out [react-native-blasted-image](https://github.com/xerdnu/react-native-blasted-image) if that maybe can be of interest 😃

Best regards! 🚀

**Comment by hotaryuzaki** [comment]
> I created a new package. [react-native-turbo-image](https://github.com/duguyihou/react-native-turbo-image). It also works with new architecture.

is there any specific reason why do you use Nuke and Coil??

**Comment by duguyihou** [comment]
> > I created a new package. [react-native-turbo-image](https://github.com/duguyihou/react-native-turbo-image). It also works with new architecture.
> 
> is there any specific reason why do you use Nuke and Coil??

The reason is simple. [Nuke](https://kean.blog/nuke/home) has good performance. I don't like writing Java and the performance of [Coil](https://medium.com/swlh/benchmarking-image-loading-libraries-on-android-3ddf365a1927) is not bad.
