### ISSUE TITLE
Gifs only play once

### ISSUE THREAD

**Issue by vuongmt2000** [DylanVann/react-native-fast-image#1016]
I use 
  "react-native": "0.68.2",
 "react-native-fast-image": "8.6.3",

**Comment by vuongmt2000** [comment]
error gifs

**Comment by iusama46** [comment]
Edit your gif and set it's loop count to 1

<img width="819" alt="image" src="https://github.com/user-attachments/assets/84ff15e8-57a9-4986-87eb-4339dbafc9b8">
