### ISSUE TITLE
Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

### ISSUE THREAD

**Issue by mlcpro** [DylanVann/react-native-fast-image#1054]
**Describe the bug**
Warning: TypeError: Cannot read property 'bubblingEventTypes' of null

**Dependency versions**

- React Native version: 0.75.4
- React version: 18.3.1
- React Native Fast Image version: ^8.6.3

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by jedaydiya** [comment]
I also encountered this issue, but reopening my emulators fixed it.Try closing and opening your simulator and android emulator.

**Comment by satyajitX001** [comment]
I encountered same issue with same version,
Solution - 
1. delete node module and reinstall it
2. cd android && ./gradlew clean
3. npm run android  <-- this is the main step

**Comment by FelipeRaulino** [comment]
@mlcpro You've closed the issue. How have you solved the problem ?

**Comment by mlcpro** [comment]
@FelipeRaulino yes, i closed the emulators and reopened

**Comment by eramudeep** [comment]
> I encountered same issue with same version, Solution -
> 
> 1. delete node module and reinstall it
> 2. cd android && ./gradlew clean
> 3. npm run android  <-- this is the main step

This fixed the issue. 
But what could be the RCA ?

**Comment by IonutDaniel99** [comment]
Rollback to old React-Native (under 0.75.4) as the new 0.76 use a new architecture which most of libraries are not yet updated and it throws this problem.

**Comment by 1mehdifaraji** [comment]
I had the same issue with the iOS simulator and `pod install` fixed it for me.

**Comment by hayata-0** [comment]
@1mehdifaraji 
Thank you for providing a solution.
I have one question.
When building for iOS using Expo, I get the same error:
Warning: TypeError: Cannot read property 'bubblingEventTypes' of null.
You mentioned that it was resolved with pod install, but did you do anything else besides that?

**Comment by 1mehdifaraji** [comment]
@hayata-0 You're welcome, no I only did `pod install` but I'm not using `expo` so you may need to rollback `react-native` or `expo` or try installing and using an earlier version of the library and try clearing cache and rebuild.

**Comment by IonutDaniel99** [comment]
I figured out after several trial and error that this was also a problem from patches of different libraries.
In my case i had an error on React-Charts so i did a patch. That patch created the bubblingEventTypes because the return type was incorrect .

Might be worth looking if you have applied patches over node_modules libraries.

**Comment by Hiba-Bazerbashi** [comment]
I'm receiving the same error with Flashlist in expo 52   ,is there any fix ?

**Comment by ArjunK01** [comment]
doing a whole eas rebuild fixed this for me

**Comment by iamabdulhaseeb** [comment]
I faced this same issue with react-native-blasted-image, I deleted app from my emulator and re-build the project, its working now

**Comment by timohuennebeck** [comment]
I also encounter this issue using Expo 52. Doing the following steps did not work for me 🙃
- Delete node_modules and ios folders
- npx expo prebuild --platform ios
- Build project in XCode
- npm run dev

**Comment by luigi-dv** [comment]
If you using Expo `npx expo install expo-linear-gradient` then `import { LinearGradient } from 'expo-linear-gradient';`

- Future reference for people that experience this error when directly using react-native-linear-gradient on expo.

**Comment by diponkorcs** [comment]
I am facing the same issue while trying to use "LinearGradient" from react-native-linear-gradient and also I have tried using "expo-linear-gradient". Both are throwing the same issues. Any solve for that?

**Comment by diponkorcs** [comment]
> If you using Expo `npx expo install expo-linear-gradient` then `import { LinearGradient } from 'expo-linear-gradient';`
> 
> * Future reference for people that experience this error when directly using react-native-linear-gradient on expo.

Thanks. Works for me.

**Comment by moonmirXD** [comment]
If you are using LinearGradient

Make sure you are importing LinearGradient from the correct package:
import LinearGradient from 'react-native-linear-gradient';

If you’re using Expo, make sure you're importing it from the correct Expo wrapper:
import { LinearGradient } from 'expo-linear-gradient';
