### ISSUE TITLE
how to set placeholder when image isnot downloaded complete

### ISSUE THREAD

**Issue by Alvin365** [DylanVann/react-native-fast-image#109]

**Comment by Alvin365** [comment]
I add a placeholder using following

import React from 'react';
import { View, Image, StyleSheet } from 'react-native'
import FastImage from 'react-native-fast-image';

const LDImage = ({ style, url, placeholder, priority }) => (
  <View key={i} style={style}>
    <Image style={StyleSheet.absoluteFill} resizeMode={'cover'} source={placeholder}/>
    <FastImage
          style={{flex:1}}
          source={{
            uri: value,
            priority: priority || FastImage.priority.normal,
          }}
          resizeMode={FastImage.resizeMode.cover}/>      
  </View>
)

export default LDImage;

**Comment by DylanVann** [comment]
Duplicate: https://github.com/DylanVann/react-native-fast-image/issues/5

It's super easy to implement this currently using a local `Image` behind `FastImage`. This will probably be added eventually though.

**Comment by AlirezaAkbarix** [comment]
Please consider it doesn't work with `png` files! (Imagine that forward image that is loading from web, is a png file, so after finishing loading you'll see it's covering placeholder image and in fact you have 2 visible images!)

**Comment by supertiger1234** [comment]
wow, its been years and still not added clap clap.

**Comment by naheed-shamim** [comment]
Put the correct FastImage inside the placeholder dummy image, it will work.

like this

`<FastImage
          source={images.placeholderProfile}
          style={styles.profileImg}
          resizeMode={FastImage.resizeMode.contain}
        >
          <FastImage
            fallback
            defaultSource={images.profile}
            source={{ uri: BASE_URL + profileImage }}
            style={styles.profileImg}
            resizeMode={FastImage.resizeMode.cover}
          />
        </FastImage>
      </>`

**Comment by 0xVikasRushi** [comment]
wow! it worked
