### ISSUE TITLE
FastImage with Blob

### ISSUE THREAD

**Issue by tiaaaa123** [DylanVann/react-native-fast-image#11]
Hi! 
I'm trying to use `react-native-fast-image` but it doesn't seems to work with Blob. I give it a blob URL as the uri and all i get is a white rectangle with red border. the onError isn't fired.
Could it be because a blob url is made to download the image and your module is ti load online image?

**Comment by DylanVann** [comment]
This module is intended to work with images on the internet, not local
images.

**Comment by DylanVann** [comment]
Also showing a white rectangle with red border might indicate it isn't
linked properly.
