### ISSUE TITLE
Application Force Close after convert to APK

### ISSUE THREAD

**Issue by syarofanz** [DylanVann/react-native-fast-image#110]
I using this library, in debug mode it's normal. But after build to apk and install in android device, force close. Why is that ? Bug or why ?

**Comment by quy1403** [comment]
+1

**Comment by quy1403** [comment]
@DylanVann please help

**Comment by k30r88** [comment]
Me too, I experienced same issue here

**Comment by Ethan-Vann** [comment]
@DylanVan also experiencing this

**Comment by barghi** [comment]
same issue here

**Comment by barghi** [comment]
change enableProguardInReleaseBuilds to false in android/app/build.gradle works for me

**Comment by barghi** [comment]
trying to add these 2 lines to android/app/proguard-rules.pro
```
-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}
```

**Comment by DylanVann** [comment]
@barghi Thanks for figuring this out, a note has been added to the README.

I don't use Proguard so I don't think I ever would have thought of this.

https://github.com/DylanVann/react-native-fast-image/blob/master/README.md#proguard

**Comment by barghi** [comment]
@DylanVann thanks for your great component 👍🏻👍🏻
