### ISSUE TITLE
Is there a way to programatically bust the cache on receiving low memory warning from the phone OS?

### ISSUE THREAD

**Issue by varungupta85** [DylanVann/react-native-fast-image#114]
More of a question than an issue. I didn't see any way to programatically bust the cache on receiving low memory warnings from the OS and wanted to check if there is such a way. Thanks!

**Comment by bighitbiker3** [comment]
I'd like this as well....might take a look this week or next if I have time

**Comment by DylanVann** [comment]
There is no way currently. Closing this in favour of this issue: https://github.com/DylanVann/react-native-fast-image/issues/195
