### ISSUE TITLE
Different default value for `resizeMode`

### ISSUE THREAD

**Issue by ilonashub** [DylanVann/react-native-fast-image#119]
There is a bit incompatibility in `resizeMode` default values when not sending any value to the prop, and then passing a `null` to the prop (as far as I understand, and tried to do in my app).

According to the documentation `FastImage.resizeMode.contain` is the default value, but in the code, I see that if I don't pass any value to `resizeMode`, then:
```
FastImage.defaultProps = {
  resizeMode: FastImage.resizeMode.cover,
}
```
but if I do pass this prop, with `null` value then I actually get `FastImage.resizeMode.contain` as the default value.

**Comment by DylanVann** [comment]
Interesting, I guess that code path on Android just isn't taken unless null is explicitly passed.

Should be fixed in the latest version.

**Comment by ilonashub** [comment]
@DylanVann thanks!
