### ISSUE TITLE
PR to react-native core?

### ISSUE THREAD

**Issue by JulianKingman** [DylanVann/react-native-fast-image#120]
Hey, this library is pretty spiffy, have you considered merging it to the react native core? I've been running into caching issues (https://github.com/facebook/react-native/issues/1397), and it's become clear that facebook is not that invested in the RN Image component, since they have their own internal one that they maintain. It would be awesome to see this take its place.
Possible?

**Comment by DylanVann** [comment]
I'm doubtful. There would be a number of things that would have to be added and fixed before I think they'd consider it. `Image` definitely does have issues, but this doesn't have feature parity with it yet.

In regards to the issue you linked to: That issue will be even worse using this component (see: https://github.com/DylanVann/react-native-fast-image/blob/master/docs/how-is-caching-handled.md). I really think it's a problem of having a poorly designed API for images. I also don't understand why you can't use a query parameter to bust the cache.

There actually is an issue open for this, although I don't blame you for not finding it, it's pretty old. I'll close this so we can't keep discussion in one place.

https://github.com/DylanVann/react-native-fast-image/issues/12
