### ISSUE TITLE
Preload seem to not do anything?

### ISSUE THREAD

**Issue by joecaraccio** [DylanVann/react-native-fast-image#121]
It could be just me, or does the Preload function not seem to really assist? Its hard to tell but it feels like you still have to see the load times regardless, wether you ran a preload or not!

anyone else feel this way?

**Comment by n1ru4l** [comment]
You talking about ios or android or both?

Also I would like to have `FastImage.preload` return a `Promise` that resolves once the image is loaded. This would make it easier to implement something like progressive image loading.

**Comment by joecaraccio** [comment]
@n1ru4l 
Talking about Android. I changed FastImage.preload to return a promise when all the images are preloaded, but even when doing that the preload dosen't seem to do much

I preloaded on 1 view, and then opened that same uri on a different view, and there was still some load time that seemed like it was just pulling down from the web

**Comment by wkoutre** [comment]
+1 for this @joecaraccio . Doesn't work on my end on iOS or Android.

RN@0.50.4
RNFI@1.0.5

**Comment by ewalti** [comment]
Thanks for the comment @joecaraccio I was hoping to use this to preload images in one view and have them instantly render in a different view. Have you had any luck with that?

**Comment by joecaraccio** [comment]
my solution was kinda specific to my use case where i just used absolute position off to the side, and rendered the image using FastImage, and then brough it back onto screen when done.. that probably dosen't work for a lot of people unfortunatly

**Comment by Kouznetsov** [comment]
The issue was the same for me, at least on Android. I recall that it did the job on iOS.

**Comment by DylanVann** [comment]
You're right, it definitely was not working on Android. I setup a server for testing and an example and could see it was making a new request when showing a preloaded image.

It did work on iOS.

This fixes it: https://github.com/DylanVann/react-native-fast-image/commit/de4f40a3a30a95fb8cdab714735501650e335dd9

A new version is published now. Let me know if you have any issues with it.

**Comment by togusa2017** [comment]
i preload images but i still see a lag when they are rendered on the next view for the first time. Am i missing anything ?

**Comment by mnlbox** [comment]
It's still not working on Android :disappointed: 
Please reopen issue until complete fix.

**Comment by DylanVann** [comment]
@togusa2017 @mnlbox Can the preloading issue on android be reproduced in a minimal example?

The preloading seems to be working in the example application in this repo:

![preload_02](https://user-images.githubusercontent.com/1537615/37140261-225747ae-227f-11e8-9da6-96cbd488f96c.gif)

**Comment by tomerono** [comment]
@joecaraccio Hey, can you share how you'v managed to make FastImage.preload to return a promise? 
preload to return a promise would completely solve my issue.

**Comment by isaachinman** [comment]
@ewalti (or anyone else in this thread) did you end up finding a way to do this?

Using preload in an iOS simulator seems to have no effect. When navigating to a screen that contains the actual `<FastImage>` with the uri, it just pulls down the image at that point in time.

**Comment by roycclu** [comment]
@DylanVann Why is this closed? Been testing it on iOS, the preload doesn't work. 
Preload on one screen, on a later screen the images still are loading. 

RN: 0.54.0-rc3
RNFastImage: 4.0.4
React: 16.3.1

Any idea how to fix/what's wrong?

**Comment by twillstudio** [comment]
Hi everyone, I am using the following code in the componentDidMount method of my App.js:

await FastImage.preload([{ uri: 'https://app.box.com/shared/static/dz6tvgka56ub8xfii6v4516zco0bmvwq.jpg' }])
      await FastImage.preload([{ uri: 'https://app.box.com/shared/static/8e43tmaproz9psvch4s7de5tyff9i71k.jpg' }])
      await FastImage.preload([{ uri: 'https://app.box.com/shared/static/udiaehxve4tjunnhe40wtvddvp8h3hdo.jpg' }])

      await FastImage.preload([{ uri: 'https://app.box.com/shared/static/6rbqggrctvsjgebxmr2u630u081w3rrz.jpg' }])
      await FastImage.preload([{ uri: 'https://app.box.com/shared/static/n4fym1ck83nmlo0uo20clpwidipr3e56.jpg' }])
      await FastImage.preload([{ uri: 'https://app.box.com/shared/static/e1fiqrjwqhm5vh77znjr1gfiy5kclw94.jpg' }])

It does not seems to do anything because i can see blank space while the image are being loaded after my app launched. 
I am using react native on my ios simulator.

Thanks very much in advance.

**Comment by FrankGoortani** [comment]
This is still not working for me on android:
RNFastImage: 6.0.3
React-Native: 0.59

Please fix this!

**Comment by twhoff** [comment]
@twillstudio that's not going to work because the preload function returns void - therefore, in the sense of a promise, it will resolve immediately.

**Comment by avet-m** [comment]
This is still not working on android:
RNFastImage: 8.1.5
React-Native: 0.61.2

**Comment by skizzo** [comment]
Why was this issue closed? It‘s still not working for me on RN0.61.5 using the latest version of reach-native-fast-image. Thanks for some insights

**Comment by punjasin** [comment]
can you updatei to to return promise so I can't disable loading spinner when it done

**Comment by mohity777** [comment]
> Why was this issue closed? It‘s still not working for me on RN0.61.5 using the latest version of reach-native-fast-image. Thanks for some insights

did u find any solution?

**Comment by vasylnahuliak** [comment]
Any news on android?

**Comment by giantslogik** [comment]
I patched android preloading here https://github.com/DylanVann/react-native-fast-image/issues/657#issuecomment-2312378889
