### ISSUE TITLE
Add support for tintColor.

### ISSUE THREAD

**Issue by KalebPortillo** [DylanVann/react-native-fast-image#124]
I tried to apply the the style tintColor on the FastImage, but it seems that this style is not supported, I need to change a PNG color dynamic in code, but I also want to use this wonderful library instead the native Image component.

**Comment by drpiou** [comment]
Hi! Same here :)

**Comment by DylanVann** [comment]
It's not currently supported. You could add a semitransparent view over the image.

It may eventually be supported but it's not a high priority at the moment.

**Comment by GuillaumeMunsch** [comment]
Add this somewhere in one of the root files to ignore the warning:

```
YellowBox.ignoreWarnings([
  'Warning: Failed prop type: Invalid props.style key `tintColor` supplied to `FastImage`',
]);
```

**Comment by GuillaumeMunsch** [comment]
In the new 5.x.x version `tintColor` doesn't work anymore

**Comment by KalebPortillo** [comment]
Hey @GuillaumeMunsch, I think it is not yet supported

Someone implement it and made a PR #226, but still waiting for the merge.
