### ISSUE TITLE
How to use FastImage in RN 0.43.4?

### ISSUE THREAD

**Issue by SunSet1219** [DylanVann/react-native-fast-image#126]
I installed FastIamge 0.1.2.
But it is not working for me.
show noting on screen.
I hope to help me ASAP.

**Comment by UADACID** [comment]
any update?

**Comment by brunolemos** [comment]
Please update your react-native version, this package only supports recent versions of it.
Current version is 0.53. Your version was released 8 months ago. Thanks.

**Comment by DylanVann** [comment]
Sorry, this module only supports the latest version of React Native.

https://github.com/DylanVann/react-native-fast-image#supported-react-native-versions
