### ISSUE TITLE
blurRadius not supported ?

### ISSUE THREAD

**Issue by EduardJS** [DylanVann/react-native-fast-image#127]
Hello!

Am I doing something wrong or this just doesn't support `blurRadius` ?

**Comment by n1ru4l** [comment]
This is a duplicate of #127. Please close it.

**Comment by EduardJS** [comment]
@n1ru4l What do you mean ... this is pull request #127

I searched for "blur" inside issues, found  nothing

**Comment by n1ru4l** [comment]
Sorry wrong issue copied 😢

#50 ist right one. You should have searched for blurRadius 😅
