### ISSUE TITLE
  The Android application is a mistake

### ISSUE THREAD

**Issue by guoguoss** [DylanVann/react-native-fast-image#128]
`Error while updating property 'source' of a view managed by:FastImageView
 null
No static method clear(Landroid/view/View;)V in class Lcom/bumptech/glide/Glide;or its super classes(declaration of 'com.bumptech.glide.Glide appears in /data/app/com.project-1/base.apk')`

**Comment by imcodervn** [comment]
I have same here.
@DylanVann can you re-check your library for this issues?

**Comment by thatjuan** [comment]
Dupe of #138 
Neither issue has a descriptive title or details

**Comment by DylanVann** [comment]
Is it that your application has a conflicting version of glide already installed? I need more details to look into this more.
