### ISSUE TITLE
style object is not passed to RN Image component

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [DylanVann/react-native-fast-image#130]
This is happening in version 2.1.3

https://github.com/DylanVann/react-native-fast-image/blob/5a67ff2cf037b74b288811931ea5f32ee9c75637/FastImage.js#L29

**Comment by brunolemos** [comment]
@chaitanya0bhagvan  Seems like an easy fix, please create a pull request.

**Comment by DylanVann** [comment]
Thanks for reporting, and for the PR 😄 . A new version has been released with this fix.
