### ISSUE TITLE
Image cache key and redirects

### ISSUE THREAD

**Issue by embpdaniel** [DylanVann/react-native-fast-image#133]
Hi, I am using fast image for Android, and my understanding is that the underlying library Glide will use the image's url as the key for caching. In the app I am building, the url I provide to fast image is something like "https://domain.com/api/users/1234/avatar/thumb", where 1234 is the user id and thumb is the type of image size to return. This url makes a re-direct to an s3 url with the correct image that I need. My question is, regarding caching, what url would become the cache key? Would it be the initial API url, or the s3 url I was re-directed to which points to the actual image size I needed?

The reason why I ask this is because the s3 url passes a query parameter that always changes, so if the key is the s3 url it looks like my images will never be cached.

Let me know, thanks

**Comment by DylanVann** [comment]
I'm not sure what would happen in your scenario. It sounds like it might end up never refreshing, because it will use https://domain.com/api/users/1234/avatar/thumb as the cache key. You could confirm this using something like [stetho](http://facebook.github.io/stetho/).

**Comment by DylanVann** [comment]
This might be relevant: https://github.com/bumptech/glide/issues/752#issuecomment-157519478

**Comment by embpdaniel** [comment]
Thanks for this info @DylanVann it clears things up. It indeed would use the api url, which is good news for me.

**Comment by msqar** [comment]
@embpdaniel im in the same situation as you, can you help me? how can i make this redirect work? doing also AWS redirects

**Comment by embpdaniel** [comment]
@msqar `react-native-fast-image` utilizes `Glide` under the hood for Android apps. `Glide` is an Android library for image caching. About the re-directs, did you check out @DylanVann 's link above? The redirects should not affect it. It worked fine on my project.

**Comment by msqar** [comment]
@embpdaniel dont worry! It was server's fault, HTTP images were causing this issue on Android due to cross-domain errors and insecurity... whenever we activated HTTPS redirects, everything started working as expected :) thanks for replying!
