### ISSUE TITLE
Glide cache signature

### ISSUE THREAD

**Issue by embpdaniel** [DylanVann/react-native-fast-image#134]
Curious if we are able to provide a Glide cache signature to control when the cache should clear? Our requirements state that images should be cached for 7 days then cleared. Is this possible? If not, it sounds that we can bust the cache by passing an extra query param to our image url that changes after 7 days. Could you confirm? Thanks!

**Comment by DylanVann** [comment]
I wrote some documentation on this: https://github.com/DylanVann/react-native-fast-image/blob/master/docs/how-is-caching-handled.md

To increase performance there is not fine grained control of the cache in this package. Ideally you would use immutable urls for your images. To work around this you can use a query parameter though.
