### ISSUE TITLE
Cannot render assets from smart album

### ISSUE THREAD

**Issue by uragecz** [DylanVann/react-native-fast-image#136]
I was using Image from react-native.. and assets from smartAlbum ( CameraRoll ) worked fine... but now when i changed it to FastImage... the photos just aren't rendered... the source uri for example is - "photos://106E99A1-4F6A-45A2-B320-B0AD4A8E8473/L0/001"
and like i said, it doesn't rendered... but when i change for example uri to 
'https://unsplash.it/400/400?image=1'
It works fine... so any ideas.. ?

**Comment by DylanVann** [comment]
I should clarify the readme, this package if intended to be used for remote images, not local images.

**Comment by DylanVann** [comment]
This is now handled, but currently falls back to `Image` (243b33db768b8afe4c58999db005600bda4a07dd). There is an open issue for displaying local images without a fallback.
