### ISSUE TITLE
package com.dylanvann.fastimage does not exist

### ISSUE THREAD

**Issue by vitto-moz** [DylanVann/react-native-fast-image#139]
Hi

after
yarn add react-native-fast-image
react-native link

react-native run-android  - executed 

then 
package com.dylanvann.fastimage does not exist
import com.dylanvann.fastimage.FastImageViewPackage;
                              ^
E:\path\path\path\
MainApplication.java:29: error: cannot find symbol
            new FastImageViewPackage(),
                ^
  symbol: class FastImageViewPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

**Comment by GustavoLucero** [comment]
Same error. Did you solve this problem?

**Comment by vitto-moz** [comment]
Unfortunately no :(

**Comment by adamlachmann** [comment]
Had the same problem, `react-native link` must have failed mid execution. Add
```
compile project(':react-native-fast-image')
```
to dependencies in `app/build.gradle`

**Comment by bl4ze** [comment]
@adamlachmann this solves the issue.

**Comment by DylanVann** [comment]
Yeah sometimes there are issues with link. It works in the standard way though, not any different than most other native packages.
