### ISSUE TITLE
Please allow contain children

### ISSUE THREAD

**Issue by lianzhongdandan** [DylanVann/react-native-fast-image#142]
Please allow contain children, Thank you!

**Comment by thatjuan** [comment]
Children support was a feature deliberately removed [in this commit](https://github.com/DylanVann/react-native-fast-image/commit/2df16ca0385c4e8bae42f7b94456ae456e31d22d) to keep the API close to that of <Image> and potentially other reasons.

**Comment by n1ru4l** [comment]
We could add a ImageBackground Component. (https://facebook.github.io/react-native/docs/images.html#background-image-via-nesting)

In the meantime you can implement your own based on https://github.com/facebook/react-native/blob/8547b7e11163d545b7b99d4bdd063ef71129d62c/Libraries/Image/ImageBackground.js

**Comment by DylanVann** [comment]
It supports children now. I was sort of flip flopping on how exactly to implement it for a bit.

**Comment by appli-intramuros** [comment]
Hello,

the problem is that "justifyContent style" does not work for children. 
I want to display children at the bottom of the image background by setting justifyContent : "flex-end", but it is not taken into account.
Do you know why ?

My code:

**Comment by appli-intramuros** [comment]
@subhamagr  I did not find any solution ...

**Comment by julioxavierr** [comment]
Any updates on this?

**Comment by abegehr** [comment]
@appli-intramuros, @subhamagr, `justifyContent: 'flex-end'` is working for me

**Comment by msqar** [comment]
@n1ru4l your method works like a charm, thank you good Sir!

**Comment by Dat-Mobile** [comment]
The 2023 solution should be
```
import React from 'react';
import {StyleSheet} from 'react-native';
import FastImage from 'react-native-fast-image';

const ImageBackground = props => {
  const {children, style} = props;

  return (
    <FastImage {...props} style={[StyleSheet.absoluteFill, style]}>
      {children}
    </FastImage>
  );
};

export default ImageBackground;
```

**Comment by dprajapati1179** [comment]
> We could add a ImageBackground Component. (https://facebook.github.io/react-native/docs/images.html#background-image-via-nesting)
> 
> In the meantime you can implement your own based on https://github.com/facebook/react-native/blob/8547b7e11163d545b7b99d4bdd063ef71129d62c/Libraries/Image/ImageBackground.js
> 
> Here is the component I use:
> 
> import React, { Component } from 'react'
> import { View, StyleSheet } from 'react-native'
> import FastImage from 'react-native-fast-image'
> 
> export default class ImageBackground extends Component {
>   render() {
>     const { children, style = {}, imageStyle, imageRef, ...props } = this.props
> 
>     return (
>       <View style={style} ref={this._captureRef}>
>         <FastImage
>           {...props}
>           style={[
>             StyleSheet.absoluteFill,
>             {
>               width: style.width,
>               height: style.height,
>             },
>             imageStyle,
>           ]}
>         />
>         {children}
>       </View>
>     )
>   }
> }


What about blurRadius capability of ImageBackground of React Native ?
