### ISSUE TITLE
Not able to show image on iOS.

### ISSUE THREAD

**Issue by witalobenicio** [DylanVann/react-native-fast-image#145]
I'm using this lib to load an image with the following url:
`https://stocker.isilist.com.br/api/v2/product_image/${ean}/thumb/` (to access it, a token is needed and I'm providing)

But I'm not able to load it. I think that could be because I'm not accessing the image directly...
because when I try with a url like: `http://www.donizete.com.br/sites/all/themes/bootstrap_subtheme/images/donizete-logo.png` it works pretty well.

Any ideas how to solve that?

**Comment by witalobenicio** [comment]
In fact, this lib isn't loading any image in iOS.

**Comment by witalobenicio** [comment]
Sorry again, it's displaying some images, but (maybe a coincidence) isn't loading any image from aws.

**Comment by DylanVann** [comment]
Could it be related to this: https://github.com/DylanVann/react-native-fast-image/issues/14

**Comment by DylanVann** [comment]
I'll need more info to look into this more.
