### ISSUE TITLE
borderRadius on android cause sawtooth.

### ISSUE THREAD

**Issue by yqz0203** [DylanVann/react-native-fast-image#153]
On ios borderRadius works fine and the edge is smooth, but on android the edge has sawtooth.

**Comment by DylanVann** [comment]
This is an issue with `react-native` core. I'm hoping to submit a PR to address it at some point.

This actually isn't apparent on high DPI phones.

**Comment by DylanVann** [comment]
@Agoujil2saad Awesome. I'll keep an eye out for it in the next release notes then close this when I have a chance to test.

**Comment by matpaul** [comment]
@DylanVann hi, on 5.1.1 and rn 0.57.5 we reproduce same sharp effect (sawtooth) 
```jsx
<View style={{width:20, height:20, borderRadius: 10}}>
   <FastImage source={...} style={{width:20, height:20}}> 
...
```

**Comment by RageOfJustice** [comment]
@DylanVann Hi! It seems fixed on Image RN component (0.59.0). But still sawtooth with FastImage component

**Comment by Twinski** [comment]
Is there any update on this? I can reproduce sharp edges on android on FastImage, when using borderRadius

**Comment by excitedcat** [comment]
The problem still exists !

**Comment by pqminh** [comment]
+1

**Comment by DylanVann** [comment]
Cannot reproduce, please open another issue with an example showing. If it's only older versions of RN or Android it probably will not be fixed.
