### ISSUE TITLE
A lot of problems

### ISSUE THREAD

**Issue by wq13718048209** [DylanVann/react-native-fast-image#154]
First of all, many methods don't work, such as loading success, failing to load, scheduling, and not printing back, and rounded corners that don't work at all.

**Comment by mnlbox** [comment]
@DylanVann Are you still maintained this package? Some useful PR and critical issue is open for loooong time :disappointed:

**Comment by DylanVann** [comment]
There was a release 22 days ago, so I think that counts as maintaining it. If there's something you want urgently sometimes you've just gotta fork it.

You may be using `borderRadius` inside `style` instead of using it as a prop. See: https://github.com/DylanVann/react-native-fast-image/issues/156

**Comment by mnlbox** [comment]
@DylanVann you right, but I think many PR and issue like below needs more attention:
#82 
#107 
#140 
#121 (Android Preload issue)
#148 (Issue with react-native-image-progress - it's still exist in Android but you close related issue)

I think react-native-fast-image needs more fix for production ready state.
