### ISSUE TITLE
Not loading image from encoded URL

### ISSUE THREAD

**Issue by kevinnguy** [DylanVann/react-native-fast-image#158]
I'm not able to load this particular image:
```http://lp.hm.com/hmprod?set=source%5B%2Fenvironment%2F2018%2FG00_0000_3992b303a7845119cfca493905357c54dce82f1a.jpg%5D%2Cmedia_type%5BLOOKBOOK%5D%2Ctshirt_size%5BL%5D%2Cquality%5BH%5D%2Csr_x%5B-327%5D%2Csr_y%5B0%5D%2Csr_height%5B3496%5D%2Csr_width%5B2990%5D%2Chmver%5B0%5D&call=url%5Bfile%3A%2Fstudio2%2Fv1%2Fproduct.chain%5D```

and I'm suspecting that it may have to do with the encoding of the URL but I'm not sure. I tried debugging this by using `onError` but it hasn't been useful. Any ideas? Thanks for the great library!

**Comment by DylanVann** [comment]
No idea why that wouldn't work. I'll try it out and see if I can see any errors on the native side.

**Comment by DylanVann** [comment]
It's app transport security. You need to use `https` or change your app transport security settings (using https is better).
