### ISSUE TITLE
Style isn't applied to image, unless borderRadius is added to props

### ISSUE THREAD

**Issue by 1k2k** [DylanVann/react-native-fast-image#159]

**Comment by DylanVann** [comment]
Yeah, that was the intention, but it does seem like it confused a lot of people.

I've just pushed an update that changes this behavior. It will now use `borderRadius` properties from `style`.

<img width="1095" alt="screen shot 2018-03-10 at 19 08 12" src="https://user-images.githubusercontent.com/1537615/37248168-288851d4-2498-11e8-98e0-3be3cf3c0e81.png">
