### ISSUE TITLE
[Question] How do i control cache expires?

### ISSUE THREAD

**Issue by anhtuank7c** [DylanVann/react-native-fast-image#16]
This is great module, but i wonder how do i control image cache expires.
In example: I do want to cache a.jpg file for a week.

Thank you so much.

**Comment by DylanVann** [comment]
By default `SDWebImage` and `Glide` do aggressive caching. They basically cache an image from a url as long as possible. An image will be cleared from the cache if the program runs out of space for caching images, on a first in first out basis.

There isn't a way to control max age for individual images.

If you want optimal performance though you should use immutable resources, new image, new url, cache is busted automatically, no worrying about expiration.

**Comment by anhtuank7c** [comment]
Thank you @DylanVann

**Comment by ovaris** [comment]
@DylanVann Both Glide and SDWebWebImage supports cache controlling, see https://github.com/rs/SDWebImage#handle-image-refresh
https://github.com/bumptech/glide/issues/1768

**Comment by fschai89** [comment]
please create method to clear all cache, thanks

**Comment by AE0011** [comment]
any solution to clear cache of a special url?

**Comment by JamieCorkhill** [comment]
@DylanVann Sorry to bring this thread back to life after so long, but I'm wondering if you could tell me what the max cache size is for Android and IOS.

I'm not looking to manipulate that size, I just want to know what the max size is. It is my understanding that Android does not control the max cache size.

Thank you.

**Comment by fhasni** [comment]
for iOS, you can edit the policy for SDWebImage by adding those two lines inside the function `didFinishLaunchingWithOptions` in `AppDelegate.m`
```
  [[[SDImageCache sharedImageCache] config] setMaxDiskAge:-1]; // No limit
  [[[SDImageCache sharedImageCache] config] setMaxDiskSize:0]; // No limit
```
