### ISSUE TITLE
Preload local images

### ISSUE THREAD

**Issue by camdagr8** [DylanVann/react-native-fast-image#160]
Is there anyway to preload local images that are `required()`? 

I'm using the `react-native-navigation` module for screen management and when the view loads the image is not visible, then after the animation completes, it renders the image.  

I have the following `render()` function: 

```js
render() {
    let styles = {
        position:        'absolute',
        top:             0,
        left:            0,
        flex:            1,
        width:           Dimensions.get('screen').width,
        height:          Dimensions.get('screen').height,
    };

    return (
        <ScrollView>
            <FastImage
                source={require('./assets/images/background.png')}
                style={styles.bgImage}
                resizeMode={'cover'} />
        </ScrollView>
    );
}
```

**Comment by DylanVann** [comment]
This module doesn't load local images, it falls back to using `Image`, so there's no way to preload local images.

**Comment by koodiohto** [comment]
@DylanVann I wish you would add the support for locally stored images, because in my case there is an unfortunate flicker/flash even with locally stored images (fairly large images) when using the react-native Image-component. :)

**Comment by camdagr8** [comment]
@koodiohto: If it helps, I figured out a way to cache local images. I run the following command when my app is setting up: 




List if images to preload:
```js
    // Preload images with require();
    const images = {
      'icon.png': require('./icon.png'),
      'orbs-1.png': require('./orbs-1.png'),
      'orbs-2.png': require('./orbs-2.png'),
      'orbs-3.png': require('./orbs-3.png'),
      'survey-1.png': require('./survey-1.png'),
    };
```

Image processor:
```
    // Convert image refs into image objects with Image.resolveAssetSource
    loadImages(images) {        
        return Promise.all(Object.keys(images).map((i) => {
            let img = {
                ...Image.resolveAssetSource(images[i]),
                cache: 'force-cache'
            };

            return Image.prefetch(img);
        }));
    }
```

Usage: 
```js
 loadImages(images).then((results) => { /* do something with the image objects */ });
```

**Comment by DylanVann** [comment]
I am going to add support for local images. Probably soon / in the next major version. For now it does fallback to `Image` though.

**Comment by isaachinman** [comment]
@DylanVann Any update on local image support?

**Comment by kevinjacyna** [comment]
@camdagr8 Thanks for your example, I'm struggling with how I would then use the images that are cached. I am calling the loadImages function in my App.js file in componentDidMount, and would like to access the cached images from my Welcome component. Any help would be much appreciated!

My Images class:
```javascript
import { Image } from 'react-native';

export default class Images {
  constructor() {
    this.loadImages = this.loadImages.bind(this);
  }

  loadImages = images => {
    return Promise.all(
      Object.keys(images).map(i => {
        let img = {
          ...Image.resolveAssetSource(images[i]),
          cache: 'force-cache'
        };

        return Image.prefetch(img);
      })
    );
  };
}
```

And in my App.js:

```javascript
const imagesObject = {
  'full-screen-gradient.png': require('./src/images/full-screen-gradient.png'),
  'tennis-court.png': require('./src/images/tennis-court.png')
};

componentDidMount() {
    this.images.loadImages(imagesObject).then(results => {
      this.setState({
        loading: false
      });
    });
  }
```
And then in my Welcome screen component I am attempting to access the cached image like so
```javascript
      <ImageBackground
        style={styles.backgroundImage}
        source={'tennis-court.png'}
      >
```

If you could shine some light on where I'm going wrong that would be awesome, thanks in advance!

**Comment by dipeshkoirala21** [comment]
hello, can somebody help me how to work with ImagePicker uri? 
Currently, i have this 
`file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540anonymous%252Ftfjs-app-163e476a-4d39-48a7-9272-6156e46d3add/ImagePicker/214a32e3-3cc5-46f1-bd61-48255a92b4dc.png ` as url and  i did this
```
const imageAssetPath = Image.resolveAssetSource(url); 
const response = await fetch(imageAssetPath.uri, {}, { isBinary: true });
```
but its throwing TypeError: null is not an object(evaluating 'imageAssetPath.uri') as a warning. What am i doing wrong? Can somebody help me figure out this?

**Comment by alexander01202** [comment]
This has still not been added??
