### ISSUE TITLE
Color artifacts on Images (Android)

### ISSUE THREAD

**Issue by TilWs** [DylanVann/react-native-fast-image#161]
Images are showing weird color artifacts after the recent updates on Android (iOS works fine), like white or lightgreyish backgrounds which should have low contrast showing waves of light pink, mint and light blue. Normal RN image component displays the image fine.
Big image in the screenshot is a normal Image component, the smaller ones are using FastImage, all have the same image source.
![screenshot_20180312-125707](https://user-images.githubusercontent.com/33658116/37282674-8de1dd76-25f5-11e8-8c43-c6f7b7f56aca.png)

**Comment by DylanVann** [comment]
That's odd. Probably something Glide is doing as far as compression. Could you post the original image so I can reproduce this and try to fix it?

**Comment by n1ru4l** [comment]
Could be related to this: https://github.com/DylanVann/react-native-fast-image/pull/82

**Comment by TilWs** [comment]
@DylanVann We have the same problem with all images, but there you go: https://static.odernichtoderdoch.de/media/image/2d/b8/e5/60215_web_600x600.jpg

**Comment by fangasvsass** [comment]
please update glide to 4.x  this issue will be fixed

**Comment by DylanVann** [comment]
Merged https://github.com/DylanVann/react-native-fast-image/pull/164 which fixes this issue. Thanks @TilWs
