### ISSUE TITLE
please add some document about new API (onLoadEnd)

### ISSUE THREAD

**Issue by mnlbox** [DylanVann/react-native-fast-image#167]
Hi,

Thanks for merge #107 PR but I think we need some document about new API. How we can get image height and weight for loaded image from onLoadEnd?

**/CC:** @DylanVann, @jeremyclee, @ararog

**Comment by DylanVann** [comment]
A new version has been published. Documentation has been added to the readme. 

The information is added to the `onLoad` callback, since in the case of an error and `onLoadEnd` callback would not have had the info.
