### ISSUE TITLE
fatal error: too many errors emitted, stopping now

### ISSUE THREAD

**Issue by denny64** [DylanVann/react-native-fast-image#17]
Works perfectly on Android, but fails to build on iOS. Any ideas?

I'm running `react-native` 0.36.0

<img width="940" alt="screen shot 2017-07-03 at 1 38 04 pm" src="https://user-images.githubusercontent.com/9099997/27777312-0ce1ae0c-5ff5-11e7-856f-8465cea9ede4.png">

**Comment by stinodes** [comment]
+1
Having the same issue right now, seemingly out of the blue.
