### ISSUE TITLE
Android can not follow redirect

### ISSUE THREAD

**Issue by Yanjing123** [DylanVann/react-native-fast-image#178]
Now I have a image url is
https://xxxx.com/Users/Images/xxx.jpg
when access this url the server will redirect it to
https://xxxx.com/version_code/Users/Images/xxx.jpg

And in ios this image can show, but android can't. any idea how to go about fixing this?

**Comment by DylanVann** [comment]
I'm not sure. It would help a lot to have an example of a url that causes this issue.

**Comment by Yanjing123** [comment]
@DylanVann Sorry, finally found our server has user agent check, so it's not this component bug.
I will close this issue, thanks.

**Comment by DylanVann** [comment]
@Yanjing123 Thanks! 👍

**Comment by msqar** [comment]
Happening on my Huawei P20 Lite, the redirect is not working, it works on iOS tho

**Comment by Stevemoretz** [comment]
Facing this on the latest version.

**Comment by Stevemoretz** [comment]
Nope my bad, I was using a `X-Sendfile:` header not 301 works perfectly!
