### ISSUE TITLE
Dimensions not being passed to onLoad()

### ISSUE THREAD

**Issue by macavity23** [DylanVann/react-native-fast-image#181]
My onLoad handler is not receiving dimensions for the loaded image. Using code from the example:
```
<FastImage style={styles.photo}
           source={{uri: url}}
           onLoad={e => console.log(e.nativeEvent.width, e.nativeEvent.height)} />
```
This logs 'undefined, undefined' to the console. e.nativeEvent appears to have only one key, `target` (int).

The image is displaying fine. This is using 4.0.0 on the iOS simulator.

**Comment by pingxiaodou** [comment]
The same issue

**Comment by iorikingdom** [comment]
+1 
it seem working when using android ,but problem with ios

**Comment by iorikingdom** [comment]
I found the point 
Because the _onFastImageLoad called without any params
``
                                NSDictionary* params = @{
                                                         @"width":[NSNumber numberWithDouble:image.size.width],
                                                         @"height":[NSNumber numberWithDouble:image.size.height]
                                                         };
                                fastImageLoadParams = params;

and 

        _onFastImageLoad(fastImageLoadParams);

will fixed it...

**Comment by ligen52** [comment]
same issue+1 with iOS;
when it's first time ,the width and height is returned.
but when it loaded from cache ,no correct result returned.

**Comment by DylanVann** [comment]
Yeah because the properties from JS can be set in a different order the loading of the image may finish before the callbacks are set.

Out of curiousity, what do you use the dimensions of the image for anyways?

Closing the issue, thanks for the PR @ligen52 .

**Comment by macavity23** [comment]
To satisfy your curiosity, I need the image dimensions to calculate animation interpolations. Now I can use FastImage and my images won't flicker on load any more!

Thanks @ligen52 for the fix & @DylanVann for merge 🙏

**Comment by manithin** [comment]
> Yeah because the properties from JS can be set in a different order the loading of the image may finish before the callbacks are set.
> 
> Out of curiousity, what do you use the dimensions of the image for anyways?
> 
> Closing the issue, thanks for the PR @ligen52 .

Is there any ways to solve this? In my case, I have a slideshow with swipable images. When the first image is loaded, onload returns me the correct dimensions. But from next image onwards(when I swipe on the component, it loads the next image), it just returns the dimension of the first loaded image.
I use the dimensions from the call back to adjust the size of the slideshow but now that does not work.

**Comment by manithin** [comment]
> > Yeah because the properties from JS can be set in a different order the loading of the image may finish before the callbacks are set.
> > Out of curiousity, what do you use the dimensions of the image for anyways?
> > Closing the issue, thanks for the PR @ligen52 .
> 
> Is there any ways to solve this? In my case, I have a slideshow with swipable images. When the first image is loaded, onload returns me the correct dimensions. But from next image onwards(when I swipe on the component, it loads the next image), it just returns the dimension of the first loaded image.
> I use the dimensions from the call back to adjust the size of the slideshow but now that does not work.

Nevermind this. Happened since the resizeMode was "FastImage.resizeMode.cover". get it worked agin by changing the value to "FastImage.resizeMode.contain"
