### ISSUE TITLE
resizeMode.cover not working properly

### ISSUE THREAD

**Issue by venux92** [DylanVann/react-native-fast-image#184]
First Thanks for the module, image loads very fast.

I have an issue with resizeMode
I have set both via `<FastImage>` and `<Image>` but I don't get the same result.

The first image is set with <FastImage>
`<FastImage style={styles.image}
source={{
		uri: item.image,
		priority: FastImage.priority.normal,
		}}
		resizeMode={FastImage.resizeMode.cover}
/>`

The second image with <Image>
`<Image width={Theme.width * 0.85} source={{ uri: item.image }} style={styles.image}/>`

I have the same styling parameters for both.

Any idea why I can't get the same result as with `<Image>`?

![simulator screen shot - iphone 6 - 2018-04-17 at 18 03 20](https://user-images.githubusercontent.com/20675272/38856884-100e26ec-426b-11e8-8be3-f9cb086cde2b.png)

**Comment by DylanVann** [comment]
Thank you for the info. I'm closing this as a duplicate, but I will take a look at the other issue.

I think it would help to have all the resize modes shown in the example app compared to `Image` so we can ensure `FastImage` is working correctly.

https://github.com/DylanVann/react-native-fast-image/issues/19
