### ISSUE TITLE
FastImage does not  work well in animation when using 'Animated.createAnimatedComponent(FastImage)'

### ISSUE THREAD

**Issue by kphungry** [DylanVann/react-native-fast-image#185]
We have changed Image tag to FastImage for several days. Everything goes well before I take notice to the transition animation. The animation gone.
A piece of code looks like this:
 ```
const AnimatedComp = Animated.createAnimatedComponent(FastImage);
let sharedElements = React.createElement(AnimatedComp,
            {...element.props, style: [element.props.style, animatedStyle]},
            element.props.children);
 ...
return (
            <Animated.View style={[styles.overlay, this.props.style, containerStyle]}>
                {sharedElements}
            </Animated.View>
        );
```

Version: 4.0.0

**Comment by kphungry** [comment]
I have found out it. FastImage is composing Component which need to implement the _setNativeProps_ for animation. But the previous one put the _ref_ in the wrong place.

**Comment by DylanVann** [comment]
What sort of things are you trying to animate?

I'm thinking:

- opacity
- scale

I'll merge your fix, I just also want to add an example of an animated image so that regressions can be prevented in the future.

**Comment by kphungry** [comment]
I am so sorry. I am a little of busy these days. 

My animation is complicated. I use it on transition animation just like Pinterest. It contains scale and transform. 

Maybe I can make it a demo on Github.

**Comment by DylanVann** [comment]
I tried it out, seems to work. Update pushed as `v4.0.7`.
