### ISSUE TITLE
[Android] Warning: Native component for "FastImageView" does not exist [SOLVED]

### ISSUE THREAD

**Issue by toinfinityandbeyond** [DylanVann/react-native-fast-image#187]
I found myself with this issue and I was able to fix it for iOS as it's explained in #51 
However, I didn't find anything for Android... so I had to fix it myself. 
I'm writing down here what was the solution for me in order to help others with the same issue.
It seems that react-native link does not do his work properly sometimes, so there was a missed line in `android/app/src/main/java/com/PROJECT_FOLDER/MainApplication.java` you must add 

`return Arrays.<ReactPackage>asList(`
            `(.... all your packages list)`
          `  new FastImageViewPackage()`

Be sure that previously you have imported the library at the top of the file 
`import com.dylanvann.fastimage.FastImageViewPackage;`

In case this solution doesn't work for you, these are the files you must check:

At `android/settings.gradle` add 
`include ':react-native-fast-image' `
`project(':react-native-fast-image').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fast-image/android')`

At `android/app/build.gradle` add 
`dependencies {`
    `compile project(':react-native-fast-image')`
   ` (...all your dependencies)
`

Hope it helps!

**Comment by DylanVann** [comment]
Yeah, unfortunately sometimes `react-native link` doesn't work properly.

I've added manual linking instructions here: https://github.com/DylanVann/react-native-fast-image/blob/master/docs/installation-manual.md

**Comment by jalpesh** [comment]
Even after linking and with the latest release as well as the latest in master, I keep getting the error fastimageview view config not found. Can someone help us out? Works perfectly in the demo app.

**Comment by stylianospanagakos** [comment]
Same problem with Android even after following steps for manually linking lib.

**Comment by jalpesh** [comment]
There were many things i needed to change to get it to work. 
1) The compile version & glide version had to be same for my package.
2) On updating the sdk version, I had to change the implements image to implements AppCompat image.

As an offshot, can you check if you have written .addPackage(new FastImageView()) in your native android code where you are using react fast image?

**Comment by iqqmuT** [comment]
@jalpesh Can you explain in more details what kind of changes you had to make? I wonder if #258 is related to this.

**Comment by Jalpesh-indus** [comment]
@iqqmuT  Can you show me your versions and the code where you are using fastimage?

**Comment by chinavane** [comment]
"react-native": "0.59.9",
    "react-native-fast-image": "6.0.3",
same problem
