### ISSUE TITLE
Build failed in v4.0.4

### ISSUE THREAD

**Issue by wellyshen** [DylanVann/react-native-fast-image#189]
Hi I upgraded to v4.0.4. But it cause building failed.

<img width="1018" alt="2018-04-22 11 30 42" src="https://user-images.githubusercontent.com/21308003/39096630-6325df28-4685-11e8-8aec-a32a8ec57fdd.png">

**Comment by DylanVann** [comment]
Could you try cleaning in xcode and let me know if that fixes it? Thank you

I've added other troubleshooting steps here: https://github.com/DylanVann/react-native-fast-image/blob/master/docs/troubleshooting.md

**Comment by edo1493** [comment]
I am experiencing the same. :\

**Comment by DylanVann** [comment]
@edo1493 Have you tried those troubleshooting steps?

I've cleaned all the stale data I can think of and installed the new version on a new React Native project and it builds and works for me.

I'd like to be able to test on another machine to be 100% sure but I don't have one available at the moment. Also thinking about setting up some CI for this but all the iOS CI solutions cost money and I'm not sure yet which one would be best for this.

**Comment by peterlazar1993** [comment]
Got the same error as well, using pods is not an option for me.

**Comment by DylanVann** [comment]
Apparently when running fastlane `#import <SDWebImage/FLAnimatedImageView.h>` doesn't work.

**Comment by VicFrolov** [comment]
Yep, same issue here. Running in debug mode, releaser throws same error. Tried all the steps as well (clearing cache, deleting modules/build folder, watchman del all, npm start reset cache, delete derived data in xcode, cmk shift k)

**Comment by brianfoody** [comment]
Had to downgrade to 3.0.2

**Comment by DylanVann** [comment]
`v4.0.3` should work.

```bash
yarn add react-native-fast-image@4.0.3
```

I'll try to resolve this tonight.

**Comment by DylanVann** [comment]
`v4.0.6` is released. This issue should be fixed now.

Ended up doing it like this:

- Conditional import - https://github.com/DylanVann/react-native-fast-image/commit/084a41497d5688c7939f94be7d48d2f2ad74fb74
- Fix other header search path - https://github.com/DylanVann/react-native-fast-image/commit/ac00fdaa6309f03afc3bf052584a99c18726d21e

Seems to work in all the scenarios I tested:

- Debug/Release
- Using CocoaPods
- Using fastlane

Let me know if this fixes things, thank you
