### ISSUE TITLE
is FastImage base on RN Image ?

### ISSUE THREAD

**Issue by jielongz** [DylanVann/react-native-fast-image#190]
i want to use RN Image props like defaultSource to show default-placeholder image when image not load,
but some props is not support on FastImage

**Comment by DylanVann** [comment]
Some of the API is based on the API of `Image` to make it easy for people to switch, but there is no claim made about it being a drop in replacement.

The properties in the documentation are the properties that are supported.

For what you want you can use absolute positioning and a local image behind your network image.

Here is the open issue for adding this feature: https://github.com/DylanVann/react-native-fast-image/issues/5
