### ISSUE TITLE
FastImage causing Crash in IOS : Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by VasudevAkhil** [DylanVann/react-native-fast-image#191]
Hi Dylan,

    I am experiencing memory issues on using your module. Can you please take a look at this issue?

Regards,
Akhil Vasudev

**Comment by VasudevAkhil** [comment]
Hi Dylan,

    I will appreciate if you can look into this issue.Although the product solves all our requirements and the fetching speed and other features are very good but we are facing random crashes due to memory issues. 
    I hope that you will provide speedy solution.

Regards,
Akhil Vasudev

**Comment by DylanVann** [comment]
I'm closing the open issues related to memory so things are better organised. See: https://github.com/DylanVann/react-native-fast-image/issues/195
