### ISSUE TITLE
Memory overload when caching a lot of images

### ISSUE THREAD

**Issue by VicFrolov** [DylanVann/react-native-fast-image#194]
We are using pagination on our app, and have an "endless" scroll for products in our catalogue. It works great when there's only 30-50 images to display, but the memory skyrockets when we scroll through our flatlist, and the app ends up accruing over 200 mb of memory from react-native-fast-image, and then the app crashes.

Is there currently a way to clear the cached images if, for example, if there is > 50 images?

Can confirm it is react-native-fast-image, for when we switch to react-native's `Image`, this issue does not persist.

Occurs on all versions 4.0.0-4.0.7

**Comment by DylanVann** [comment]
I'm going to try to get to the bottom of this in this issue: https://github.com/DylanVann/react-native-fast-image/issues/195

I'm closing the other issues related to memory but I'll refer to them when I'm looking into that issue. Thank you for the information.
