### ISSUE TITLE
Add borderRadius support.

### ISSUE THREAD

**Issue by pfulop** [DylanVann/react-native-fast-image#2]
Hi,
I was just wondering if you plan supporting border radius style on images. At least on android it seems that this rule is ignored.

**Comment by DylanVann** [comment]
It's not supported currently. I'll look into how easy it would be to add.

**Comment by pfulop** [comment]
Well I switched to react-web-image and found out there is beta branch which has this funcionality implemented. https://github.com/vovkasm/react-native-web-image/issues/2 . You can find inspiration there if it is still relevant for you.

**Comment by grundmanise** [comment]
So even if we wrap it inside a `View` and set a `borderRadius` & `overflow: 'hidden'` on that `View` the image won't be `clipped`?

**Comment by bestlbw** [comment]
i think  u can look this to support radius,https://github.com/wasabeef/glide-transformations

**Comment by RUIFERNANDE5** [comment]
Yea, borderRadius not being supported is quite a bummer, would be awesome if we got it

**Comment by baba43** [comment]
We definitely need this before we can use this library.

Sadly I could not find any workaround to make it work, so it would be awesome to see this added :-)

**Comment by tsaohucn** [comment]
Need this too.

**Comment by dorthwein** [comment]
Same here.... ;(

**Comment by justinlok** [comment]
+1

**Comment by gitlovenotwar** [comment]
+1, even a parent view with border radius and overflow hidden, the image won't get clipped. Using react-native Image component, is working(though their caching fails on ios)

**Comment by AkilLis** [comment]
How about that.

`<View style={styles.circle}>
<FastImage style={styles.image} />
<View style={styles.fixCircleClipping}/>
</View>`

`circle: {
    width: circleSize,
    height: circleSize,
    borderRadius: circleSize / 2,
    overflow: 'hidden',
  },
  fixCircleClipping: {
    position: 'absolute',
    top: -circleFixBorder,
    bottom: -circleFixBorder,
    right: -circleFixBorder,
    left: -circleFixBorder,
    borderRadius: circleSize / 2 + circleFixBorder / 2,
    borderWidth: circleFixBorder,
    borderColor: bgColor
  },`

**Comment by anhtuank7c** [comment]
@AkilLis `overflow: 'hidden'` does not supported on `Android`

**Comment by vvavepacket** [comment]
according here, https://github.com/DylanVann/react-native-fast-image/pull/58 bordeRadius has been added, but when i tried on android, it does not work. did u guys managed to solve the issue?

**Comment by AkilLis** [comment]
It is worked as i said. You need to try this out!.

**Comment by jslok** [comment]
@AkilLis it doesn't work for me. Looks like you need to know the exact size of the image beforehand too.

**Comment by vvavepacket** [comment]
@AkilLis  which fixed u mean? I tried adding borderRadius to the component,, but it is still squared..

**Comment by pvsong** [comment]
Same issue.

**Comment by gogumai** [comment]
@DylanVann it looks like [#58](https://github.com/DylanVann/react-native-fast-image/pull/58) it's not on npm yet.

Can you please upload this feature?

Thanks!!

**Comment by tquiroga** [comment]
Same issue

**Comment by vvavepacket** [comment]
guys it works on iOS, but not on android

**Comment by OGPoyraz** [comment]
Bump

**Comment by FlorianBergmann** [comment]
+1 for Android support

**Comment by anhtuank7c** [comment]
You all can use wrap by **View** and use `overflow: hidden, borderRadius: 5`
RN support hidden on Android from version 0.50

**Comment by tmaly1980** [comment]
Yes, I concur with @anhtuank7c . Just upgrade to RN 0.50.0 and use overflow:hidden on the view container (which I tend to use anyway for scaling purposes)

**Comment by tehwayne** [comment]
would be nice to get this support vs wrapping all the images in views

**Comment by DylanVann** [comment]
`borderRadius` support has been added. I went with the containing view solution for reasons outlined here: https://github.com/DylanVann/react-native-fast-image/pull/59#issuecomment-361796662

Thank you for the help!

**Comment by ezha86** [comment]
can anyone confirm that border radius does work on android ?
for me seems it doesnt
"react-native": "^0.53.0",
"react-native-fast-image": "^2.2.5",

**Comment by vit3k** [comment]
For me it works on simulator but not on Samsung S6.

**Comment by wmonecke** [comment]
This is still not working on android:

"react-native": "0.47.1",
"react-native-fast-image": "^5.0.3",

**Comment by anhtuank7c** [comment]
@wmonecke You have to upgrade to RN `0.50.0` or newer version

**Comment by coucoseth** [comment]
was borderRadious added because it isnt working on my end on android

**Comment by jesspinklet** [comment]
@coucoseth in our case we had to giva a background color to fast image as well in order to make it work.
`backgroundColor: "transparent"`
transparent bg works as well .
