### ISSUE TITLE
Support Base64 images on Android.

### ISSUE THREAD

**Issue by anhtuank7c** [DylanVann/react-native-fast-image#20]
I do display base64 image with FastImage, work well on iOS, show blank view on Android.

**Comment by andreechristian** [comment]
Is this issue resolved yet? I still got this bug on Jan 2018

**Comment by matt-oakes** [comment]
At the very least it should show a warning if you try to do this to avoid potential issues.

**Comment by victorileaf** [comment]
Same Issue !!

**Comment by anhtuank7c** [comment]
Something like: https://stackoverflow.com/questions/34588905/how-to-load-image-through-byte-array-using-glide?answertab=votes#tab-top

https://github.com/DylanVann/react-native-fast-image/blob/master/android/src/main/java/com/dylanvann/fastimage/FastImageViewModule.java#L37

**Comment by newaz** [comment]
Any update ?

**Comment by badver** [comment]
Here is a workaround:
You can set base64 string this way:
```
const image = `data:${mimeType};base64,${base64String}`
<FastImage
      source={{ uri: image }} <---- put base64 with mimetype here
/>
```

Where mimeType depends on content. 
I use [this code](https://gist.github.com/badver/4b6a3d3bce269713bc0b255146885df5) to resolve type from a file extension.

**Comment by anhtuank7c** [comment]
@badver Does it work on Android? iOS still working well.

**Comment by badver** [comment]
@anhtuank7c Yes.

**Comment by DylanVann** [comment]
There's an example of base64 usage in the example application:

- https://github.com/DylanVann/react-native-fast-image/blob/4d8c74945df460bd89ad2bb74c86efb6ccf76c48/ReactNativeFastImageExample/src/images/fields.ts
- https://github.com/DylanVann/react-native-fast-image/blob/4d8c74945df460bd89ad2bb74c86efb6ccf76c48/ReactNativeFastImageExample/src/LocalImagesExample.tsx#L96
