### ISSUE TITLE
TransformException: Error while generating the main dex list When upgrade 4.0.8

### ISSUE THREAD

**Issue by mbizplus** [DylanVann/react-native-fast-image#203]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithMultidexlistForRelease'.
> com.android.build.api.transform.TransformException: Error while generating the main dex list.

Version:
 "react-native": "0.55.0",
  "react-native-fast-image": "^4.0.8",

It working fine 4.0.3, this issue only 4.0.5 & 4.0.8

**Comment by DylanVann** [comment]
Try adding the proguard rules: https://github.com/DylanVann/react-native-fast-image#proguard

**Comment by mbizplus** [comment]
@DylanVann It working after i update to version 4.0.12

**Comment by bobmulder** [comment]
Got the exact same error like @mbizplus mentioned. I used the latest release: `4.0.14`. Gave it a change to downgrade to `4.0.12` but it worked!

@DylanVann any idea why downgrading worked well? :)

**Comment by DylanVann** [comment]
@bobmulder I'm not sure. Maybe something to do with this: https://github.com/DylanVann/react-native-fast-image#proguard
