### ISSUE TITLE
onLoad never called if the image is taken from cache

### ISSUE THREAD

**Issue by theys1995** [DylanVann/react-native-fast-image#208]
Hi,

Great library btw. I've stumbled upon this issue after trying to make a loading component for the FastImage one showing an activity indicator while the image is... well loading 😄 . The odd thing is that the onLoadStart is called, but no other callback happens if the image is taken from cache. One solution would be to force the image to be reloaded every time by altering the request param from the url but that would just defeat the purpose.

I've tested only on iOS. Is this a problem with the underlying iOS library or does this behaviour happen on Android too ?

**Comment by DylanVann** [comment]
@theys1995 Are you using the most recent version of `react-native-fast-image`? This was an issue before but I think it's been fixed.

**Comment by davidrichard23** [comment]
I'm actually getting this using 4.0.14. `onLoadStart` is the only one that works, `onLoad onLoadEnd and onProgress` never get called. I'm unsure what info I can provide to help figure out what's happening since it seems like I've run into a rare edge case.

```
<FastImage 
					style={styles.image} 
					source={{uri: url}} 
					resizeMode='contain' 
					onLoadStart={() => {
						console.log('loading')
						this.setState({ loading: true })
					}} 
					onProgress={(e) => {
						console.log('progress')
						this.setState({ loading: false })
					}}  
					onLoadEnd={() => {
						console.log('loaded')
						this.setState({ loading: false })
					}} 
				/>
```

**Comment by davidrichard23** [comment]
Fixed it. I had to delete the app's `/Users/<username>/Library/Developer/Xcode/DerivedData` folder after upgrading from a previous version.

**Comment by minhchienwikipedia** [comment]
Is it closed? I got this issue on Android, I onError it's work but onLoadStart never called. How can I resolve it?

**Comment by saghul** [comment]
@DylanVann I think needs further investigation. Just like @minhchienwikipedia I'm running into this after updating from 4.0.14 to 5.0.3.

**Comment by chudaotrucnhan** [comment]
I got this issue on Android with react native fast image version 5.1.2 onError nerver called.

**Comment by JuliusCosmoRomeo** [comment]
I've got the same issue: onLoadEnd is never called for external resources on Android, only for local ones.
RN Fast Image 6.0.3 and RN 0.57.8

**Comment by AnilkumarDO** [comment]
I am also getting same issue, Is it fixed?

**Comment by wsdt** [comment]
Getting this issue too

**Comment by Kogilapriadarsini** [comment]
I also getting the same issue in RN 0.60.4 and fast image 7.0.2.. any resolution?

**Comment by felix-voicehub** [comment]
Getting this still with RN 61.5 and FastImage 8.1.5

**Comment by casaumayman** [comment]
I'm still getting this error with RN 0.64.1 and fast-image 8.3.7, just only onLoadStart called.
![image](https://user-images.githubusercontent.com/42993140/129528230-15b8aeae-4651-4057-99bd-418fa0131a36.png)

**Comment by hb-webdev** [comment]
`onLoadStart` is the only prop on Android that gets called for me.`onLoad`, `onError`, and `onLoadEnd` never do.

However, I am using conditional rendering of the `display` style... (i.e., switching between `display='none'` & `display='flex'`): `style={{display: imageDisplay}}`

EDIT: Sigh...Apparently it's a known issue: https://github.com/DylanVann/react-native-fast-image/issues/529
