### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by ajonno** [DylanVann/react-native-fast-image#21]
After installing and linking, I'm seeing this when trying to display image(s):

![image](https://user-images.githubusercontent.com/3005269/28066453-5340b69a-6680-11e7-9464-367e0bbde43a.png)

React native version: 0.42.3

To start with just tried rendering a canned image, like this:

```
<FastImage
   style={styles.image}
   source={{ 
      uri: 'https://facebook.github.io/react/img/logo_og.png', 														
      priority: FastImage.priority.normal
   }} 
   resizeMode={FastImage.resizeMode.contain}
/>
```

Any ideas why we are not seeing the images render ?

**Comment by bang88** [comment]
Do you try to rerun `react-native run-ios` or run it from xcode ?

**Comment by DylanVann** [comment]
Yeah you have to link the library and then do a build of the native application. Red border on components is an indication that it's not linked and built.

**Comment by Shashi147** [comment]
even after linking the library , same issue

**Comment by gitlovenotwar** [comment]
I am having the same issue. Image is not rendering.

**Comment by angeloocana** [comment]
+1

**Comment by Unlighten** [comment]
Same issue

**Comment by barjas** [comment]
same issue even after rebuild

**Comment by DylanVann** [comment]
It won’t work in Expo. Expo will not allow you to use third party native libraries. If you want this though you can vote up this feature request:

https://expo.canny.io/feature-requests/p/add-react-native-fast-image
