### ISSUE TITLE
Very high resolution images

### ISSUE THREAD

**Issue by wq13718048209** [DylanVann/react-native-fast-image#210]
I have a very large array images, a set of resolution I put them in the FlatList display, the question now is, I'm not sure their width and height, but I want to keep the width of the image is equal to the width of the screen, scaling, such as height can I use the fast - image but not high effect seems to have a fixed width only do you have any idea

**Comment by DylanVann** [comment]
These are remote images right?

If you don't know the height you would need to pass in a temporary height until the image loads.
You can then use `onLoad` to get the actual height and set it. (https://github.com/DylanVann/react-native-fast-image#onerror---void)

Maybe in the future auto height will be supported, but I think the reason it isn't with `Image` and the reason I'm hesitant to implement it is that this sort of sizing causes UI jank. It's usually better to have approximate dimensions and use an appropriate `resizeMode`.

**Comment by wq13718048209** [comment]
Thank you very much   i think ,  How do I do that ,  Thank you for your reminding!  This component of yours is very good ,I come from China ,A lot of people around me are using it,I hope you can do better

**Comment by DylanVann** [comment]
@wq13718048209 Glad you find it useful.

Check out this example to see what I meant about using `onLoad`, but alternatively just choose a fixed height and use a `resizeMode`, that's usually a better user experience.

https://github.com/DylanVann/react-native-fast-image/blob/master/react-native-fast-image-example/src/AutoSizeExample.js
