### ISSUE TITLE
Problem with the version of support-v4

### ISSUE THREAD

**Issue by PangGua00** [DylanVann/react-native-fast-image#225]
I have a problem with the version of `com.android.support:support-v4`.
Path: Project --> android --> build.gradle  
Code: 
```
dependencies{
    compile "com.android.support:support-v4:${_compileSdkVersion}"              
}
```
Error: `couldn't resolve "com.android.support:support-v4:23"`
When I changed the code to `compile "com.android.support:support-v4:${_compileSdkVersion}.+"` manually, it worked.   
Hope can give me some advice for this problem, thanks.

**Comment by hufans** [comment]
Please tell us how to solve this problem?
