### ISSUE TITLE
Problem adding git repo to dependencies

### ISSUE THREAD

**Issue by Mikunj** [DylanVann/react-native-fast-image#227]
Hey, i've been trying to add this repo as a dependency to a project using yarn using the following command:
```
yarn add https://github.com/DylanVann/react-native-fast-image.git
```
However it fails with 
```
git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git
error Command failed with exit code 128.
```

Is there anyway to fix this? We are already using version `4.0.14` but want to upgrade to the latest `master` build as it has features that we really require for our app.

**Comment by Mikunj** [comment]
Solved.

Worked when i used:
```
yarn add DylanVann/react-native-fast-image.git
```

**Comment by ardalahmet** [comment]
@Mikunj Thanks a lot!
