### ISSUE TITLE
Add Support for React Native 0.56+

### ISSUE THREAD

**Issue by csotiriou** [DylanVann/react-native-fast-image#235]
According to https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#056 RN will use babel 7.

> React Native now uses Babel 7. When upgrading to 0.56, make sure to bump your babel-preset-react-native package.json dependency to ^5.0.1 or newer. If you have a library, please make sure that you update the preset there too as Babel 7 is not backwards compatible. Once 0.56 reaches stable, we will move the babel-preset-react-native@latest tag to 5.0.1.

I suppose react-native-fast-image should be updated for this reason.

**Comment by fzyzcjy** [comment]
+1

**Comment by DylanVann** [comment]
This actually is not a concern for most React Native libraries since we ship non-transpiled code.
