### ISSUE TITLE
Add a way to use Glide for local images on Android

### ISSUE THREAD

**Issue by tdboone** [DylanVann/react-native-fast-image#237]
I'm working on an app that uses react-native-fast-image for rendering GIFs because we're running into memory issues when using the built-in react-native `Image` component to rending our GIFs, and things are working great on that end.

I'm currently implementing a feature that saves GIFs locally for future use, which presents a problem on Android, as react-native-fast-image automatically falls back to rendering the built-in `Image` component for any uri that begins with `file://`.

Is there an easy update that would allow me to render a local GIF image the same way I can render a remote GIF image? And is there some workaround I can use in the meantime?

**Comment by gugakatsi** [comment]
@tdboone guess it's already merged #205 , check pr , i guess that's solution at least for images idk , i am interested in too.

**Comment by DylanVann** [comment]
It's done! Try one of the newer versions, thanks!
