### ISSUE TITLE
Control cache time?

### ISSUE THREAD

**Issue by baba43** [DylanVann/react-native-fast-image#24]
Is it possible to define / control how long images are cached by this library? 
How long are images cached at all when using this library?

I'm asking this because I want to use this library for user-specific data that might get deleted. If so, the images (that are not related to any up-to-date content and so never shown again) should not stay forever, obviously.

Maybe this is a dumb question but hopefully someone will answer it anyway. 

Thank you.

**Comment by efstathiosntonas** [comment]
@DylanVann how much is this `set size`? Is there a way to change it or force clear cache programmaticaly with a button?

**Comment by DylanVann** [comment]
I don't think people need control that is that granular in most situations. Why do you think you need this capability?

Closing this issue for now.
