### ISSUE TITLE
Invariant Violation: Native component for "FastImageView" does not exist

### ISSUE THREAD

**Issue by shayegh** [DylanVann/react-native-fast-image#240]
Hi,
when I add Fastimage to my project, i got the "Invariant Violation: Native component for "FastImageView" does not exist" error.
please help me

**Comment by tanforce** [comment]
"react-native-fast-image": "2.0.1"
我导入的是这个版本，直接react-native link react-native-fast-image 就可以使用了，最新版本的我也试了，ios也报你这个问题，一直没找到好的解决方式

**Comment by denis-shostik** [comment]
You should install native module using cocoapods

**Comment by shayegh** [comment]
it has bin solved (now picker open) by adding
.addPackage(new PickerPackage())
to
mReactInstanceManager = ReactInstanceManager.builder()
.setApplication(getApplication())
.setBundleAssetName("index.android.bundle")
.setJSMainModulePath("index")
.addPackage(new MainReactPackage())
.addPackage(new FastImage())
.setUseDeveloperSupport(BuildConfig.DEBUG)
.setInitialLifecycleState(LifecycleState.RESUMED)
.build();
