### ISSUE TITLE
Error when installing another library

### ISSUE THREAD

**Issue by NdozHH** [DylanVann/react-native-fast-image#244]
When you install another library, the android fast-image project disappears and you have to install it again and make the link, which is very annoying and tedious, some solution?

**Comment by n1ru4l** [comment]
If you are talking about ios I would recommend to use cocoapods

**Comment by NdozHH** [comment]
And for Android?

**Comment by DylanVann** [comment]
There isn't enough detail to make any recommendation. There's probably something wrong with your specific setup.
