### ISSUE TITLE
1st: Nice Work 2nd: Question regarding dependencies

### ISSUE THREAD

**Issue by spacegraym3** [DylanVann/react-native-fast-image#26]
node: 8.2.1
react-native-cli: 2.0.1
react-native: 0.43.2

I added updated a fork or react-native-photo-browser to use your FastImage.  For some reason, I get the following compilation error:

```
 FFFastImageView.h:5:9: fatal error: 'FLAnimatedImageView.h' file not found
#import "FLAnimatedImageView.h"
        ^
1 error generated.
```
Aside from yarn add react-native-fast-image and running react-native link, what else do I need to do?  Looks like the paths are incorrect?

**Comment by DylanVann** [comment]
Hello 😃 , I'm not sure what would cause that error.`FLAnimatedImageView` should be included with this module. It may be something to do with incorrect header search paths for your project.

If I do an install and link on a new React Native project the header search paths are like this:

<img width="1920" alt="screen shot 2017-08-08 at 1 16 13 am" src="https://user-images.githubusercontent.com/1537615/29057281-3df98ade-7bd7-11e7-8c7c-0c536c3d4c6a.png">

**Comment by DylanVann** [comment]
Closing this issue for now.
