### ISSUE TITLE
Android does not compile: Could not resolve all files for configuration

### ISSUE THREAD

**Issue by jankrah12** [DylanVann/react-native-fast-image#260]
Error:

Could not resolve all files for configuration ':react-native-fast-image:releaseCompileClasspath'.
> Could not find support-annotations.jar (com.android.support:support-annotations:26.1.0).
  Searched in the following locations:
      https://jcenter.bintray.com/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar

Here is my build.gradle with relevant parts:

```
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.invites"
        minSdkVersion 21
        targetSdkVersion 27
        versionCode 16
        versionName "1.1.16"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
}

dependencies {
    implementation project(':react-native-fast-image')
    implementation project(':react-native-linear-gradient')
    implementation project(':react-native-image-resizer')
    implementation project(':react-native-view-shot')
    implementation project(':react-native-fetch-blob')
    implementation "com.google.android.gms:play-services-base:15.0.0"
    implementation 'com.android.support:multidex:1.0.1'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
      transitive = true
    }

apply plugin: 'com.google.gms.google-services'
```

**Comment by tobi512** [comment]
Hi, 
sounds like you're missing the Android Support Repository (installed via SDK Manager -> SDK Tools) or have a corrupt/old version of it installed. Check what version you have and maybe try a reinstall of the repo if it's already installed (uncheck and apply, then recheck and apply again...).
