### ISSUE TITLE
How I can set placeholder image

### ISSUE THREAD

**Issue by wdayanand** [DylanVann/react-native-fast-image#265]

**Comment by rendomnet** [comment]
@Fsarmento your placeholder is not correct. 
Placeholder must be visible unless source is not **dowloaded**. Or if source was not downloaded at all(because of some error or not reachable)

**Comment by Fsarmento** [comment]
Oh, I see. There is an older issue for that - [#5](https://github.com/DylanVann/react-native-fast-image/issues/5). In the last [comment](https://github.com/DylanVann/react-native-fast-image/issues/5#issuecomment-398090447) there is a workaround using 2 overlapped Images.

**Comment by nica0012** [comment]
Really waiting on this!

**Comment by devpascoe** [comment]
Oh for sure, would love this.

**Comment by EgidioCaprino** [comment]
This PR adds `placeholder` prop https://github.com/DylanVann/react-native-fast-image/pull/409

**Comment by EhsanSarshar** [comment]
wrap it in a helper component

({source, placeHolder}) => {
    const [source, setSource] = useState(placeHolder)
    <FastImage  source={source}. onLoadEnd={ () => setSource({uri: source}) }/>
}

**Comment by muhammad786** [comment]
Seems still no support for a placeholder, following is my workaround for placeholder 


`<View>
            { loading &&
                <MImage
                containerStyle={imageStyle}
                uri={placeholderUri}
                />
            }
            <FastImage
            style={loading?{width:0, height:0}:imageStyle}
            source={uri}
            onLoad={()=>{
                setTimeout(()=>{
                    setLoading(false)
                },100)
            }}            
            resizeMode={FastImage.resizeMode.contain}        
            />
        </View>`

**Comment by chramos** [comment]
> Seems still no support for a placeholder, following is my workaround for placeholder
> 
> `<View> { loading && <MImage containerStyle={imageStyle} uri={placeholderUri} /> } <FastImage style={loading?{width:0, height:0}:imageStyle} source={uri} onLoad={()=>{ setTimeout(()=>{ setLoading(false) },100) }} resizeMode={FastImage.resizeMode.contain} /> </View>`

I did something like that but I noticed that I lost the cache feature... I mean, every time I "rerender" my component I see the placeholder and after some milliseconds I see the real image

**Comment by AJV2018** [comment]
`                        <ImageBackground
                            style={styles.dp}
                            source={require('../../assets/item-img-placeholder.png')} >
                            <FastImage
                                style={styles.dp]}
                                source={{
                                    uri: state.image,
                                }}
                            />
                        </ImageBackground>
`

**Comment by DylanVann** [comment]
This library now supports `defaultSource`, if that doesn't meet your needs you could try something else from this thread, like the layering solution.

**Comment by yoann84** [comment]
It's super laggy with default source with Flashlist (didn't try with flatlist)
