### ISSUE TITLE
Error while updating property 'source' of a view managed by: FastImageView  null  null

### ISSUE THREAD

**Issue by Amurmurmur** [DylanVann/react-native-fast-image#27]
I dont know whats the problem.
Exactly the same code works fine on iOS, Android however, throws the following:
<img width="423" alt="screen shot 2017-07-30 at 02 49 48" src="https://user-images.githubusercontent.com/8608333/28749493-e309d2ac-74d1-11e7-887e-a333fea20f14.png">

My environment:
RN v0.46.2
Android 5.0.1
RNFI v0.1.2

**Comment by weddell** [comment]
@Amurmurmur - I just got this error too - It seems to do with hot reloading, if you rebuild the package with react-native run-android it seems to fix it

**Comment by Amurmurmur** [comment]
@DylanVann Alrighty, so I've figured out that the problem exists from the version 0.1.0+ 
By downgrading to 0.0.11 I've been able to run the app with no problems on both platforms, though borderRadius on android doesnt get applied as I've mentioned in another issue.

**Comment by JLWalsh** [comment]
Also facing this problem.

**Comment by lugrugzo** [comment]
Same problem with Android.

**Comment by Amurmurmur** [comment]
@lugrugzo  just downgrade to 0.0.11 for now

**Comment by lugrugzo** [comment]
I did that to fix the problem. 

_Sent from my Xiaomi MI 5s using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by DylanVann** [comment]
Thanks for the bug report.
I am not a Java developer. Technically I am but... I just wanted to make a list...

See fix here: https://github.com/DylanVann/react-native-fast-image/commit/f21522c4092c9ccf5a8c83e56f2c5c4ae3ddc1c8

**Comment by brunitob** [comment]
v0.1.4 Im getting error when compiling 

`
error: FastImageViewPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class FastImageViewPackage implements ReactPackage {
       ^

Execution failed for task ':react-native-fast-image:compileReleaseJavaWithJavac'.
`

**Comment by DylanVann** [comment]
You need to update React Native. createJSModules is deprecated. Should have
done a major version bump, sorry.

**Comment by DylanVann** [comment]
Now available as `v1.0.0`.

**Comment by Amurmurmur** [comment]
@brunitob @DylanVann  I've created a pull request for backward compatibility your error if you use RN < 0.47
#38

**Comment by tdekoning** [comment]
For future references: I encountered the same issue, but it only happened on builds that have proguard turned on.
To fix that, add glide's proguard rules to your project, see https://github.com/krschultz/android-proguard-snippets/blob/master/libraries/proguard-glide.pro

**Comment by jslok** [comment]
I'm having this error show up by my users in my bugsnag account though I have not been able to reproduce it in dev. I'm not really sure where to start on this. I have proguard disabled. Here is the full error from bugsnag. Using react-native-fast-image 1.0.0 and have had this error on react-native 0.47.x and 0.49.x. Any help would be much appreciated!

```
com.facebook.react.bridge.JSApplicationIllegalArgumentException · Error while updating property 'source' of a view managed by: FastImageView
Raw
ViewManagersPropertyCache.java:95com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp	
ViewManagerPropertyUpdater.java:129com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty	
ViewManagerPropertyUpdater.java:48com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps	
ViewManager.java:34com.facebook.react.uimanager.ViewManager.updateProperties	
NativeViewHierarchyManager.java:227com.facebook.react.uimanager.NativeViewHierarchyManager.createView	
UIViewOperationQueue.java:153com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute	
UIViewOperationQueue.java:809com.facebook.react.uimanager.UIViewOperationQueue$1.run	
UIViewOperationQueue.java:922com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches	
UIViewOperationQueue.java:47com.facebook.react.uimanager.UIViewOperationQueue.access$2100	
UIViewOperationQueue.java:880com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded	
GuardedRunnable.java:21com.facebook.react.bridge.GuardedRunnable.run	
Handler.java:739android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:148android.os.Looper.loop	
ActivityThread.java:7406android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
ZygoteInit.java:1230com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:1120com.android.internal.os.ZygoteInit.main	
Caused By: java.lang.reflect.InvocationTargetException ·
Method.java:-2java.lang.reflect.Method.invoke	
ViewManagersPropertyCache.java:83com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp	
ViewManagerPropertyUpdater.java:129com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty	
ViewManagerPropertyUpdater.java:48com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps	
ViewManager.java:34com.facebook.react.uimanager.ViewManager.updateProperties	
NativeViewHierarchyManager.java:227com.facebook.react.uimanager.NativeViewHierarchyManager.createView	
UIViewOperationQueue.java:153com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute	
UIViewOperationQueue.java:809com.facebook.react.uimanager.UIViewOperationQueue$1.run	
UIViewOperationQueue.java:922com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches	
UIViewOperationQueue.java:47com.facebook.react.uimanager.UIViewOperationQueue.access$2100	
UIViewOperationQueue.java:880com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded	
GuardedRunnable.java:21com.facebook.react.bridge.GuardedRunnable.run	
Handler.java:739android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:148android.os.Looper.loop	
ActivityThread.java:7406android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
ZygoteInit.java:1230com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:1120com.android.internal.os.ZygoteInit.main	
Caused By: java.lang.IllegalArgumentException · You cannot start a load for a destroyed activity
RequestManagerRetriever.java:134com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed	
RequestManagerRetriever.java:125com.bumptech.glide.manager.RequestManagerRetriever.get	
RequestManagerRetriever.java:89com.bumptech.glide.manager.RequestManagerRetriever.get	
RequestManagerRetriever.java:91com.bumptech.glide.manager.RequestManagerRetriever.get	
Glide.java:657com.bumptech.glide.Glide.with	
FastImageViewManager.java:143com.dylanvann.fastimage.FastImageViewManager.setSrc	
Method.java:-2java.lang.reflect.Method.invoke	
ViewManagersPropertyCache.java:83com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp	
ViewManagerPropertyUpdater.java:129com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty	
ViewManagerPropertyUpdater.java:48com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps	
ViewManager.java:34com.facebook.react.uimanager.ViewManager.updateProperties	
NativeViewHierarchyManager.java:227com.facebook.react.uimanager.NativeViewHierarchyManager.createView	
UIViewOperationQueue.java:153com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute	
UIViewOperationQueue.java:809com.facebook.react.uimanager.UIViewOperationQueue$1.run	
UIViewOperationQueue.java:922com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches	
UIViewOperationQueue.java:47com.facebook.react.uimanager.UIViewOperationQueue.access$2100	
UIViewOperationQueue.java:880com.facebook.react.uimanager.UIViewOperationQueue$2.runGuarded	
GuardedRunnable.java:21com.facebook.react.bridge.GuardedRunnable.run	
Handler.java:739android.os.Handler.handleCallback	
Handler.java:95android.os.Handler.dispatchMessage	
Looper.java:148android.os.Looper.loop	
ActivityThread.java:7406android.app.ActivityThread.main	
Method.java:-2java.lang.reflect.Method.invoke	
ZygoteInit.java:1230com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run	
ZygoteInit.java:1120com.android.internal.os.ZygoteInit.main
```

**Comment by aidinb** [comment]
same here

**Comment by christophby** [comment]
Any news?

**Comment by buffaly** [comment]
Same problem here
RN 0.49
Fast-image 1.0.0
production on Android 4,6,7

**Comment by pampang** [comment]
Same problems here in android...
RN: 0.44.3,
react-native-fast-image: 1.0.0

Could anyone helps?

**Comment by johnlim5847** [comment]
do you guys have any solution for this?

**Comment by imcodervn** [comment]
same here. If I create a new project and add this library, it fine. But if I add this library into the project that I working, it not working. I don't know why.

**Comment by skizzo** [comment]
Anybody able to solve this?

**Comment by 1k2k** [comment]
@tdekoning solution worked for me, it was proguard!

**Comment by DylanVann** [comment]
For people wondering if this is proguard you can try adding these lines: https://github.com/DylanVann/react-native-fast-image#proguard

**Comment by Maniae** [comment]
Hi, I'm still facing this issue after editing my proguard file with the above configurations. I also tried the one given in #96. I then realized I was not using proguard in development anyway.
FastImage component is working fine on iOS, also working on Android with remote JS debugger, but crashing with this error on Android in development without remote JS debugger.
Using react 16.4.1 RN 0.56.0 RNFI 5.0.3

**Comment by Lichwa** [comment]
Experiencing the same issue, even in debug mode so I don't think it's related to proguard in any way.

**Comment by stephan-nordnes-eriksen** [comment]
Perhaps useless comment to some, but I was not able to get this to work, even when seemingly disabling proguard completely.

I ended up downgrading to version 4.0.14, and now it works. 

Not the preferred solution, but at least one solution, if you were completely stuck, like me.

**Comment by LuisRodriguezLD** [comment]
I tried everything but still had the error in dev mode, @stephan-nordnes-eriksen 'solution' worked

**Comment by evanjmg** [comment]
+1 having this issue as well.

**Comment by diegolmello** [comment]
It's happening here on 5.1.1
Downgrading to 5.0.11 seems to fix.

**Comment by luoyushouchai** [comment]
@diegolmello Encountering both on v 5.0.11 and 5.1.1

**Comment by krisidmisso** [comment]
same here 
![image](https://user-images.githubusercontent.com/9657055/50699814-36d38680-1049-11e9-80ee-f922c80864e5.png)

**Comment by diegolmello** [comment]
Still happens on 5.1.2.

**Comment by jaltin** [comment]
I've also just ran into this problem on versipn 5.1.1

**Comment by WrathChaos** [comment]
Still happens on 5.1.2. 
@DylanVann any chance to fix it?

**Comment by diegolmello** [comment]
If I'd have to guess, I'd say [this commit](https://github.com/DylanVann/react-native-fast-image/commit/47e36edc24a1990eeb735527ae4ebe6d2dbe61b5) is causing this issue.
Does anyone managed to isolate the error?
I couldn't simulate it, but it appears on Fabric.

**Comment by sokki** [comment]
this happened to me on 5.1.2 when using wrong urls without protocol (like `//example.com/pic.jpg`).

**Comment by spruce-bruce** [comment]
FWIW @sokki's comment helped me get past this issue.

I'm displaying images from disk and a source uri like this: `/some/path/to/file` would cause this error, but `file:///some/path/to/file` would not.

**Comment by Akramz** [comment]
Still happens on **5.2.0**

Stack trace from Fabric:

**Fatal Exception: com.facebook.react.bridge.JSApplicationIllegalArgumentException
Error while updating property 'source' of a view managed by: FastImageView**
```
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.getPropName (ViewManagersPropertyCache.java)
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java)
com.facebook.react.uimanager.ViewManagerPropertyUpdater.clear (ViewManagerPropertyUpdater.java)
com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java)
com.facebook.react.uimanager.NativeViewHierarchyManager.resolveView (NativeViewHierarchyManager.java)
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations (UIViewOperationQueue.java)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java)
...
```

**Caused by java.lang.IllegalArgumentException
Must not be null or empty**

```
com.bumptech.glide.util.Preconditions.checkArgument (Preconditions.java)
com.bumptech.glide.load.model.GlideUrl. (Unknown Source)
com.dylanvann.fastimage.FastImageSource.getGlideUrl (FastImageSource.java)
com.dylanvann.fastimage.FastImageViewManager.setSrc (FastImageViewManager.java)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.getPropName (ViewManagersPropertyCache.java)
com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty (ViewManagerPropertyUpdater.java)
com.facebook.react.uimanager.ViewManagerPropertyUpdater.clear (ViewManagerPropertyUpdater.java)
com.facebook.react.uimanager.ViewManager.updateProperties (ViewManager.java)
com.facebook.react.uimanager.NativeViewHierarchyManager.resolveView (NativeViewHierarchyManager.java)
com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute (UIViewOperationQueue.java)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.dispatchPendingNonBatchedOperations (UIViewOperationQueue.java)
com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded (UIViewOperationQueue.java)
com.facebook.react.uimanager.GuardedFrameCallback.doFrame (GuardedFrameCallback.java)
com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame (ReactChoreographer.java)
com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame (ChoreographerCompat.java)
...
```

**Comment by diegolmello** [comment]
Just an update from my side:
I figured in some cases my server returns only part of the url and I have to append to create the full url.
Server returns this: `images/image.png`
Correct url: `https://server/images/image.png`
This case would trigger this error and crash the app.

By making sure `http` or `https` is always present, I can run 5.3.0 on production :)

**Comment by loyoliteabid** [comment]
I got resolved this error when i followed the instruction given in https://github.com/DylanVann/react-native-fast-image 

If you use Proguard you will need to add these lines to `android/app/proguard-rules.pro`

```
-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```

**Comment by jowe13** [comment]
This problem is still present for me using:
"react-native-fast-image": "5.1.1".

I already added the lines of the comment above to my proguard-rules.

However this problem only seems to be appearing with remote images and not with locally bundled images. Anyone have an idea to help?

**Comment by WrathChaos** [comment]
After 2 years, that problem still there on Android. We should solve and make a PR :)

**Comment by joepake** [comment]
@WrathChaos try bellow command to clone resources from rn to res android
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res

**Comment by WrathChaos** [comment]
@joepake Thank you but I've tried it but not working with it. Also, this error also appears on iOS either.

**Comment by minhphung210** [comment]
i have same issues on production with version 5.2.0 
add 
`-keep public class com.dylanvann.fastimage.* {*;}`
`-keep public class com.dylanvann.fastimage.** {*;}`

not work for me :(

**Comment by manujbahl** [comment]
Any solution for this?

**Comment by KalebPortillo** [comment]
Facing the same issue

**Comment by almorak** [comment]
> I got resolved this error when i followed the instruction given in https://github.com/DylanVann/react-native-fast-image
> 
> If you use Proguard you will need to add these lines to `android/app/proguard-rules.pro`
> 
> ```
> -keep public class com.dylanvann.fastimage.* {*;}
> -keep public class com.dylanvann.fastimage.** {*;}
> -keep public class * implements com.bumptech.glide.module.GlideModule
> -keep public class * extends com.bumptech.glide.module.AppGlideModule
> -keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
>   **[] $VALUES;
>   public *;
> }
> ```

added but still same
"react-native": "0.60.5"
"react-native-fast-image": "^7.0.2",

**Comment by glennvgastel** [comment]
FYI - I fixed this by simple checking if the given url is valid.

**Comment by puneetBinary** [comment]
Can't resolve by adding these lines In proguard
-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}


"react-native": "0.60.5"
"react-native-fast-image": "^7.0.2"

Did anyone resolve on this version?

**Comment by zhangyugehu** [comment]
**I got the solution**

for me, when i given url start with '//'. like '//abc.com/aaa.png'. so i fixed by hook fastImage's render
````JavaScript
static fixFastImage() {
  const oldRender = FastImage.render;
  FastImage.render = function render(...args) {
    if (args&&args.length&&args.length>0&&args[0]&&args[0].source) {
      const { source } = args[0];
      if (source.uri&&/^\/\//.test(source.uri)) {
        source.uri = 'https://i1.wp.com/www.ecommerce-nation.com/wp-content/uploads/2018/10/404-error.jpg?fit=800%2C600&ssl=1';
      }
    }
    const origin = oldRender.call(this, ...args);
    return React.cloneElement(origin);
  };
}
````

**Comment by puneetBinary** [comment]
I got the solution too, 
First, run the project on Android studio for a better view of errors. Check your URL of the Image you are receiving, If It Is correct then go to the fast Image library and give the not null check to the glideUrl Object In FastImageViewManager.java file. If the URL Is not correct then check from the backend or see what you are appending for Image for making Url

**Comment by mlbz198** [comment]
> I got the solution too,
> First, run the project on Android studio for a better view of errors. Check your URL of the Image you are receiving, If It Is correct then go to the fast Image library and give the not null check to the glideUrl Object In FastImageViewManager.java file. If the URL Is not correct then check from the backend or see what you are appending for Image for making Url

Can you tell me clearly? Thanks!

**Comment by puneetBinary** [comment]
Just run the project on Android studio and you will get the error In the log cat. You can click and go to that class and that line and give the null pointer check or put a try cache check

**Comment by dunglamhawking** [comment]
Is this fixed yet?

**Comment by schumannd** [comment]
@dunglamhawking doesn't seem to be. Invalid URLs (for me the whole domain part was missing) cause android to crash while iOS does not.

**Comment by oferRounds** [comment]
Same here, any workaround?

**Comment by rodionovich221** [comment]
I just found a solution from [this answer](https://github.com/DylanVann/react-native-fast-image/issues/407#issuecomment-476153632).

just prettify url of your source with this line of code, it did a magic. ;)
`const normalisedSource = source && typeof source.uri === 'string' && !source.uri.split('http')[1] ? null : source;`

**Comment by oferRounds** [comment]
@rodionovich221 @DylanVann shouldn’t this check be included in the library itself?

**Comment by simply999** [comment]
> @lugrugzo just downgrade to 0.0.11 for now
How do you downgrade？

**Comment by simply999** [comment]
> @lugrugzo just downgrade to 0.0.11 for now

How do you downgrade？

**Comment by diegothem** [comment]
Perhaps this would help people experiencing the issue, on our project we have Fabric and the latest two versions of the Fabric Gradle plugin [`1.31.2`](https://docs.fabric.io/android/changelog.html#october-15-2019)  and [`1.31.1`](https://docs.fabric.io/android/changelog.html#id82) is causing this exception only in the .apk generated by the `.aab` file. In the version [`1.31.0`](https://docs.fabric.io/android/changelog.html#july-24-2019) it doesn't appear.

**Comment by baotoan1905** [comment]
I don't think it's something wrong with URL, since I tried to hardcode url like bellow, still facing same error 
I'm using react-native 0.61.5, fastimage 8.1.5
![image](https://user-images.githubusercontent.com/7258479/79528058-366ecb80-8093-11ea-829f-7c1c2c38b813.png)

**Comment by simply999** [comment]
error url.
you can try opening the url



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Toan Nguyen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 中午11:07
收件人:&nbsp;"DylanVann/react-native-fast-image"<react-native-fast-image@noreply.github.com&gt;;
抄送:&nbsp;"amaris.li"<739970281@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DylanVann/react-native-fast-image] Error while updating property 'source' of a view managed by: FastImageView  null  null (#27)





 
I don't think it's something wrong with URL, since I tried to hardcode url like bellow, still facing same error
 I'm using react-native 0.61.5, fastimage 8.1.5

**Comment by simply999** [comment]
Higher versions should be compatible



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Diego Rotondale"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月13日(星期一) 下午4:36
收件人:&nbsp;"DylanVann/react-native-fast-image"<react-native-fast-image@noreply.github.com&gt;;
抄送:&nbsp;"amaris.li"<739970281@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DylanVann/react-native-fast-image] Error while updating property 'source' of a view managed by: FastImageView  null  null (#27)





 
Perhaps this would help people experiencing the issue, on our project we have Fabric and the latest two versions of the Fabric Gradle plugin 1.31.2  and 1.31.1 is causing this exception only in the .apk generated by the .aab file. In the version 1.31.0 it doesn't appear.

**Comment by thanhdevapp** [comment]
handler local image and fix

class ProgressiveImage extends React.Component {

    getUriImage(uri) {
        return uri !== null && uri !== undefined && uri.includes("/") && uri.includes(".") ? uri : ""
    }

    render() {
        let source = this.props.source;
        return (
            <View style={styles.container}>
                {this.props.source && this.props.source.uri ? <FastImage {...this.props} source={{
                    uri: this.getUriImage(this.props.source.uri),
                    cache: FastImage.cacheControl.immutable,
                }} /> : <Image {...this.props} />}
            </View>
        )
    }
}

**Comment by meashishpokhrel** [comment]
const CarouselItem = ({ item }) => {
    return (
        <View style={styles.cardView}>
            <FastImage style={styles.image} source={{ uri: item.url }} />
            <View style={styles.textView}>
                <Text style={styles.itemTitle}> {item.title}</Text>
                <Text style={styles.itemDescription}>{item.description}</Text>
            </View>
        </View>
    )
}

I am getting the error Updating property "source" of a view managed by : FastImageView
null
must not be a null or empty string...

Please can any body help me this?
BTW it runs perfecly when i use <Image/>

**Comment by meashishpokhrel** [comment]
```
const CarouselItem = ({ item }) => {
    return (
        <View style={styles.cardView}>
            <FastImage style={styles.image} source={{ uri: item.url }} />
            <View style={styles.textView}>
                <Text style={styles.itemTitle}> {item.title}</Text>
                <Text style={styles.itemDescription}>{item.description}</Text>
            </View>
        </View>
    )
}

const CarouselItem = ({ item }) => {
    return (
        <View style={styles.cardView}>
            <FastImage style={styles.image} source={{ uri: item.url }} />
            <View style={styles.textView}>
                <Text style={styles.itemTitle}> {item.title}</Text>
                <Text style={styles.itemDescription}>{item.description}</Text>
            </View>
        </View>
    )
}
```

**Comment by meashishpokhrel** [comment]
```
const CarouselItem = ({ item }) => {
    return (
        <View style={styles.cardView}>
            <FastImage style={styles.image} source={{ uri: item.url }} />
            <View style={styles.textView}>
                <Text style={styles.itemTitle}> {item.title}</Text>
                <Text style={styles.itemDescription}>{item.description}</Text>
            </View>
        </View>
    )
}
```
I am getting the error Updating property "source" of a view managed by : FastImageView
null
must not be a null or empty string...

Please can any body help me this?
BTW it runs perfecly when i use

**Comment by simply999** [comment]
Please check if the URL is valid







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DylanVann/react-native-fast-image"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月16日(星期三) 晚上10:10
收件人:&nbsp;"DylanVann/react-native-fast-image"<react-native-fast-image@noreply.github.com&gt;;
抄送:&nbsp;"amaris.li"<739970281@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [DylanVann/react-native-fast-image] Error while updating property 'source' of a view managed by: FastImageView  null  null (#27)





 
const CarouselItem = ({ item }) =&gt; {
 return (
 
 <FastImage style={styles.image} source={{ uri: item.url }} /&gt;
 
  {item.title}
 {item.description}
 
 
 )
 }
 
I am getting the error Updating property "source" of a view managed by : FastImageView
 null
 must not be a null or empty string...
 
Please can any body help me this?
 BTW it runs perfecly when i use

**Comment by meashishpokhrel** [comment]
> Please check if the URL is valid
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "DylanVann/react-native-fast-image" <notifications@github.com&gt;; 发送时间:&nbsp;2020年9月16日(星期三) 晚上10:10 收件人:&nbsp;"DylanVann/react-native-fast-image"<react-native-fast-image@noreply.github.com&gt;; 抄送:&nbsp;"amaris.li"<739970281@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [DylanVann/react-native-fast-image] Error while updating property 'source' of a view managed by: FastImageView null null (#27) const CarouselItem = ({ item }) =&gt; { return ( <FastImage style={styles.image} source={{ uri: item.url }} /&gt; {item.title} {item.description} ) } I am getting the error Updating property "source" of a view managed by : FastImageView null must not be a null or empty string... Please can any body help me this? BTW it runs perfecly when i use — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes the URL Is Valid.
WHen i use Image tag the pictures pop out normally.
PLz any solutions?

**Comment by meashishpokhrel** [comment]
WHen i console log URL
I get:  https://firebasestorage.googleapis.com/v0/b/kisanapp-6c486.appspot.com/o/images%2Fimage1.jpg?alt=media&token=6dec40cc-e246-4be0-b8e4-5627d3d99923

Exact Location of my image which means url is not empty

**Comment by KhoaN56** [comment]
I meet this problem again. The url is available but it keeps display the error sheet telling me that null or empty isn't allowed.

**Comment by simply999** [comment]
please give me your url



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Khoa ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 下午5:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DylanVann/react-native-fast-image] Error while updating property &#39;source&#39; of a view managed by: FastImageView  null  null (#27)





 
I meet this problem again. The url is available but it keeps display the error sheet telling me that null or empty isn't allowed.

**Comment by KhoaN56** [comment]
> please give me your url
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Khoa ***@***.***&gt;; 发送时间: 2021年6月24日(星期四) 下午5:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [DylanVann/react-native-fast-image] Error while updating property &#39;source&#39; of a view managed by: FastImageView null null (#27) I meet this problem again. The url is available but it keeps display the error sheet telling me that null or empty isn't allowed. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry. I've found it's not the lib's issue. Thank you for your care. 😂

**Comment by dhairyasenjaliya** [comment]
still exists on debug android
