### ISSUE TITLE
Source.cache doesn't exist + strange cache

### ISSUE THREAD

**Issue by ishigamii** [DylanVann/react-native-fast-image#274]
HI, I just read the documentation and install the lib in my app and it's working pretty nicely now.

To start I am using : 
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-fast-image": "^5.0.3",
```

Though I am having a bug/crash when I try to use the cache property of the source like described in the documentation : 

> source.cache?: enum
> FastImage.cache.immutable - (Default) - Only updates if url changes.
> FastImage.cache.web - Use headers and follow normal caching procedures.
> FastImage.cache.cacheOnly - Only show images from cache, do not make any network requests.

If I put that in my code or check the code the `cache` object in `FastImage` doesn't exist which result in a crash.

<img width="309" alt="capture d ecran 2018-08-31 a 17 52 56" src="https://user-images.githubusercontent.com/26909067/44922833-c76e2300-ad46-11e8-9018-e9f040c8cbdc.png">

my code is : 

```
        <FastImage
          style={{ height: 200, marginVertical: 8 }}
          source={{
            uri: myurl,
            priority: FastImage.priority.normal,
            cache: FastImage.cache.cacheOnly,
          }}
          resizeMode={FastImage.resizeMode.cover}
        />
```

Second point is more a question. I am having one first page where you can see a **gif** loaded with FastImage very fast and then I got to a second view and doing the same simple code the gif is taking very long to charge this time. I don't understand why it charged fast at first and on a second view with the same url so it should be charged from cache it just takes like 20 secondes even longer than loading it with default `Image`. 

The code is : 
```
        <FastImage
          style={{ height: 200, marginVertical: 8 }}
          source={{
            uri: myurl,
            priority: FastImage.priority.normal,
          }}
          resizeMode={FastImage.resizeMode.cover}
        />
```

Thanks a lot
Hope it will help.

**Comment by r8** [comment]
I've got the same issue with FastImage.cache, so had to check the sources.

@ishigamii Looks like docs are inaccurate in this case. 
Try `FastImage.cacheControl.cacheOnly`

```
FastImage.cacheControl = {
    // Ignore headers, use uri as cache key, fetch only if not in cache.
    immutable: 'immutable',
    // Respect http headers, no aggressive caching.
    web: 'web',
    // Only load from cache.
    cacheOnly: 'cacheOnly',
}
```
