### ISSUE TITLE
Showing Local GIF

### ISSUE THREAD

**Issue by sadeghhosseini** [DylanVann/react-native-fast-image#278]
Would you care to explain with an example the procedure of adding a local GIF to your project using react-native-fast-image?

**Comment by DylanVann** [comment]
There is an example: https://github.com/DylanVann/react-native-fast-image/blob/32fa98d621462abf1f86051f9fcf6f5f7751eccc/react-native-fast-image-example/src/LocalImagesExample.js#L87
