### ISSUE TITLE
:react-native-fast-image:compileDebugJavaWithJavac

### ISSUE THREAD

**Issue by Wish-ljh** [DylanVann/react-native-fast-image#279]
> Task :react-native-fast-image:compileDebugJavaWithJavac FAILED
/Users/ZY/Documents/project/nicaiapp/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewPackage.java:11: 错误:FastImageViewPackage不是抽象的, 并且未覆盖ReactPackage中的抽象方法createJSModules()
public class FastImageViewPackage implements ReactPackage {
       ^
注: /Users/ZY/Documents/project/nicaiapp/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewManager.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
1 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fast-image:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
82 actionable tasks: 24 executed, 58 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by boscorat** [comment]
I also had this error this morning although the same project had been building correctly a couple of days ago.  Reinstalling the dependencies solved the issue for me:
`rm -r node_modules`
`yarn`
`react-native link`
`react-native run-android`
If you're not using yarn you could replace the `yarn` line with `npm install`.

**Comment by zerbinidamata** [comment]
Hey, i am having this issue and unable to fix it. @boscorat  solution did not worked for me. Are there any other solutions? 
thanks

**Comment by lvfb20** [comment]
none works. unbelievable

**Comment by rodriguezmanu** [comment]
any updates about this?

**Comment by FrankGoortani** [comment]
This might probably be because of Upgrade to AndroidX - I'd avoid that.

**Comment by DylanVann** [comment]
`react-native-fast-image@7.0.0` supports AndroidX without modifications.

**Comment by trinadhkoya** [comment]
@DylanVann  but this is leading  to xcode crash.
