### ISSUE TITLE
Fix View.propTypes deprecation warning.

### ISSUE THREAD

**Issue by gavinanthony** [DylanVann/react-native-fast-image#28]
![image](https://user-images.githubusercontent.com/392797/28784825-2358765c-75da-11e7-8c68-ead901db59ef.png)
Getting a deprecation warning for `View.propTypes`
react: 16.0.0-alpha.6
react-native: 0.44.0 

Looks like it's being caused right here
https://github.com/DylanVann/react-native-fast-image/blob/master/FastImage.js#L90

**Comment by DylanVann** [comment]
DONE!
