### ISSUE TITLE
C++ exception in 'nativeFlushQueueImmediate' Malformed calls from JS: field sizes are different

### ISSUE THREAD

**Issue by samcampisi** [DylanVann/react-native-fast-image#295]
I followed the steps to manually install react-native-fast-image on both iOS and Android.

I added the demo code:
```javascript
<FastImage
    style={styles.image}
    source={{
      uri: 'https://unsplash.it/400/400?image=1',
      headers:{ Authorization: 'someAuthToken' },
      priority: FastImage.priority.normal,
    }}
    resizeMode={FastImage.resizeMode.contain}
  />
```

And the first time it loads the image successfully. 

However, when I try to access the image again, I get this error on both iOS and Android:

![file](https://user-images.githubusercontent.com/42766924/45804557-b2890d80-bcbc-11e8-9672-58475dd76440.jpg)

is there something I'm missing on how to use this library?...
I tried rm -rf node_modules && npm i but it doesn't work.

**Comment by samcampisi** [comment]
I found out it had to do with another library I had installed. When I used it in a normal image without the other library it works.

**Comment by lannablue89** [comment]
@samcampisi I also get this error, what was other library you using?

**Comment by samcampisi** [comment]
@lannablue89 I think it was react-native-snap-carousel
