### ISSUE TITLE
Show image by requie don't active for real device

### ISSUE THREAD

**Issue by manhhoan73** [DylanVann/react-native-fast-image#296]
I use the react-native-fast-image library to display the image on the virtual machine when the image appears normally. The release of the release does not show. Do you have any examples of using this case? sorry my english is not good Thank you so much

**Comment by edo1493** [comment]
I am seeing this on the latest. It seems like on the latest version if you require a local file, it won't show in the app in production. Any idea? @DylanVann

**Comment by pingxiaodou** [comment]
same here

**Comment by namnh240795** [comment]
Track this. its only happen on android.
https://github.com/DylanVann/react-native-fast-image/pull/283

**Comment by edo1493** [comment]
Thanks!

**Comment by manhhoan73** [comment]
> Track this. its only happen on android.
> #283
> For now, i use Image for local resource instead.

Are you Vietnamese?
