### ISSUE TITLE
Image is not being rendered

### ISSUE THREAD

**Issue by andruxnet** [DylanVann/react-native-fast-image#3]
I did the following:

```
yarn add react-native-fast-image
react-native link
```

Then I replaced one of my images from this:

```
                    <Image
                      style={styles.image}
                      source={{uri: imageUri}}
                    />

```
to this:

```
                    <FastImage
                      style={styles.image}
                      source={{
                        uri: imageUri,
                        priority: FastImage.priority.normal,
                      }}
                      resizeMode={FastImage.resizeMode.contain}
                      onLoad={() => console.tron.log('loaded')}
                      onError={() => console.tron.log('error')}
                    />
```

I see the empty space where the image should be displayed, but no image. Am I missing something?

**Comment by DylanVann** [comment]
If you're new to React Native: You need to rebuild the native code when you
run link. Quit the simulator and re-run 'react-native run-ios'.

If not, I'm not sure, I'll take a closer look in a bit.

**Comment by andruxnet** [comment]
I already did that, I stopped the packager and ran yarn start, then react-native run-ios, same problem

**Comment by DylanVann** [comment]
I think it was an issue with the last version published.

Could you try installing the latest version? I just created a demo project, installed and ran it, seems good now.

**Comment by andruxnet** [comment]
That did it!

Thanks a lot for the fast response.

**Comment by DylanVann** [comment]
You're welcome, thanks for finding the issue 😄 .

**Comment by jenilshah93** [comment]
im having the same problem, installed the latest version, problem still doesn't seem to go
