### ISSUE TITLE
iPhone X can not show local image

### ISSUE THREAD

**Issue by guihouchang** [DylanVann/react-native-fast-image#308]
how to fixed it?

**Comment by kientux** [comment]
I don't know why but `FastImage` suddenly can't display any local image on both Android and iOS. For now I have to use React Native `Image` instead.

**Comment by heyman333** [comment]
Yeah. I also have a ploblem  using localImage

**Comment by vlaja** [comment]
Hi there,

I think you might have issue with styling around this. In some cases FastImage was not a drop in replacement for me.

You can check this by trying to add `{ height: '100%', width: '100%' }` inside the style object of the image that isn't showing up.

If it shows after adding max height i width, then think about how you can restyle your image or the image container.

**Comment by DylanVann** [comment]
Not enough info here, local images seem to be working on latest.
