### ISSUE TITLE
Could not find method implementation

### ISSUE THREAD

**Issue by AibiTi** [DylanVann/react-native-fast-image#311]
```js
"react": "16.3.1",
"react-native": "0.55.4",    
"react-native-fast-image": "^5.0.11",
```

![360 164605195910050](https://user-images.githubusercontent.com/40224479/46924586-e572b700-d058-11e8-9259-68dbfd6e3f6c.png)

**How to solve?**

**Comment by DylanVann** [comment]
If you upgrade your version of React Native (including your Gradle version) then `implementation` will work. `implementation` replaces `compile` in newer versions of Gradle. If this change is not made in this library then it eventually will stop working for new versions of React Native.
