### ISSUE TITLE
Error with other library dependencies.

### ISSUE THREAD

**Issue by AibiTi** [DylanVann/react-native-fast-image#312]
![360 16411201463774](https://user-images.githubusercontent.com/40224479/46925585-2a99e780-d05f-11e8-9b2a-5e4286cfa360.png)

**Comment by DylanVann** [comment]
Could be related to the [other issue](https://github.com/DylanVann/react-native-fast-image/issues/311)?

Maybe also related to [Proguard](https://github.com/DylanVann/react-native-fast-image#proguard)?

**Comment by AibiTi** [comment]
This problem may be caused by some inventory being repeatedly dependent on `android.support`. I annotated on the following places and got the correct compilation. ( v5.0.4 -> build.gradle -> line 56 )

![360 1660083094110113](https://user-images.githubusercontent.com/40224479/46929315-88cfc600-d071-11e8-9733-6be2eaae8f2e.png)

**Comment by DylanVann** [comment]
In newer React Native versions you can configure a project wide variable for the support library versions.
