### ISSUE TITLE
conflict between Android and React native when both use glide

### ISSUE THREAD

**Issue by linguokun1** [DylanVann/react-native-fast-image#318]
(Can't read [com] (Can't read [bumptech] (Can't read [glide] (Can't read [GeneratedAppGlideModuleImpl.class] (Duplicate zip entry [com/bumptech/glide/GeneratedAppGlideModuleImpl.class]))))))

**Comment by onlybenyang** [comment]
please read the doc https://github.com/DylanVann/react-native-fast-image/blob/master/docs/app-glide-module.md

**Comment by jeremyclee** [comment]
To be clear on the link above, you need to add
`ext {
    excludeAppGlideModule       = true
}`
to you project root gradle file, not the react-native-fast-image gradle file, and definitely not your app level gradle file

**Comment by linguokun1** [comment]
Thanks all of you , I solve it

**Comment by CrackerKSR** [comment]
> To be clear on the link above, you need to add `ext { excludeAppGlideModule = true }` to your **project root gradle file**, not the react-native-fast-image gradle file, and definitely not your app level gradle file

Thanks
