### ISSUE TITLE
Could you please support placeholder image?

### ISSUE THREAD

**Issue by sinhpn92** [DylanVann/react-native-fast-image#319]
Hi,
This is amazing image lib for my react native app. It's will be more awsome if you support placeholder image from local when loading image from internet by uri. 
Have you plan to implement it?

Thanks

**Comment by hhunaid** [comment]
Yes, specially since Glide and SDWebImage both support them natively.

**Comment by sinhpn92** [comment]
Thank you support @hhunaid.
I have try to set placeholder for default request in GlideModule but It doesn't work.

**Comment by webbin** [comment]
Is there any api new for setting placeholder image before the reomte source has been downloaded?

**Comment by nehacurefit** [comment]
Is there any update for supporting placeholder images. Or if anyone has found something in forked repo , please update here. Need it urgently in efficient way

**Comment by EgidioCaprino** [comment]
Any update on this?

**Comment by EgidioCaprino** [comment]
This PR adds `placeholder` prop https://github.com/DylanVann/react-native-fast-image/pull/409

**Comment by DylanVann** [comment]
Merged!
