### ISSUE TITLE
Add non-aggressive caching.

### ISSUE THREAD

**Issue by bjartebore** [DylanVann/react-native-fast-image#32]
It would be great if we could get the possibility to turn on http caching control (SDWebImageRefreshCached in SDWebImage) to utilise functionality like etags

**Comment by DylanVann** [comment]
etags are evil, use immutable urls.

Joking, I understand you might be constrained as far as how that works. Immutable urls are definitely better if you can make it happen. I can look into this adding this. In order to do it `Glide` would have to provide something equivalent.
