### ISSUE TITLE
enum FastImage.cacheControl wrong Type Definitions

### ISSUE THREAD

**Issue by Aligertor** [DylanVann/react-native-fast-image#325]
Just a minor issue.

The possible values for source.cache can not be used as shown in the README.md when using Type Script.

The possible Values are defined as 
FastImage.cacheControl
in ./src/index.js

but the Types are defined as 
FastImage.cache
in ./src/index.d.ts

**Comment by kicsigabszi** [comment]
same bug in version 8.1.5. Available values for source.cache: 'low' | 'normal' | 'high'

**Comment by moreiraj2** [comment]
The issue still persist in version 8.1.5!
