### ISSUE TITLE
how to support webp image ? 

### ISSUE THREAD

**Issue by XHTeng** [DylanVann/react-native-fast-image#326]
I found that contains libwebp directory , but still can't display webp image , how to solute it ?

![image](https://user-images.githubusercontent.com/17663111/47492857-8bf06080-d880-11e8-942f-c079fe40ad9f.png)

**Comment by XHTeng** [comment]
> i use podfile and add to podfile :
> 
> ```
> pod 'SDWebImage/WebP'
> ```
> It working for me.
I did that , and run `pod install` , but I got this error , 
![image](https://user-images.githubusercontent.com/17663111/47506313-5eb4aa00-d8a2-11e8-89c2-f3f282c75121.png)
fastimage SDWebImage duplicate with pod SDWebImage .

![image](https://user-images.githubusercontent.com/17663111/47506620-0af69080-d8a3-11e8-9c54-e2756779c9da.png)

**Comment by shemdani** [comment]
Check your Xcode version. What version are you on?

**Comment by bbturtle** [comment]
@XHTeng 

Remove lib add in libraies on xcode, below image:

<img width="263" alt="screenshot at oct 26 08-06-55" src="https://user-images.githubusercontent.com/42196041/47538555-38205e80-d8f6-11e8-9cab-1c767fc441a3.png">

**Comment by XHTeng** [comment]
> @XHTeng
> 
> Remove lib FastImage.xcodeproj in libraries on xcode, below image:
> 
> <img alt="screenshot at oct 26 08-06-55" width="263" src="https://user-images.githubusercontent.com/42196041/47538555-38205e80-d8f6-11e8-9cab-1c767fc441a3.png">

it works , thx !

**Comment by evanbinyang** [comment]
Can you use FastImage component after removing FastImage.xcodeproj? @XHTeng

**Comment by ds8k** [comment]
@bbturtle @XHTeng I'm with @evanbinyang, wouldn't that mean you'd no longer be able to use the FastImage component?

**Comment by bbturtle** [comment]
> @bbturtle @XHTeng I'm with @evanbinyang, wouldn't that mean you'd no longer be able to use the FastImage component?

I using podfile in iOS, not link FastImage.xcodeproj and link manual in Android
![image](https://user-images.githubusercontent.com/42196041/50619948-2a5b0b00-0f2f-11e9-87dd-118f1746267c.png)
