### ISSUE TITLE
Will calling preload twice force the image to be fetched again?

### ISSUE THREAD

**Issue by baba43** [DylanVann/react-native-fast-image#33]
Simple question that came to my mind because I would like to know if I have to care about storing the information that an image has already been fetched before.

Might be added to the readme as well.

Thank you!

**Comment by DylanVann** [comment]
Not that simple actually, it's down to the native libraries and how they implement the methods this calls. Looking at the source of `SDWebImage` and `Glide`, I don't think the image will be loaded twice, it will just hit the cache the second time. If you want to be 100% sure you could continually preload the same url and take a look at the network monitor.

I tested on iOS and I don't see any redownloading.
