### ISSUE TITLE
Android Release apk images not showing

### ISSUE THREAD

**Issue by yeomann** [DylanVann/react-native-fast-image#330]
Hello,

i was using `"^4.0.14"` untill i upgraded to `"^5.0.11"` I see that after make a release app for both IOS and Android. Only android one is failing to show the images. I'm very much baffled as Android is showing images very fine when i'm on development. But when i made a release apk to test on my device. it doesn't show any image. while on IOS everything is fine. I am completely lost. If i didn't do the linking correct then why would it be working on IOS and android (development ONLY).

Although the library was working in release and development before upgrading. Ironically `react-native-maps` also not showing map in release mode now!
I'm having such a hard time from couple of days because of these issues.
Can you please tell me what should i try? i have tested on my real Device which has API 23 and its Samsung J7 Prime.

**Comment by bbturtle** [comment]
see this : #324

**Comment by bbturtle** [comment]
> okay seems that i'm not alone @bbturtle but it seems merged i don't know if the fix is released on npm or not

please update to v5.1.0, it's worked for me

**Comment by yeomann** [comment]
if that so then let me close this issue. for now my Gradle release build is seems to be f** at the moment because firebase + maps + appcenter.
