### ISSUE TITLE
indicator ProgressCircle 

### ISSUE THREAD

**Issue by AlmogRnD** [DylanVann/react-native-fast-image#35]
I'm using the following package for a preloader https://github.com/oblador/react-native-image-progress 

Which is great and works perfect with react image, I wanted to know if FastImage can add this support it would be great to have a preloader option

**Comment by DylanVann** [comment]
I'm trying to keep this as a low level library for now. In the future I might add that support to this package, but for now it's available separately as described here: https://github.com/DylanVann/react-native-fast-image/issues/9#issuecomment-320849198
