### ISSUE TITLE
Animated WebP display issues (With "Fix")

### ISSUE THREAD

**Issue by Sejadis** [DylanVann/react-native-fast-image#385]
Currently there is a problem with displaying animated webp without transparency on iOS12 devices.
This problem was fixed in SDWebImage v4.4.1
Just from skipping through the SDWebImage changelogs there doesnt appear to be breaking changes on first sight so it would be nice if the version could be updated

**Comment by ds8k** [comment]
I'm also in need of this fix. I've tried forking the repo and updating the submodule commit but I'm having a hell of a time testing out that it actually works. Whenever I install from my directory the submodule never initializes. @DylanVann I can put in a PR that updates the commit if it'll help out

**Comment by DylanVann** [comment]
Fixed in the latest release. Thanks @ds8k !
