### ISSUE TITLE
Compilation error: FastImageViewPackage is not abstract and does not override abstract method createJSModules()

### ISSUE THREAD

**Issue by clay-morgan** [DylanVann/react-native-fast-image#39]
Receive this error upon trying to package.

Seems removeJSModules override was removed in the last commit

**Comment by clay-morgan** [comment]
Well upgrading to RN 47 seems to work

**Comment by mehdijjz** [comment]
@clay-morgan I don't want to upgrade to RN 47 and am stocked with 46. what do I do ?!

**Comment by skizzo** [comment]
@clay-morgan For [RN versions < 0.47.0](https://github.com/DylanVann/react-native-fast-image/releases/tag/v1.0.0), explicitly use [react-native-fast-image **v0.0.11**](https://github.com/DylanVann/react-native-fast-image/tree/v0.0.11) by either 

a) installing with `npm install --save react-native-fast-image@0.0.11`or 

b) specifying the version in your package.json (`"react-native-fast-image": "0.0.11",`) and running `npm install`.

Then, link with `react-native link react-native-fast-image` and you should be good to go. Just worked for me (using RN 0.44.1).
