### ISSUE TITLE
Preloading local images used via require() fails

### ISSUE THREAD

**Issue by IljaDaderko** [DylanVann/react-native-fast-image#395]
Sometimes with even local images take a short while to load, particularly if there are many images composing full ui i.e. games.

I thought using `.preload` method on my local images could elevate some bottlenecks, but following errors

```js
export default function preloadImages() {
  FastImage.preload([
    require('../assets/images/dwarf.webp')
])
```

Whenever I call `preloadImages` I receive following error

> Exception '-[__NSCFNumber objectForKeyedSubscript:]: unrecognized selector sent to instance 0xf4263c55c59de1d2' was thrown while invoking preload on target FastImageView with params (
>         (
>         1
>    )
> )

I assume this number `1` relates to me using require. Should this be supported as part of preload or is this issue irrelevant?

**Comment by IljaDaderko** [comment]
I found a small hack-around this by doing following, not sure how I feel about it yet, but we can get `uri` from `require` by using react-native's `Image.resolveAssetSource`

```js
import { Image } from 'react-native';
import FastImage from 'react-native-fast-image';

export function preloadImages() {
  const images = [
    require('../assets/images/graphic1.webp'),
    require('../assets/images/graphic2.jpg'),
    require('../assets/images/graphic3.webp')
  ];

  const uris = images.map(image => ({
    uri: Image.resolveAssetSource(image).uri
  }));

  FastImage.preload(uris);
}

```

**Comment by IljaDaderko** [comment]
Solution above works very well for me, only wishing for a callback on `preload` to know when images have loaded

**Comment by cjroth** [comment]
Worked for me too! Thanks :)

**Comment by EhsanSarshar** [comment]
as of @IljaDaderko awesome solution I made this simple utility function

```javascript
import FastImage from 'react-native-fast-image'
import { Image } from 'react-native'

export function preloadImages(links = []) {

    const uris = links.map(link => ({
        uri: Image.resolveAssetSource(require(link)).uri
    }));

    if (uris.length)
        FastImage.preload(uris);
}
```

**Comment by ibnubtpn** [comment]
Hi @IljaDaderko , did your solution work on Android as well? because I still can see the loading flicker when the first time the local image loaded in the component. I've also added the priority to `high` when `FastImage.preload`

**Comment by IljaDaderko** [comment]
@ibnubtpn This was a long time ago, I believe I only tested on iOS, so not sure about Android.

**Comment by pastean** [comment]
doesn't seem to work for android; did anyone find a solution?

**Comment by gpbaculio** [comment]
Works for android for me, solution of @IljaDaderko

**Comment by f4z3k4s** [comment]
@pastean FYI: `Image.resolveAssetSource` is not a production ready implementation, it does not work in Android Release mode. I've learned it the hard way, not with images, but with 3d models. See [this thread](https://github.com/facebook/react-native/issues/24963) for more info.

However, you can achieve the same with `expo-asset` and that works in every environment, the following snippet looks like this:

```ts
import { Asset } from 'expo-asset';
import FastImage from 'react-native-fast-image';

const loadImage = async (filePath: string) => {
  const [{ localUri }] = await Asset.loadAsync(filePath);
  return localUri as string;
};

const preloadImages = async () => {
  const sources = await Promise.all(
    [require('../path/to/image-a'), require('../path/to/image-b')].map(async (uri) => ({
      uri: await loadImage(uri)
    }))
  );
  FastImage.preload(sources);
};
```

**Comment by Stevemoretz** [comment]
> @pastean FYI: `Image.resolveAssetSource` is not a production ready implementation, it does not work in Android Release mode. I've learned it the hard way, not with images, but with 3d models. See [this thread](https://github.com/facebook/react-native/issues/24963) for more info.
> 
> However, you can achieve the same with `expo-asset` and that works in every environment, the following snippet looks like this:
> 
> ```ts
> import { Asset } from 'expo-asset';
> import FastImage from 'react-native-fast-image';
> 
> const loadImage = async (filePath: string) => {
>   const [{ localUri }] = await Asset.loadAsync(filePath);
>   return localUri as string;
> };
> 
> const preloadImages = async () => {
>   const sources = await Promise.all(
>     [require('../path/to/image-a'), require('../path/to/image-b')].map(async (uri) => ({
>       uri: await loadImage(uri)
>     }))
>   );
>   FastImage.preload(sources);
> };
> ```

Thanks for sharing.

**Comment by f4z3k4s** [comment]
@Stevemoretz welcome mate, enough time was wasted on that. :)

**Comment by alexander01202** [comment]
Please add support for expo. Native plugins can now be used
