### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by wholcman** [DylanVann/react-native-fast-image#4]
Actually, gifs don't work

**Comment by DylanVann** [comment]
I think they should work on iOS. On android it would involve adding another dependency. Might be worth it for platform parity and ease of use.

**Comment by DylanVann** [comment]
Actually it doesn't work on iOS. Looks like it's something to do with linking FLAnimatedImage.

**Comment by andruxnet** [comment]
GIFs would be a nice enhancement! Right now they do load but as if they were JPEG

**Comment by DylanVann** [comment]
Included in the latest version.

![gif_support](https://cloud.githubusercontent.com/assets/1537615/25693356/c42a683c-3076-11e7-835f-0127b196277f.gif)

**Comment by wholcman** [comment]
Don't forget to import FLAnimatedImageView correctly.
Actually, FLAnimatedImageView.h is not found.

**Comment by DylanVann** [comment]
Try cleaning your project:

```bash
rm -rf ios/build
react-native run-ios
```

**Comment by enahum** [comment]
@DylanVann have you thought of adding stop/start/isAnimated for GIF's ? It should be supported by FLAnimatedImage and If I'm correct also for Glide on Android.

thoughts?

**Comment by SeniorSam7** [comment]
the gif is working as a source, but not as a defaultSource
