### ISSUE TITLE
Caching issue I can't understand

### ISSUE THREAD

**Issue by obsidianart** [DylanVann/react-native-fast-image#402]
Images are load as follow 
```
const Images = {
  level1: require('../Images/Levels/1.png'),
  level2: require('../Images/Levels/2.png'),
  level3: require('../Images/Levels/3.png'),
....
```

and they are used as follow
```
<FastImage
                  style={{flex: 1, height: undefined, width: undefined}}
                  source={Images[`level${id}`]}
                  resizeMode={FastImage.resizeMode.contain}
                />
```

Everything is fine till the moment I added some images. From that moment (on Android, not sure about IOs) after I released on the store all images got mixed.
Uninstalling and installing the app fix the problem, meaning it's a caching issue. I checked a second device to be sure and the issue was the same, I tried switching to
```
<FastImage
                  style={{flex: 1, height: undefined, width: undefined}}
                  source={{
                    uri: Image.resolveAssetSource(Images[`level${id}`]).uri
                  }}
                  resizeMode={FastImage.resizeMode.contain}
                />
```
but it didn't fix it.
I don't know if it's a bug or I'm doing something wrong, and I know it's hard to reproduce. If you have any idea of what I can try I can give it a go

**Comment by thoth-ibl** [comment]
`<FastImage
                  style={{flex: 1, height: undefined, width: undefined}}
                  source={{
                    uri: Image.resolveAssetSource(Images[`level${id}`]).uri, cache: 'web'
                  }}
                  resizeMode={FastImage.resizeMode.contain}
                />`
You can try. @obsidianart

**Comment by obsidianart** [comment]
@thoth-ibl thank you. I can't easily replicate the issue so I don't know when/if I'm going to be able to try.

**Comment by alxplusplus** [comment]
We have the same problem. It seems only Happen after an update of the app version in android. I will try to dig and recreate with more info.

**Comment by thoth-ibl** [comment]
_My solution for react-native-fast-image version 5.1.2: 
 + load local image: I use Image component of react-native
 + load remote image: I use react-native-fast-image library.

**Comment by patrickkempff** [comment]
@obsidianart I did some research on this issue. It looks like this has something to do with the Glide cache when handling local images.
