### ISSUE TITLE
incompatible types: okhttp3.Interceptor cannot be converted to expolib_v1.okhttp3.Interceptor

### ISSUE THREAD

**Issue by SenhorBardell** [DylanVann/react-native-fast-image#404]
The problem with detached expo app, that has breaking changes for okhttp3 package.

Proposed solution of switching import for exploib_v1.okhttp3 renders a problem `OkHttpClient` cannot be converted to a factory. Thus preventing any detached expo app to use this package.

**Comment by SDxBacon** [comment]
@raul-madrigal has made a comment to fix this issue couple days ago, here is the link:https://github.com/DylanVann/react-native-fast-image/issues/249#issuecomment-463310273

I've tried it with detached project on expo version 32, and it does works :)

**Comment by markygab** [comment]
Sorry for being a dunce.... How do I use @raul-madrigel GIST to checkout this fix? @SDxBacon did you create a Fork and apply his changes?

**Comment by SenhorBardell** [comment]
@markygab `git apply changes.diff`

**Comment by DylanVann** [comment]
Closing Expo issues until Expo updates to React Native 0.60.0.
