### ISSUE TITLE
Crash on Android if source is an invalid URL

### ISSUE THREAD

**Issue by raynor85** [DylanVann/react-native-fast-image#407]
If I pass as `source` an object like this `{ uri: 'INVALID_URL' }` I get the following error on Android:
```
Error while updating property 'source' of a view managed by: FastImageView

null

Must not be null or empty
```
At the moment I am normalising the source using this (ugly) code to avoid the crash:
```ts
const normalisedSource = source && typeof source.uri === 'string' && !source.uri.split('https://')[1] ? null : source;
```
but I think it would be better if the library prevents it.

**Comment by OrangeFlavoredColdCoffee** [comment]
not all image start https,   http ??
const normalisedSource = source && typeof source.uri === 'string' && !source.uri.split('http')[1] ? null : source;

**Comment by MrLaibin** [comment]
this is log.
```
2019-03-28 19:29:08.185 14848-14848/E/fastimage: http://img.abc.com/o_1d6v24em310p7pib14b94gsjbha.jpg
2019-03-28 19:29:08.185 14848-14848/ E/fastimage: false
2019-03-28 19:29:08.195 14848-14848/ E/fastimage: true
2019-03-28 19:29:08.196 14848-14848/E/unknown:ViewManager: Error while updating prop source
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
```

**Comment by Thrajnor** [comment]
@OrangeFlavoredColdCoffee Your answer works perfectly. Thank you very much! you saved me so much time ^^

**Comment by KamyabHusain** [comment]
Getting exact same problem 
@OrangeFlavoredColdCoffee but what about if broken image from server

**Comment by tianliuj** [comment]
so I need adjust every source ? It's so Unfriendly！！！

**Comment by rodionovich221** [comment]
> const normalisedSource = source && typeof source.uri === 'string' && !source.uri.split('http')[1] ? null : source;

You saved my day!

**Comment by osrl** [comment]
> not all image start https, http ??
> const normalisedSource = source && typeof source.uri === 'string' && !source.uri.split('http')[1] ? null : source;
 not all images start with https or http. what about local images

**Comment by alexdieudonne** [comment]
how i could use this function or variable ?

**Comment by alexdieudonne** [comment]
> > not all image start https, http ??
> > const normalisedSource = source && typeof source.uri === 'string' && !source.uri.split('http')[1] ? null : source;
> 
> not all images start with https or http. what about local images

i don't know where

**Comment by raynor85** [comment]
You don’t have to use it necessarily, but it prevents malformed url to
crash on Android devices. If you want to use it, just wrap your fast image
with your own custom component wrapper and apply the function to fast image
data source prop

**Comment by codebetterme** [comment]
render() {
    return (
        <FastImage source={{uri: this.getUriImage(_uri)}}/>
    )
}

function getUriImage(uri) {
    return uri !== null && uri !== undefined && uri.includes("/") && uri.includes(".") ? uri : ""
}

**Comment by leogildo10** [comment]
> not all image start https, http ??

where do i have do make this change?

**Comment by cdw1p** [comment]
> render() {
> return (
> <FastImage source={{uri: this.getUriImage(_uri)}}/>
> )
> }
> 
> function getUriImage(uri) {
> return uri !== null && uri !== undefined && uri.includes("/") && uri.includes(".") ? uri : ""
> }

Thanks you, my problem is solved using this

**Comment by thanhdevapp** [comment]
Handler local image

class ProgressiveImage extends React.Component {

    getUriImage(uri) {
        return uri !== null && uri !== undefined && uri.includes("/") && uri.includes(".") ? uri : ""
    }

    render() {
        let source = this.props.source;
        return (
            <View style={styles.container}>
                {this.props.source && this.props.source.uri ? <FastImage {...this.props} source={{
                    uri: this.getUriImage(this.props.source.uri),
                    cache: FastImage.cacheControl.immutable,
                }} /> : <Image {...this.props} />}
            </View>
        )
    }
}

**Comment by z3r0c00l-2k** [comment]
I think the library itself should take of this issue, on ios it works perfectly.
