### ISSUE TITLE
Android Build Error RN Fast Image 5.2.0 - React Native 0.59.1

### ISSUE THREAD

**Issue by smeekmeister** [DylanVann/react-native-fast-image#435]
Task :react-native-fast-image:compileReleaseJavaWithJavac FAILED
Gradle may disable incremental compilation as the following annotation processors are not incremental: compiler-4.7.1.jar (com.github.bumptech.glide:compiler:4.7.1).
Consider setting the experimental feature flag android.enableSeparateAnnotationProcessing=true in the gradle.properties file to run annotation processing in a separate task and make compilation incremental.
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
Note: [2] Wrote GeneratedAppGlideModule with: [com.bumptech.glide.integration.okhttp3.OkHttpLibraryGlideModule, com.dylanvann.fastimage.FastImageOkHttpProgressGlideModule]
/Users/smekens/Github/js-in-the-loop-mobile/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewConverter.java:23: error: package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ImageSource;
                                           ^
/Users/smekens/Github/js-in-the-loop-mobile/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:10: error: package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ImageSource;
                                           ^
/Users/smekens/Github/js-in-the-loop-mobile/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageSource.java:14: error: cannot find symbol
public class FastImageSource extends ImageSource {
                                     ^
  symbol: class ImageSource
/Users/smekens/Github/js-in-the-loop-mobile/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewModule.java:12: error: package com.facebook.react.views.imagehelper does not exist
import com.facebook.react.views.imagehelper.ImageSource;
                                           ^
4 errors

**Comment by iksent** [comment]
Same error

**Comment by guhungry** [comment]
@iksent @smeekmeister Can I see your app/build.gradle? Have you try to clean project and rebuild?

Iuse fast image 5.2.0 with 5.59.0, 0.59.1 and 0.59.2 with no problem both ci and all my pcs.

**Comment by zi6xuan** [comment]
```
repositories {
    mavenCentral()
    maven {
        url "https://maven.google.com"
    }
}
```
I wonder if missed the code to access the local react-native，about this   @DylanVann 
```
    maven {
        // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
        url "$projectDir/../../../node_modules/react-native/android"
    }
```

**Comment by kbrandwijk** [comment]
Just added 5.2.0 for the first time to my RN 0.59.2 project. No build issues on Android (both in debug and release with the proguard rules).

My advice would be to check your target SDK version.

**Comment by nic-thomson** [comment]
Rebuiling my app with ReactNative 0.59 , I too ended up with this problem .  None of the above fixes worked  for me.  This Commit did fix it 
https://github.com/DylanVann/react-native-fast-image/pull/439/commits/2276c719c2dbbe48c44bbaf415d42bc72f37e71e

**Comment by kbrandwijk** [comment]
I believe that change was part of the upgrade process, according to rn-diff-purge...

**Comment by origamih** [comment]
My fix is to download `https://github.com/DylanVann/react-native-fast-image`, then put the `android/` to `node_modules/react-native-fast-image/`, overwrite everything

**Comment by DylanVann** [comment]
Since this is an issue with React Native < 0.60.0 I'm closing. Sorry I can't help. If you still have the issue with the latest React Native version and latest `react-native-fast-image` version please open a new issue. Thank you!

**Comment by zi6xuan** [comment]
`fastimage:7.0.0+` must be use the `react-native:0.60.0+`,Update the description text is better
