### ISSUE TITLE
Add support for CocoaPods and Gradle.

### ISSUE THREAD

**Issue by ruoyuruoshui** [DylanVann/react-native-fast-image#44]

**Comment by DylanVann** [comment]
Why would you prefer to use CocoaPods and Gradle?

**Comment by anonrig** [comment]
I would also like to use this plugin, but since there isn't any cocoapods support, I couldn't use it. Since, libraries like react-native-maps are enforcing the use of cocoapods, we merged all of our 3rd party libraries to cocoapods. @DylanVann is it possible to add this enchancement?

**Comment by patrickkempff** [comment]
@anonrig 
I submitted PR #143 which adds cocoapods support.

**Comment by DylanVann** [comment]
I'm pretty sure you are actually able to use cocoapods and non-cocoapods dependencies. You just have to do the linking steps manually. They're not included in the readme, but they're pretty much the same for every native library.

This library does support using gradle.
CocoaPods support is in the latest release.
