### ISSUE TITLE
Trying to use FastImage produces an Invariant violation on iOS after installing with CocoaPods

### ISSUE THREAD

**Issue by nadav2051** [DylanVann/react-native-fast-image#443]
Error:
"Invariant Violation: Element type is invalid: expected a string( for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in"

My use is as follows:
```
import FastImage from 'react-native-fast-image';
...
        return <FastImage
            source={{ uri: 'http://website.com/image.gif' }}
        />;
...
```

Using version: 5.2.0, React Native version: 0.51

If that helps, console.log of FastImage produces this:
`{ '$$typeof': {},
  render: [Function],
  displayName: 'FastImage',
  resizeMode: 
   { contain: 'contain',
     cover: 'cover',
     stretch: 'stretch',
     center: 'center' },
  priority: { low: 'low', normal: 'normal', high: 'high' },
  cacheControl: { immutable: 'immutable', web: 'web', cacheOnly: 'cacheOnly' },
  preload: [Function],
  defaultProps: { resizeMode: 'cover' },
  propTypes: 
   { accessible: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     accessibilityLabel: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     accessibilityComponentType: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     accessibilityLiveRegion: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     importantForAccessibility: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     accessibilityTraits: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     accessibilityViewIsModal: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onAccessibilityTap: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onMagicTap: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     testID: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     nativeID: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onResponderGrant: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onResponderMove: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onResponderReject: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onResponderRelease: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onResponderTerminate: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onResponderTerminationRequest: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onStartShouldSetResponder: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onStartShouldSetResponderCapture: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onMoveShouldSetResponder: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onMoveShouldSetResponderCapture: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     hitSlop: { [Function: chainedCheckType] isRequired: [Function: bound checkType] },
     onLayout: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     pointerEvents: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     style: [Function],
     removeClippedSubviews: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     renderToHardwareTextureAndroid: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     shouldRasterizeIOS: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     collapsable: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     needsOffscreenAlphaCompositing: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     source: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onLoadStart: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onProgress: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onLoad: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onError: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     onLoadEnd: { [Function: bound checkType] isRequired: [Function: bound checkType] },
     fallback: { [Function: bound checkType] isRequired: [Function: bound checkType] } } }`

Which indeed looks like an object

Edit - Downgrading to 4.0.14 fixed it.

**Comment by StevenMasini** [comment]
@nadav2051 Have you tried to update your React Native ?

`react-native-fast-image` is meant to be compatible with the latest version of React Native.
RN `0.51` is a lot behind the scope of the latest release `0.59`.

I would have suggest you to try updating your version of RN. A lot has changed since `0.51`, you would benefit from those change I think.
