### ISSUE TITLE
SDWebImage update to 5.x

### ISSUE THREAD

**Issue by ivanmoskalev** [DylanVann/react-native-fast-image#447]
Hi! Is there any particular reason to stay on the 4.x version of `SDWebImage` backend? If not, I can perform the update to 5.x. I'd very much like to use `react-native-fast-image` in an app that is being incrementally rewritten using `react-native` – and this app is already using `SDWebImage` 5.0.

**Comment by dreampiggy** [comment]
@ivanmoskalev I create a PR for this. Please help me to contact the maintainer of react native fast image, so that PR can be merged soon.

See: #454

**Comment by ivanmoskalev** [comment]
@DylanVann We need you here.

**Comment by ivanmoskalev** [comment]
@DylanVann Hi! 

If you need help with managing incoming issues, I could help out with that. 24 PRs + 128 issues is a lot, I can understand that. That said, silently disregarding other people's work (like @dreampiggy's #454) seems not the way to go.

If you feel that the #454 is somehow below par, or that #447 is proposing something that you don't like, just give feedback. If you don't have time to review and test, just give feedback. If you like to see it merged, but don't have time, just give feedback. Either way, please give us at least something so we could plan further actions on our own projects that depend on `react-native-fast-image`.
