### ISSUE TITLE
Fix dependency versions for pods

### ISSUE THREAD

**Issue by Ricowere** [DylanVann/react-native-fast-image#456]
https://github.com/DylanVann/react-native-fast-image/blob/2a3438c0d0b81c81116d2e73ad7cf871da0662dd/react-native-fast-image.podspec#L23-L25

Guys I'd say is insanely unsafe to not fix a version for the pod dependencies. With the new SDWebImage update you will need to update this dependency declaration because they removed those subspecs.

I propose;

- You strictly force the dependency version `pod 'SDWebImage/GIF', '4.4.6'` for instance.
- You weakly force the dependency version `pod 'SDWebImage/GIF', '~> 4'` OR `pod 'SDWebImage/GIF', '~> 4.4'` for instance.
- If you don't want to force dependency versions, I'm afraid you will need to update the package.

Hope it helps!

**Comment by DylanVann** [comment]
Some people just like to live on the edge.

Nah I agree, you're right they should be specified.
