### ISSUE TITLE
react-native-fast-image Fails! 

### ISSUE THREAD

**Issue by BINAIMENG** [DylanVann/react-native-fast-image#460]
![image](https://user-images.githubusercontent.com/19889708/56880617-12843580-6a90-11e9-8448-a06c2fb212a5.png)
![image](https://user-images.githubusercontent.com/19889708/56880688-4d866900-6a90-11e9-8c1a-da8d464bacac.png)

and this is my version:
 "react": "16.6.0",
 "react-native": "0.57.1",
 "react-native-fast-image": "^5.3.0",

**Comment by patrickkempff** [comment]
@BINAIMENG are you sure this issue is related to react-native-fast-image? Looking at the error I looks like something goes wrong in an other part of your application.

**Comment by chakrihacker** [comment]
I am getting this error too

**Comment by Desintegrator** [comment]
+

**Comment by Desintegrator** [comment]
> @BINAIMENG are you sure this issue is related to react-native-fast-image? Looking at the error I looks like something goes wrong in an other part of your application.

Yep, if i delete <FasctImage> component, all works properly

**Comment by Desintegrator** [comment]
@BINAIMENG did u fix it?

**Comment by chakrihacker** [comment]
Hi, please check the react version and fast image version, I think this error comes when those are mismatch

**Comment by lfrdreamman** [comment]
@BINAIMENG did u fix it?

**Comment by BINAIMENG** [comment]
> @BINAIMENG did u fix it?

yes i fix this error . It's a react version error.

**Comment by lfrdreamman** [comment]
@BINAIMENG 用的什么版本的react啊
