### ISSUE TITLE
Invariant Violation: Element Type is invalid - ForwardRef /TypeScript

### ISSUE THREAD

**Issue by evanjmg** [DylanVann/react-native-fast-image#467]
Everything was working for 5.2.0 then I upgraded to 5.4.2 and I get:
Invariant Violation: Element Type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. 
Check render method of ForwardRef.
Versions: React Native 0.57.1, React 16.8.3, Typescript 2.8.4, @types/react:16.8.3
This breaks TypeScript compilation and is not just a type error but a build error, so metro can't build it

**Comment by evanjmg** [comment]
Perhaps this is an issue with the typescript babel transformer? However, I can't find any other similar issues on this

**Comment by evanjmg** [comment]
Update: issue still persists for latest React 16.8.6 and types

**Comment by evanjmg** [comment]
Not using the React.memo resolves this issue. I've made a fork for my own use. This is only a workaround. React.memo seems important for a component like this. Will continue to try to resolve the type differences

**Comment by DylanVann** [comment]
I just created a React Native project using TypeScript and installed and used RNFI without any issues.

Did you use [these instructions](https://facebook.github.io/react-native/blog/2018/05/07/using-typescript-with-react-native)?

What version of React and React Native are you using (try updating)? May also be related to `@types/react` and or `@types/react-native`, you could try updating them as well.

**Comment by evanjmg** [comment]
Yeah I have the standard setup - @types/react-native-0.57.51 types and @0.57.1 react-native and use react-native-typescript-transformer

**Comment by DylanVann** [comment]
The newer setup for React Native with TypeScript uses Babel, so this may be why it worked for me.

**Comment by DylanVann** [comment]
Will need more info, maybe with reproduction steps.
