### ISSUE TITLE
Black images for proguard enabled release in Android

### ISSUE THREAD

**Issue by aliustaoglu** [DylanVann/react-native-fast-image#471]
I was working with this component without a problem until I enabled proguard. I've edited proguard-rules.pro as suggested in readme. But all the fast images turned to completely black. 

**To Reproduce**

1. in build.gradle file set below variables
```
enableSeparateBuildPerCPUArchitecture = true
enableProguardInReleaseBuilds = true
shrinkResources = true 
universalApk = true
```
2. Edit proguard-rules.pro file as below:
```
-keep public class com.dylanvann.fastimage.* {*;}
-keep public class com.dylanvann.fastimage.** {*;}
-keep public class * implements com.bumptech.glide.module.GlideModule
-keep public class * extends com.bumptech.glide.module.AppGlideModule
-keep public enum com.bumptech.glide.load.ImageHeaderParser$** {
  **[] $VALUES;
  public *;
}
```
3. Generate a signed apk. It will create several apks. Upload app-universal-release.apk to either physical device or an emulator
4. See that all the images turned to black

**Expected behavior**
Images should appear as normal

**Screenshots**
<table>
<tr><th>Proguard Enabled</th><th>Proguard Disabled</th></tr>
<tr><td><img width="273" alt="proguard-enabled" src="https://user-images.githubusercontent.com/15793376/57577962-c47f2100-74d6-11e9-8961-d73fd7942a82.png"></td><td><img width="269" alt="proguard-disabled" src="https://user-images.githubusercontent.com/15793376/57577966-d2cd3d00-74d6-11e9-96b7-5155f9c00ec1.png"></td></tr>
</table>

**Dependency versions**

All versions are the latest (of today).

- React Native version: 0.59.8
- React version: 16.8.6
- React Native Fast Image version: 6.0.0

**Comment by aliustaoglu** [comment]
This was something to do with Glide library. If you don't use shrinkResources, it works fine.

```
shrinkResources = false
```

**Comment by mitsinsar** [comment]
Hi, I've trying to solve the issue without using `shrinkResources false`. If someone is looking for the answer; [here it is](https://stackoverflow.com/a/64281013/10039864).
