### ISSUE TITLE
WebP with 6.0.0

### ISSUE THREAD

**Issue by pontusab** [DylanVann/react-native-fast-image#476]
- React Native version: `v0.59.8`
- React version: `16.8.6`
- React Native Fast Image version: `6.0.0`

In the latest release using cocapods and WebP the images are not displayed at all. Downgrading to `5.4.2` works just fine. 

I guess there is something with `SDWebImage` that needs to be patched?

**Comment by guhungry** [comment]
Please refer to https://github.com/DylanVann/react-native-fast-image/pull/454#discussion_r277512690

**Comment by pontusab** [comment]
Yes, tried that. Did not work, did it work for you then @guhungry ?

**Comment by guhungry** [comment]
Nope, I didn't use webp in my app.

**Comment by Ilphrin** [comment]
Seems like `SDWebImage` have its support disabled by default (See https://stackoverflow.com/questions/18012527/how-to-load-a-webp-image-with-sdwebimage ) Maybe you can try something like one of the answers @pontusab ?

**Comment by dreampiggy** [comment]
@pontusab See [SDWebImageWebPCoder](https://github.com/SDWebImage/SDWebImageWebPCoder) Readme.

For 5.0, all the external image format coders, are standalone modules (Pods). If you want to use WebP, you can add the Pods and register it in `AppDelegate.m`.


```
pod 'react-native-fast-image'
pod 'SDWebImageWebPCoder'
```

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // ...
    // Register WebP format support
    [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];
    // ...
}
```

**Comment by pontusab** [comment]
Thanks, I got it to work 🥇

**Comment by pontusab** [comment]
Import in `AppDelegate.m`:
```
#import "SDImageCodersManager.h"
#import <SDWebImageWebPCoder/SDImageWebPCoder.h>

```

An add:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // ...
    // Register WebP format support
    [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];
    // ...
}
```

**Comment by aibrahim3546** [comment]
@pontusab What is the step you do to get it works?

I did like this

- add `pod 'SDWebImageWebPCoder'`
- run `pod install`

and then in `AppDelegate.m`

```
#import "SDImageCodersManager.h"
#import <SDWebImageWebPCoder/SDImageWebPCoder.h>

// .....

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    // ...
    // Register WebP format support
    [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];
    // ...
}

//....
```

I cannot build the App. It failed.

**Comment by dancomanlive** [comment]
@aibrahim3546 What is the error msg? Try pod deintegrate before pod install maybe. The solution above worked for me just fine.

**Comment by fondoger** [comment]
Thanks, it works perfectly for me!

**Comment by vinceprofeta** [comment]
For react native `v0.60` - make sure to run `pod update`

**Comment by srajesh636** [comment]
> Import in `AppDelegate.m`:
> 
> ```
> #import "SDImageCodersManager.h"
> #import <SDWebImageWebPCoder/SDImageWebPCoder.h>
> ```
> 
> An add:
> 
> ```
> - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
> {
>     // ...
>     // Register WebP format support
>     [SDImageCodersManager.sharedManager addCoder:SDImageWebPCoder.sharedCoder];
>     // ...
> }
> ```

Thanks, it Worked like charm
