### ISSUE TITLE
Scrolling through images list on iOS is very laggy

### ISSUE THREAD

**Issue by ramon90** [DylanVann/react-native-fast-image#477]
**Describe the bug**
When scrolling through an images flatlist on ios (which is not very long, about 30 images), scrolling becomes laggy and the scrolling position keeps flickering while scrolling. It works fine on Android. Also, it works fine on iOS using normal Image from react-native, but I want to use react-native-fast-image for its extra features.

**To Reproduce**
1. Render a list of 30-50 images on ios using react-native-fast-image
2. Scroll through the list.
3. You will notice what is mentioned above.

**Expected behavior**
The scroll to be smooth

- React Native version: 0.59.3
- React version: 16.8.3
- React Native Fast Image version: 5.3.0

**Comment by greyexpert** [comment]
I've also noticed this performance issue, but it was because of large images in the list. I fixed it by using smaller variants ( thumbnails ). After the fix - no scroll lags at all.

**Comment by ramon90** [comment]
I cannot use smaller images, the image needs to be displayed as it is

**Comment by ramon90** [comment]
Unfortunately, I cannot use smaller images, the image needs to be displayed as it is,

**Comment by ramon90** [comment]
Any one knows a fix please :'(

**Comment by ianpogi5** [comment]
> Unfortunately, I cannot use smaller images, the image needs to be displayed as it is,

how big are your images?

**Comment by ramon90** [comment]
> > Unfortunately, I cannot use smaller images, the image needs to be displayed as it is,
> 
> how big are your images?

I fixed the problem. It was due to large images, they were 3000X4000, i resized them to 1000X1000
