### ISSUE TITLE
Error:(20, 5) error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by AlmogRnD** [DylanVann/react-native-fast-image#48]
Getting the following issues when trying to build for Android works for iOS

`/Users/Almog/Full-Time-Employment/Construction-Cloud/RnD/CCMobileApp/node_modules/react-native-fast-image/android/src/main/java/com/dylanvann/fastimage/FastImageViewPackage.java`
`Error:(20, 5) error: method does not override or implement a method from a supertype`

```
Error:Execution failed for task ':react-native-fast-image:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

Any ideas how to fix this?

**Comment by AlmogRnD** [comment]
Any updates on this?

**Comment by arabscimitar** [comment]
#47

**Comment by DylanVann** [comment]
Duplicate of https://github.com/DylanVann/react-native-fast-image/issues/47
