### ISSUE TITLE
error while updating 'source' of a view on android null uri

### ISSUE THREAD

**Issue by jihyeonjeong11** [DylanVann/react-native-fast-image#484]
**Describe the bug**
The title says it's problem.

I check all issues relating this, but I think the situation little different from them sine they uploaded the same error with 'null null'...
I tried to change my fastimageviewmanager.java on this link
https://github.com/DylanVann/react-native-fast-image/commit/f21522c4092c9ccf5a8c83e56f2c5c4ae3ddc1c8
but not helped(No ImageViewWithUrl symbol)
Thanks in advance.

**To Reproduce**
Steps to reproduce the behavior if possible, or a link to a reproduction repo:
1. npm install
2. react-native link
3. add some FastImage tags

**Expected behavior**
Images should appear nicely

**Screenshots**
![Screenshot_20190528-101722_Crunch_Price](https://user-images.githubusercontent.com/44692923/58444256-5bccb100-8132-11e9-81bb-456746c402b7.jpg)

**Dependency versions**

- React Native version: 0.59
- React version: 16.5
- React Native Fast Image version: 0.0.5(fast image expo)

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

**Comment by Ilphrin** [comment]
Hi @jihyeonjeong11! Can please provide a code sample of what you tried to achieve?
This error means that you are providing a wrong value for `source` prop, maybe a typo in the imported image or something like that

**Comment by jihyeonjeong11** [comment]
Thanks for your feedback.
I finally figured out this happens when Flatlist renders FastImage tag without a value on android environment, not ios.
Also, nesting buttons inside FastImage tag also causes this error on android.

like this.
```
<FastImage>
  <TouchableWithoutFeedback />
</FastImage>
```
this throws an error on android.
