### ISSUE TITLE
'SDWebImage/UIImageView+WebCache.h' file not found

### ISSUE THREAD

**Issue by Doko-Demo-Doa** [DylanVann/react-native-fast-image#49]
RN 0.46.4

```
node_modules/react-native-fast-image/ios/FastImage/FFFastImageView.h:3:9: fatal error: 'SDWebImage/UIImageView+WebCache.h' file not found
#import <SDWebImage/UIImageView+WebCache.h>
        ^
1 error generated.
```

**Comment by chrise86** [comment]
@Doko-Demo-Doa did you manage to fix your issue?

**Comment by Doko-Demo-Doa** [comment]
@chrise86 Yes. Originally I want to modify the library to use with my RN 0.46.4 project (which cannot be upgraded to 0.47 due to certain old plugins).

But when I forked the repo. I realized that the SDWebImage IOS library cannot be downloaded because yarn does not install git submodules by default. You have to either install the dependencies by NPM, or re-publish the package yourself to NPM registry with a new name.

I published it with the name `react-native-fast-image-legacy` , so you can install it using yarn or npm:

`yarn install react-native-fast-image-legacy`

**Comment by DylanVann** [comment]
@Doko-Demo-Doa Glad you were able to resolve this, hopefully you can get those plugins updated one day.
