### ISSUE TITLE
Execution failed for task ':react-native-fast-image:compileDebugJavaWithJavac'. 

### ISSUE THREAD

**Issue by acevedo93** [DylanVann/react-native-fast-image#499]
Any solution for this?
These are my dependencies.

"react-native": "^ 0.58.6",
"react-native-fast-image": "^ 6.0.3",

**Comment by JeremyBradshaw7** [comment]
I need this resolved too
"react-native": "^ 0.59.9",
"react-native-fast-image": "^ 6.0.3",

**Comment by roshan-p** [comment]
Same errors.
I thinks it is related to AndroidX issues

**Comment by JeremyBradshaw7** [comment]
> Same errors.
> I think it is related to AndroidX issues

Yes I think so. Google introduced some change a few days ago that seems to force AndroidX compatibility. I'm going to have to drop fast-image temporarily and revert to the standard Image until this is addressed.

**Comment by rphlmr** [comment]
I just add this package to my project and it compiles without errors.
`"react-native": "0.59.8",`

What should I do to reproduce this error ?

**Comment by roshan-p** [comment]
I'm not sure why but many java's file in android/build folder of react-native-fast-image still creating file with some old build artifact for example android.support.annotation.NonNull instead of  androidx.annotation.NonNull

**Comment by adamterlson** [comment]
I was able to work around this error by following [this guide](https://github.com/DylanVann/react-native-fast-image/blob/master/docs/app-glide-module.md) to disable the glide module, which is the module that has the erroneous generated content:

android/build.gradle
```
project.ext {
    excludeAppGlideModule = true
}
```

**Comment by sootood** [comment]
same error

**Comment by paolospag** [comment]
I get the same error if I use `react-native-fast-image@6.1.0` with `react-native@0.60.0-rc.3`.
Probably this is due to the lack of support for AndroidX and, as @adamterlson  has already said, a [jetifier](https://github.com/mikehardy/jetifier) support is needed
@DylanVann any update on this?

**Comment by DylanVann** [comment]
`react-native-fast-image@7.0.0` supports AndroidX without modifications.

**Comment by trinadhkoya** [comment]
@DylanVann  completely agreed ! But this is leading to Xcode crash.Can we have any workaround for this.

**Comment by micabe** [comment]
@trinadhkoya   you need to 
1) delete the module from node_modules
2) delete entry in Xcode in Link binary with librairies
3) reinstall fast image node module
4) relink `libRNFastImage.a` in Link binary with librairies section

**Comment by tomoima525** [comment]
For those struggling with 7.0.0, I came up with the solution to use  6.0.3 and  keep Android running.
Checked with RN 0.59.10, but it should probably work with 0.60.x and above
- Under `android` dir of your project add `gradle.properties`

```
android.useAndroidX=true
android.enableJetifier=true
```

This is required to use AndroidX and convert libraries in your project. (By the way you may also want to use https://github.com/mikehardy/jetifier for converting RN project to support AndroidX)

- Under `android` dir of your project, open `build.gradle` and set `glideVersion` to 4.8.0 on your project. For example 

```
buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
        glideVersion = "4.8.0"  // Add this
    }
...
}
```

This will over write the setting in FastImage.

- inside `react-native-fast-image/android/build.gradle` change below:

```
// Comment out this
//    implementation("com.github.bumptech.glide:annotations:${_glideVersion}") {
//        exclude group: "com.android.support", module: "annotations"
//    }
    annotationProcessor "androidx.annotation:annotation:1.1.0" // Add this
```

You might want to write a `post install` script to rewrite the setting above.

`com.github.bumptech.glide:annotation` is where the annotation processing is generating `com.android.support.NonNull` we use `androidx.annotation` instead.

**Comment by ardalahmet** [comment]
@tomoima525 
Thanks! It worked.

I used https://github.com/ds300/patch-package for patching `react-native-fast-image/android/build.gradle` automatically on every `yarn install`.
It works like a charm.

**Comment by jonathanwasaki** [comment]
@tomoima525
Thanks!!
