### ISSUE TITLE
Placeholder image.

### ISSUE THREAD

**Issue by grundmanise** [DylanVann/react-native-fast-image#5]
Hi, thanks for this very useful lib!
It would be great if we could set a placeholder image (to show it while the image is loading).

**Comment by DylanVann** [comment]
Yeah I was thinking of including that but cut it to get the lib released. I'll take a look at how that could be done now.

**Comment by zakster12** [comment]
I really think that  it would be awesome to have a placeholder.

**Comment by gitlovenotwar** [comment]
Yes, placeholder is definitely a must! Great plugin, btw.

**Comment by pavanmehta91** [comment]
@DylanVann  any update on the placeholder? Or any workarounds to have a placeholder(defaultImage) ?

**Comment by wellyshen** [comment]
Great library and waiting for placeholder feature

**Comment by Angelk90** [comment]
@DylanVann : Are there any news?
I saw this: https://github.com/DylanVann/react-native-fast-image/issues/109#issuecomment-351889257

**Comment by AlirezaAkbarix** [comment]
@Angelk90! That's not a wise solution! It's better to handle with `onLoadEnd` method.

**Comment by Angelk90** [comment]
@AlirezaAkbarix :  You could be more specific. Can you give an example?

**Comment by AlirezaAkbarix** [comment]
@Angelk90! You set placeholder prop as default source, then use `onLoadEnd` method to replace that placeholder with new grabbed image (this method should been changed to return image).

**Comment by codingwaysarg** [comment]
Hi! I solved it by using a wrapper component. This is my wrapper component.

[PlaceHolderFastImage](https://gist.github.com/codingwaysarg/1115a6365eff654800b9dd3428104512)

**Comment by staffannase** [comment]
Not sure if other people have this issue but I tend to get a blink when using the wrapper on pages where the image is visible on page load.

**Comment by craigcoles** [comment]
@DylanVann Is there any update on this particular feature? I did see that you mentioned in https://github.com/DylanVann/react-native-fast-image/issues/109#issuecomment-384457112 that it would probably get added. Is it on the roadmap? 🙏

**Comment by zeekay18** [comment]
Is there any plan in adding defaultimage as a placeholder?

**Comment by EgidioCaprino** [comment]
This PR adds `placeholder` prop https://github.com/DylanVann/react-native-fast-image/pull/409

**Comment by timothystewart6** [comment]
What's wrong with just adding `defaultSource`?  https://facebook.github.io/react-native/docs/image.html#defaultsource

**Comment by timothystewart6** [comment]
I've managed to do it like this:

```
      <FastImage          
          source={{
            uri: `https://www.example.com/example.png`,
          }}
          fallback
          defaultSource={require(../images/fallback.png))}
        />
```

I don't think `defaultSource` works with `<FastImage />` but it does with `<Image />` so I set `fallback` so that on an error, it falls back to `<Image />` which supports `defaultSource`

**Comment by EgidioCaprino** [comment]
> What's wrong with just adding `defaultSource`? https://facebook.github.io/react-native/docs/image.html#defaultsource

@timothystewart6 so is it just a matter of naming? I think a `placeholder` prop is more suitable for this case.

> ** Edit **
> Now that I've read the request more this won't address the placeholder feature but it is a workaround for a fallback so I'll leave the comment. Hope this helps.
> 
> I've managed to do it like this:
> 
> ```
>       <FastImage          
>           source={{
>             uri: `https://www.example.com/example.png`,
>           }}
>           fallback
>           defaultSource={require(../images/fallback.png))}
>         />
> ```
> I don't think `defaultSource` works with `<FastImage />` but it does with `<Image />` so I set `fallback` so that on an error, it falls back to `<Image />` which supports `defaultSource`

@timothystewart6 that is great, but covers only the case when an error occurs and you still want to display a default image. It does not cover the case where the actual image is being loaded and you want a placeholder in the meantime.

**Comment by timothystewart6** [comment]
> > What's wrong with just adding `defaultSource`? https://facebook.github.io/react-native/docs/image.html#defaultsource
> 
> @timothystewart6 so is it just a matter of naming? I think a `placeholder` prop is more suitable for this case.
> 
> > ** Edit **
> > Now that I've read the request more this won't address the placeholder feature but it is a workaround for a fallback so I'll leave the comment. Hope this helps.
> > I've managed to do it like this:
> > ```
> >       <FastImage          
> >           source={{
> >             uri: `https://www.example.com/example.png`,
> >           }}
> >           fallback
> >           defaultSource={require(../images/fallback.png))}
> >         />
> > ```
> > I don't think `defaultSource` works with `<FastImage />` but it does with `<Image />` so I set `fallback` so that on an error, it falls back to `<Image />` which supports `defaultSource`
> 
> @timothystewart6 that is great, but covers only the case when an error occurs and you still want to display a default image. It does not cover the case where the actual image is being loaded and you want a placeholder in the meantime.

Not just naming, it handles both the default and fallback.  Wouldn't just passing prop through to the underlying `<Image />` component work?  Maybe I am misunderstanding.  Sorry!

**Comment by sanealytics** [comment]
Here is the code that works in my specific use case

```
            <View>
              { !this.state.isImgLoaded && (
                <FastImage
                  style={{
                    width: 400,
                    height: 450,
                    position: 'absolute',
                  }}  
                  source={{uri: photo.uri}}
                  resizeMode={FastImage.resizeMode.contain}
                />  
              ) } 
              <FastImage
                style={{
                  width: 400,
                  height: 450,
                }}  
                source={{uri: photo.images[this.state.count % photo.images.length]}}
                onLoadEnd={this.handleImgLoaded}
                resizeMode={FastImage.resizeMode.contain}
              />  
            </View>

```

elsewhere -

```
  handleImgLoaded = () =>
    this.setState({ isImgLoaded: true })
```

**Comment by EgidioCaprino** [comment]
@sanealytics what is the first image that you render when `!this.state.isImgLoaded`? Is that a sort of placeholder? If so, why do have to remove it when the actual image is loaded? If you would not remove it that the placeholder would remain when some error occurs while displaying the actual image.

**Comment by sanealytics** [comment]
That is a good idea @EgidioCaprino but it doesn't work for me.
I load a super low res default of the first image as `photo.uri`, and then rotate through the array of high res `photo.images`.
If I don't hide it on first image load, the default photo will flash before the next one does.

Your use case might differ.

**Comment by zackhsuan** [comment]
I feel quite upset that this placeholder feature is still not implemented yet white SDWebImages lib supports it since the very early release. SAD

**Comment by naorzr** [comment]
@zackhsuan so go ahead and implement it,and make a pr, this is an open-source project after all..

**Comment by lucasfeijo** [comment]
@codingwaysarg I've rewritten your wrapper to suit my needs and I think it's cleaner: https://gist.github.com/lucasfeijo/8dc8cdb52558744103cbc3bfe1c617f8

Throwing it out there for anyone that needs a placeholder with fast-image.

**Comment by turingpavan** [comment]
```javascript
import React from 'react'

import FastImage from 'react-native-fast-image'
import { StyleSheet } from 'react-native'
import PLACE_HOLDER_DEFAULT from '../assets/images/placeholder_profile.png';


class SmartImage extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            imageLoading: true
        }
    }

    imageLoadProgress = (e) => {
        this.setState({ imageLoading: false })
        this.props.onProgress && this.props.onProgress(e)
    }
    imageLoadError = () => {
        this.setState({ imageLoading: false })
        this.props.onError && this.props.onError()
    }

    imageLoad = (e) => {
        this.setState({ imageLoading: true })
        this.props.onLoad && this.props.onLoad(e)
    }

    render() {
        let { source } = this.props
        const { style, resizeMode } = this.props
        const { imageLoading } = this.state

        source = imageLoading ? source : (this.props.placeholder || PLACE_HOLDER_DEFAULT);

        return (
            <FastImage
                {...this.props}
                style={style}
                source={source}
                fallback={!this.state.imageLoading}
                onError={this.imageLoadError}
                onProgress={this.imageLoadProgress}
                onLoad={this.imageLoad}
            />
        )
    }
}


export default SmartImage
```

To use elsewhere
```
<SmartImage style={styles.somestyle}
                  source={{ uri: item.someuri }} />

```

**Comment by qalqi** [comment]
```javascript
import React from 'react'

import FastImage from 'react-native-fast-image'
import { StyleSheet } from 'react-native'
import PLACE_HOLDER_DEFAULT from '../assets/images/placeholder_profile.png';


class SmartImage extends React.Component {
    constructor(props) {
        super(props)
        this.state = {
            imageLoading: true
        }
    }

    imageLoadProgress = (e) => {
        this.setState({ imageLoading: false })
        this.props.onProgress && this.props.onProgress(e)
    }
    imageLoadError = () => {
        this.setState({ imageLoading: false })
        this.props.onError && this.props.onError()
    }

    imageLoad = (e) => {
        this.setState({ imageLoading: true })
        this.props.onLoad && this.props.onLoad(e)
    }

    render() {
        let { source } = this.props
        const { style, resizeMode } = this.props
        const { imageLoading } = this.state

        source = imageLoading ? source : (this.props.placeholder || PLACE_HOLDER_DEFAULT);

        return (
            <FastImage
                {...this.props}
                style={style}
                source={source}
                fallback={!this.state.imageLoading}
                onError={this.imageLoadError}
                onProgress={this.imageLoadProgress}
                onLoad={this.imageLoad}
            />
        )
    }
}


export default SmartImage
```

To use elsewhere
```javascript
<SmartImage style={styles.somestyle}
                  source={{ uri: item.someuri }}  placeholder={{uri: globalplaceholderURL }}
/>

<SmartImage style={styles.somestyle}
                  source={{ uri: item.someuri }}  placeholder={REQUIRE_PLACEHOLDER}
/>
```

**Comment by sinodko** [comment]
I've prepared custom wrapper using hooks. 

```js
import React, { useState, useMemo, memo } from "react";
import PropTypes from "prop-types";
import { View, StyleSheet } from "react-native";
import CachedImage from "react-native-fast-image";

const FastImage = memo(
  ({
    renderPlaceholder,
    renderErrorImage,
    onError,
    onLoad,
    imageStyle,
    ...otherProps
  }) => {
    const [isLoading, setLoading] = useState(true);
    const [isErrored, setIsErrored] = useState(false);

    const CachedImageMemoized = useMemo(() => {
      return (
        <CachedImage
          {...otherProps}
          style={[imageStyle, styles.image]}
          onError={() => {
            setLoading(false);
            setIsErrored(true);
            onError && onError();
          }}
          onLoad={e => {
            setLoading(false);
            onLoad && onLoad(e);
          }}
        />
      );
    }, [onError, onLoad, imageStyle, otherProps]);

    return (
      <View style={imageStyle}>
        {CachedImageMemoized}
        {isLoading && renderPlaceholder()}
        {isErrored && renderErrorImage()}
      </View>
    );
  }
);

FastImage.priority = CachedImage.priority;
FastImage.resizeMode = CachedImage.resizeMode;

FastImage.propTypes = {
  renderPlaceholder: PropTypes.func,
  renderErrorImage: PropTypes.func,
  onError: PropTypes.func,
  onLoad: PropTypes.func,
  imageStyle: PropTypes.object.isRequired
  // Your imageStyle can look like:
  // imageStyle = {width: XYZ, height: XYZ}
};

const styles = StyleSheet.create({
  image: { position: "absolute", zIndex: -1 }
});

export default FastImage;
```
I've tried solutions above but I noticed some perforamnce issues. This works for me really well. And it will work for you also if you will memoize props in parent component.

Using this solution you are free to use any react component as Placeholder image and any react component as Error image too.

**Comment by danielgindi** [comment]
Solved in both Android and iOS in https://github.com/DylanVann/react-native-fast-image/pull/550

**Comment by deepgosalia1** [comment]
> Solved in both Android and iOS in #550

@danielgindi I went through your forked repo and the fixing of the placeholder issue. Can you please explain the steps in general to replace @DylanVann's npm module in my project with yours? Do i just copy and replace his files with yours in the nodemodule's folder? or is there any other way?
(please dont mind a this basic question, new to this)

**Comment by muhammad786** [comment]
Seems still no support for a placeholder, following is my workaround for placeholder 


<View>
            { loading &&
                <MImage
                containerStyle={imageStyle}
                uri={placeholderUri}
                />
            }
            <FastImage
            style={loading?{width:0, height:0}:imageStyle}
            source={uri}
            onLoad={()=>{
                setTimeout(()=>{
                    setLoading(false)
                },100)
            }}            
            resizeMode={FastImage.resizeMode.contain}        
            />
        </View>

**Comment by danielgindi** [comment]
@deepgosalia1 The steps are "replace the package's version with the git repo url"

**Comment by thanhtrankma** [comment]
> Yeah I was thinking of including that but cut it to get the lib released. I'll take a look at how that could be done now.
Seems still no support for a placeholder.

**Comment by URvesh109** [comment]
<FastImage style={imageStyle} source={{uri: imgSrc}} />
        <Image style={PLACE_HOLDER_IMAGE_STYLE} source={Images.emptyImg} />
        
export const PLACE_HOLDER_IMAGE_STYLE: ImageStyle = {
  position: 'absolute',
  width: '100%',
  height: '100%',
  zIndex: -100,
  borderRadius: 10,
};

Temporary solution

**Comment by sridix** [comment]
You can use <ImageBackground>

Working fine with below code.
<ImageBackground source={require('../assets/images/logo.png')} resizeMode="center">
    <FastImage
        source={{ uri: item.front_image }}
        style={{
          width: '100%',
          height: undefined,
          aspectRatio: .7,
        }}
        resizeMode={'stretch'}
      />
</ImageBackground>

**Comment by fukemy** [comment]
i didnt find any perfect solution in above posts, even Glide and SdWebImage provide placeholder it's self

**Comment by DylanVann** [comment]
It has been merged. Mostly based on @danielgindi's PR (thank you for that, very thorough). Some of the other solutions in this thread are not bad either, but I wouldn't go that route in this lib, left to userland.

There's certain things that the solution that is merged won't support, e.g. different `resizeMode` for the placeholder, different tint, priority, low resolution networked image, that could be accomplished by something as simple as rendering one `FastImage` below another `FastImage`. I think the merged solution does have the advantage of having superior performance though, and it makes use of what's provided by the native libraries this library depends on.
