### ISSUE TITLE
Build fails on 6.0.3 when using fastlane

### ISSUE THREAD

**Issue by gtebbutt** [DylanVann/react-native-fast-image#501]
**Describe the bug**
After upgrading to 6.0.3, the build works in development - `react-native run-ios` runs fine in the simulator - but fails to build for distribution with fastlane. Rolling back to 5.4.2 fixes the issue. 

Relevant output below: 
```
▸ Building library libRNFetchBlob.a
▸ Building library libRNFetchBlob.a
▸ Compiling picture_psnr_enc.c

❌  error: Build input file cannot be found: '.../node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/libwebp/src/enc/picture_psnr_enc.c'


▸ Compiling yuv_sse2.c

❌  error: Build input file cannot be found: '.../node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/libwebp/src/dsp/yuv_sse2.c'


▸ Compiling yuv_mips_dsp_r2.c

❌  error: Build input file cannot be found: '.../node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/libwebp/src/dsp/yuv_mips_dsp_r2.c'


▸ Compiling yuv_mips32.c

❌  error: Build input file cannot be found: '.../node_modules/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/libwebp/src/dsp/yuv_mips32.c'

[18:18:09]: Exit status: 65
```

I've checked the path under `node_modules` and there doesn't seem to be a `libwebp` folder anywhere, but this doesn't cause a problem for the simulator build. 

**Dependency versions**

- React Native version: 0.59.9
- React version:  16.8.6
- React Native Fast Image version: 6.0.3

**Comment by DylanVann** [comment]
Any way I can reproduce this? Does it also happen with the most recent versions?

**Comment by dreampiggy** [comment]
`/react-native-fast-image/ios/Vendor/SDWebImage/Vendors/libwebp` in 6.x of fast-image

This vendor of git submodule is already been removed. So I guess your cloned cache or something cause this issue.

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/60483205-1407ef00-9cc7-11e9-8479-7d7b1bbcb326.png)

![image](https://user-images.githubusercontent.com/6919743/60483217-1b2efd00-9cc7-11e9-9f75-cf781600ece3.png)

There are no any vendor directory. So this must be something about your git submodule config or cache.

**Comment by DylanVann** [comment]
The latest version of `react-native-fast-image` does things differently regarding native module linking. Let me know if there are still issues @gtebbutt.

**Comment by DISKONEKTeD** [comment]
I too was getting this similar error but downgraded 5.4.2 to fix it

I'm using 0.59.10, and I do not plan on upgrading to react 0.60, as not all react packages have been upgraded to support it and they probably won't for a while, during this transition period.
