### ISSUE TITLE
Ejected app from expo crashes android

### ISSUE THREAD

**Issue by dackom** [DylanVann/react-native-fast-image#505]
If I have
`project.ext {
    excludeAppGlideModule = true
}`
in build.gradle, 
Android app crashes with: 
<img src="https://i.ibb.co/64RzPWq/Screenshot-1561557053.png" alt="Screenshot-1561557053" border="0">

Otherwise app crashes silently.

I just ejected from expo, and this library was the only reason why I ejected. Now I cannot build it or even run it on android. :(

**Dependency versions**

- React Native version: expo sdk 33
- React version: 16.8.3
- React Native Fast Image version: 6.0.3

I googled already a lot, added everything to progurad-rules.pro ... but no luck...
Any ideas?

**Comment by px-amaac** [comment]
These look similar #516

**Comment by DylanVann** [comment]
This will need to wait until Expo updates to React Native 0.60.0.
