### ISSUE TITLE
GIF won't auto play on iOS after upgrading to 6.0

### ISSUE THREAD

**Issue by ouabing** [DylanVann/react-native-fast-image#509]
**Describe the bug**
GIFs won't auto play. Since SDWebImage 5.0, it introduced a new way to render animated images, as described [here](https://github.com/SDWebImage/SDWebImage/wiki/Advanced-Usage#animated-image-50), and removed `FLAnimatedImage` support. And SDAnimatedImageView implemented its own [setImage](https://github.com/SDWebImage/SDWebImage/commit/87bbcdc46ff8857aaebbfbc663c340a351a80a58#diff-9cdf661490007a0fb3566a2760b9597dR239) which is overridden in RNFastImage.

I don't know much about Objective-C, it's hard for me to submit a PR... We may have to use the new `SDAnimatedImage` subclass along with `SDAnimatedImageView` to make GIFs auto play. Or we can use [SDWebImageFLPlugin](https://github.com/SDWebImage/SDWebImageFLPlugin) with `UIImageView` to continue using `FLAnimatedImage` (but maybe won't benefit from SD's new improvements).

**Expected behavior**
GIFs auto play.

**Dependency versions**

- React Native version: 0.59.9
- React version: 16.8.6
- React Native Fast Image version: 16.1.0

**Comment by farad4y** [comment]
Same problem here

**Comment by DylanVann** [comment]
@tberman This is the issue.
