### ISSUE TITLE
Warning: Native component for "FastImageView" does not exist

### ISSUE THREAD

**Issue by lichenglu** [DylanVann/react-native-fast-image#51]
Thank you for the great work! I cannot wait to see it work on my end \(^ ^)/

Here is my basic information:
MacOS Sierra
Expo 20.0.0
React Native 0.47.2

I installed the package following the instruction: 
1. yarn add `react-native-fast-image`
2. react-native link

But when I use it, the terminal gives me this warning `Warning: Native component for "FastImageView" does not exist`, and NO image was shown, only red boxes. But if I change to React Native's Image component, things work as expected.

<img width="381" alt="screen shot 2017-08-26 at 01 21 58" src="https://user-images.githubusercontent.com/14342440/29739164-f9274430-89fc-11e7-8b51-d4505b4f634d.png">

I wonder if it is because I am using expo? But I tried eject expo, and link again, but the warning persists, and no image was showing up. :(

**Comment by denny64** [comment]
+1

**Comment by rmanniez** [comment]
+1

**Comment by Delfyn** [comment]
+1

**Comment by jankarres** [comment]
+1

Expo 20.0.0
React Native 0.47.2
npm 4.6.x

**Comment by pcooney10** [comment]
Projects that use `react-native link` are not compatible with Expo. In order to use a library like this, you must detach your application and use ExpoKit. More information can be found [here](https://docs.expo.io/versions/latest/guides/expokit.html#changing-native-dependencies).

**Comment by pcooney10** [comment]
Also, you may want to consider these alternatives:

  - [https://github.com/wcandillon/react-native-img-cache](https://github.com/wcandillon/react-native-img-cache)
  - [https://github.com/wcandillon/react-native-static-images](https://github.com/wcandillon/react-native-static-images)

**Comment by solababs** [comment]
+1

**Comment by pcooney10** [comment]
@solababs +1 for what? The error? 

This package will not work with Expo. Only an ejected app using ExpoKit.

**Comment by lichenglu** [comment]
@pcooney10 Sorry for the inconvenience. I opened this issue mainly because I failed to use the library after ejecting my expo app. Do I need to go to xcode for extra setup? Because I only ran `react-native link` after ejection.

**Comment by solababs** [comment]
@pcooney10 im not runnning on expo. im running in emulator and also tested on device. i get this red border and the image doesnt display. I used react-native-image-progress with it too and get the same result. on android tho.

**Comment by pcooney10** [comment]
My apologies - disregard my statement then.

I had looked into using this a while ago, and commented my two cents at the time (multiple people were referencing expo in their setup). I got a notification today and didn't read through the entire issue before posting.

I unfortunately do not have much experience with apps ejected from expo, but recall reading something about 'react-native link` not always playing nicely with CocoaPods. There is a brief note on it here: https://docs.expo.io/versions/latest/guides/expokit.html#ios.

This issue / PR might also be helpful (for those looking to use react-native link with ExpoKit projects): https://github.com/facebook/react-native/pull/15460. After a quick take, it seems that this should implemented in the coming version (v22), but I am not certain this will resolve your issue.

**Comment by jssprz** [comment]
+1

**Comment by psyanite** [comment]
+1 😞

**Comment by irfansener** [comment]
+1 :(

**Comment by DylanVann** [comment]
What @pcooney10 said is correct, you cannot use this with a non-ejected app. This is because you cannot make native code additions or modifications when using expo.

**Comment by vitto-moz** [comment]
I don't  use expo but have the same error. However, my app is not ejected - does this mean I should eject my app to use a library? Thanks!

**Comment by sabiya115** [comment]
I am not using expo, and using RN version 50.03, and still getting the same error? 
i linked it using react-native link, but still not working.

**Comment by pcooney10** [comment]
@vitto-moz are you using [`create-react-native-app`](https://github.com/react-community/create-react-native-app)? If so, you are using expo.

**Comment by vitto-moz** [comment]
no, I don't
react-native run-android  (for example)

**Comment by pcooney10** [comment]
@vitto-moz Ok. From what I've read, `react-native link` doesn't always work as expected, so I would maybe use that as your basis when trying to debug your issue. A lot of repos have instructions on how to link manually, so you may need to look through the source and see if all of the dependencies are getting added to your app's `build.gradle` and `AndroidManifest.xml` files.

**Comment by DylanVann** [comment]
A non-ejected app created using `create-react-native-app` uses expo.

`react-native init myproject` will create a plain React Native project.

**Comment by togusa2017** [comment]
@vitto-moz i also had the same issue today. my project was build using react-native init.  I agree with @pcooney10 the react-native link didn't work as expected.

This is what i did to fix:
I created a new project and only added react-native-fast-image and successfully linked it using react-native link and then copied all the changes related to react-native-fast-image(MainActivity, ...) in my former project and it worked. I hope this helps.

**Comment by peteroid** [comment]
Seems the `react-native link react-native-fast-image` missed the step 2 described here https://facebook.github.io/react-native/docs/linking-libraries-ios.html. It worked after doing the step 2 manually.

**Comment by MacKentoch** [comment]
@peteroid As I'm using pod on my iOS project, I guess I have to link manually too.

Did you add `FLAnimatedImage` and `SDWebimage` too?

**Comment by MacKentoch** [comment]
I fixed my issue (no need for linking `FLAnimatedImage` and `SDWebimage`) that was linked to combination of `pod` + `xcode 9` + automatic link with `react-native link`

I gave [more details here](https://github.com/DylanVann/react-native-fast-image/issues/174#issuecomment-378586827)

**Comment by DylanVann** [comment]
Manual linking instructions have been added here: https://github.com/DylanVann/react-native-fast-image/blob/master/docs/installation-manual.md

**Comment by Wbqqqq** [comment]
@peteroid thanks , I'm ok with your method!~

**Comment by reubert22** [comment]
Manual linking worked!
