### ISSUE TITLE
(0, _react.memo) is not a function. FastImageBase

### ISSUE THREAD

**Issue by tvhimanshu** [DylanVann/react-native-fast-image#510]
![Simulator Screen Shot - iPhone 6 - 2019-07-04 at 13 46 44](https://user-images.githubusercontent.com/23523187/60650714-48fc7900-9e62-11e9-8313-5f40041f9b5b.png)

**Comment by Balasnest** [comment]
Exactly facing this issue

**Comment by DylanVann** [comment]
You need to upgrade your version of React. The latest React Native release uses `16.8.6`.
