### ISSUE TITLE
ld: library not found for -lFastImage

### ISSUE THREAD

**Issue by JeremyBradshaw7** [DylanVann/react-native-fast-image#514]
Getting this link error in using 7.0.0 against RN 0.59.9

**Comment by jkdf2** [comment]
I can +1 this happening, but I believe that @DylanVann expects this to happen, based on [the release notes of v7.0.0](https://github.com/DylanVann/react-native-fast-image/releases/tag/v7.0.0) and [this commit removing `react-native link` instructions](41de1fdc6d241d20ce77c5422b9a72d0e433e16a). I don't think the library intends to support React Native versions below v0.60 anymore.

**Comment by DylanVann** [comment]
☝️ @jkdf2 is correct. It [does not intend to support older versions](https://github.com/DylanVann/react-native-fast-image#supported-react-native-versions). If you need to continue using an older version you can use `^6.0.0`.

React Native `0.60.0` is great though, you should upgrade.

**Comment by JeremyBradshaw7** [comment]
I'm using 7.0.0 now with RN 0.59.9 and just did a manual link - seems to work. I plan to upgrade to RN 0.60.0 next month, if I can work out how to migrate my existing solution to use cocoapods.

**Comment by DylanVann** [comment]
I've added a note to the readme.
