### ISSUE TITLE
cani't search it from cocopod

### ISSUE THREAD

**Issue by Ekhui** [DylanVann/react-native-fast-image#518]
what's the name in cocopod?
[!] No podspec found for `react-native-fast-image` in `../node_modules/react-native-fast-image`

**Comment by Ekhui** [comment]
and drag into the xcode will be crash

**Comment by Schabaani** [comment]
same issue using 5.2.0

**Comment by apsuva** [comment]
pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'
its works for me

**Comment by ParshantAroras** [comment]
Thanks @apsuva it works.

**Comment by SABRYX** [comment]
it should be like this    
pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
