### ISSUE TITLE
GIF image with same uri do not rendered sometimes.

### ISSUE THREAD

**Issue by tikkichan4** [DylanVann/react-native-fast-image#53]
FastImage just saved my life, the performance is very good.
However, i found that GIF image do not rendered sometimes.

**_Please noted that the same image were used in both testing._**

First Test:
1) Render the same GIF image with RCTImage, FastImage in the same page. 
2) FastImage component renders placeholder which equals to the image
3) FastImage component do not renders the GIF image. (Although there is no any warning during the loading, I am sure that it is not caused by the image file size because i was waiting for the loading for 5 minutes and RCTImage just successfully rendered the gif image within 5 seconds)

Second Test: 
1) Render the same GIF image with RCTImage, FastImage in the same page. 
2) FastImage component renders placeholder which equals to the image
3) FastImage component renders the GIF image

**Comment by DylanVann** [comment]
@tikkichan4 Thanks for the bug report.

I'd need more information to be able to look into it. Can you reproduce this issue? Is there any gif in particular that causes this issue?
