### ISSUE TITLE
cocoapod install error

### ISSUE THREAD

**Issue by Ekhui** [DylanVann/react-native-fast-image#534]
when I run pod 'RNFastImage', :podspec => '../node_modules/react-native-fast-image/RNFastImage.podspec'

it will be :

[!] Unable to find a specification for `SDWebImageWebPCoder (~> 0.2.3)` depended upon by `RNFastImage`

**Comment by AbdulmalickDimnang** [comment]
@Ekhui just go to ios and then "pod repo update" after that, try again "pod install" then it should be working fine

**Comment by drminh2807** [comment]
> @Ekhui just go to ios and then "pod repo update" after that, try again "pod install" then it should be working fine

It worked!

**Comment by Nathan-Patnam** [comment]
For me I had the exact same file paths being used for my dependencies in both the 'Copy Bundle Resources" and the 'Copy Pod Resources' So I deleted everything in my Copy Pod Resources to have something like:


![Screen Shot 2019-10-13 at 2 09 10 AM](https://user-images.githubusercontent.com/17086697/66711692-b1f76500-ed5e-11e9-8a22-02ffc8f1a26b.png)
![Screen Shot 2019-10-13 at 2 09 15 AM](https://user-images.githubusercontent.com/17086697/66711694-b459bf00-ed5e-11e9-98c8-99dfebd39151.png)
