### ISSUE TITLE
Can not open FastImage.xcodeproj

### ISSUE THREAD

**Issue by Bang9** [DylanVann/react-native-fast-image#535]
**Describe the bug**
can not open FastImage iOS project
It occur error that close immediately my project

**To Reproduce**
open node_modules/react-native-fast-image/ios/FastImage.xcodeproj

**Expected behavior**
open Xcode

**Screenshots**
![image](https://user-images.githubusercontent.com/26326015/62534235-99ad2a80-b883-11e9-9b0e-4fb8b8757523.png)

**Dependency**
fast image version : 7.0.2

**Comment by paulohenriqueav** [comment]
Same issue, any update?

**Comment by pvoznyuk** [comment]
Same issue, any update?

**Comment by ostar0816** [comment]
Same issue, downgraded to v6.1.1 for a temporary workaround.

**Comment by Bang9** [comment]
currently 7.0.x of iOS is not wokring
use 6.1.1 and then fix the build.gradle of android(react-native-fast-image) as '7.0.x' build.gradle file
(6.1.1 using Glide that not supported android x)

**Comment by alpamys-qanybet** [comment]
@Bang9, I followed your instructions, but now my project does not launch. I just replaced ```build.gralde``` file, and replaced by androidx class mappings some error imports. If it is not right, please give me your build.gradle.

**Comment by Bang9** [comment]
@alpamys-qanybet If you set properly, you dont need replace any method to android x by yourself.
do you have `jetifier` ? If you not `npm install --save jetifier`

**Comment by Bang9** [comment]
After upgrade to Xcode 11, Xcode crash is gone from my project(but FastImage.xcodeproj is still a problem)

**Comment by andru1989** [comment]
I'm using `jetifier` but have same issue, using `v7.0.2`
@Bang9 did you find a solution different than downgrading ?

**Comment by Bang9** [comment]
> I'm using `jetifier` but have same issue, using `v7.0.2`
> @Bang9 did you find a solution different than downgrading ?

XCode clean
Remove project
Clone project
npm install
pod install

**Comment by rahamin1** [comment]
@Bang9

> use 6.1.1 and then fix the build.gradle of android(react-native-fast-image) as '7.0.x' build.gradle file (6.1.1 using Glide that not supported android x)

Can you explain what exactly you mean by that?

**Comment by Bang9** [comment]
> @Bang9
> 
> > use 6.1.1 and then fix the build.gradle of android(react-native-fast-image) as '7.0.x' build.gradle file (6.1.1 using Glide that not supported android x)
> 
> Can you explain what exactly you mean by that?

@rahamin1 
1. copy `build.gradle` file in `react-native-fast-image-v7.0.x`
2. open `build.gradle` file in `react-native-fast-image-v6.1.1`
3. paste

**Comment by rahamin1** [comment]
Hmmm... I am risking revealing my ignorance here: I thought that build.gradle is an android file., not an ios file... Does it have to do anything with ios build?

**Comment by Bang9** [comment]
@rahamin1 TLDR
`v7.0.x` working on Android, but throw error on iOS (Xcode issue) -> can't resolve problem
`v6.1.1` working on iOS, but not working on Android (Android-X issue) -> can resolve problem
