### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version "> 0.4.x < 0.9.0".

### ISSUE THREAD

**Issue by brkrtp** [DylanVann/react-native-fast-image#55]
Hi i cant install, its my terminal:
` yarn add react-native-fast-image`
`yarn add v0.27.5`
`[1/4] Resolving packages...`
`warning There appears to be trouble with your network connection. Retrying...`
`[2/4] Fetching packages...`
`error link@0.1.5: The engine "node" is incompatible with this module. Expected version "> 0.4.x < 0.9.0".`
`error Found incompatible module`
`info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Comment by victorbadila** [comment]
+1

**Comment by DylanVann** [comment]
I think this was probably a temporary issue caused by a semver compatible (but broken) update to a dependency of this module. Should be working fine now.

**Comment by dante8300** [comment]
Did anyone managed to solve this issue?

**Comment by ejswenson15** [comment]
+1

**Comment by DylanVann** [comment]
This package no longer specifies an engine requirement. So I don't know why anyone would be having this issue. I'd need more information.

**Comment by giacomocerquone** [comment]
Same here. The real package that is requiring an exact version of node is upath@1.0.4 that probably is a dependencies of this package. @DylanVann

**Comment by flunder** [comment]
I used npm instead of yarn and it was just fine!

**Comment by YogeshSinghNegi** [comment]
> I used npm instead of yarn and it was just fine!

Thanks man, it worked for me too. (Y)

**Comment by BiplovQss** [comment]
me too @flunder . thanks.

**Comment by Ericnsamba** [comment]
try this: yarn --ignore-engines
