### ISSUE TITLE
Dependency issue when building with 6.0.3

### ISSUE THREAD

**Issue by jonassvalin** [DylanVann/react-native-fast-image#555]
**Describe the bug**
Our pipeline is currently failing to build the Android app due to what appears to be a broken dependency:

`> Could not resolve com.github.bumptech.glide:glide:4.7.1.
  Required by:
      project :app > project :react-native-fast-image
      project :app > project :react-native-fast-image > com.github.bumptech.glide:okhttp3-integration:4.7.1
   > Could not resolve com.github.bumptech.glide:glide:4.7.1.
      > Could not get resource 'https://jitpack.io/com/github/bumptech/glide/glide/4.7.1/glide-4.7.1.jar'.
         > Could not HEAD 'https://jitpack.io/com/github/bumptech/glide/glide/4.7.1/glide-4.7.1.jar'. Received status code 522 from server: Origin Connection Time-out
> Could not resolve com.github.bumptech.glide:annotations:4.7.1.
  Required by:
      project :app > project :react-native-fast-image
   > Could not resolve com.github.bumptech.glide:annotations:4.7.1.
      > Could not get resource 'https://jitpack.io/com/github/bumptech/glide/annotations/4.7.1/annotations-4.7.1.pom'.
         > Could not GET 'https://jitpack.io/com/github/bumptech/glide/annotations/4.7.1/annotations-4.7.1.pom'. Received status code 522 from server: Origin Connection Time-out`

**Expected behavior**
App should build successfully

**Dependency versions**

- React Native version: 0.59.5
- React version: 16.8.6
- React Native Fast Image version: 6.0.3

**Note:** if these are not the latest versions of each I recommend updating as extra effort will not be taken to be backwards compatible, and updating might resolving your issue.

We are in the processing of undergoing the new react-native upgrade but we're not quite there yet. It's unclear if that would help this issue.

**Comment by jonassvalin** [comment]
We managed to resolve this by completing the react native upgrade which allowed us to use a newer version of RNFI, but my guess would be that the problem remains. Thanks!

**Comment by TheSolly** [comment]
@jonassvalin to what version did you upgrade your react-native?
facing the same issue running RN-"0.59.10" and RNFI-"^6.1.1" and RNFI-"^7.0.2"

**Comment by Kottidev** [comment]
@jonassvalin  Please update glideVersion to  "4.10.0"

**Comment by nefelilygourioti** [comment]
Also had this, navigated to https://www.jitpack.io/com/github/bumptech/glide/glide/4.7.1/glide-4.7.1.pom and got a failed build warning.

Incredibly, this solved it for me: 
https://gitmemory.com/issue/jitpack/jitpack.io/3970/531199447
