### ISSUE TITLE
Ability to set auto height, issues with images getting cropped  

### ISSUE THREAD

**Issue by AlmogRnD** [DylanVann/react-native-fast-image#56]
With the current version, you have to set width and height which then crops the images it would be great to have an option to set auto height or use something like this - https://github.com/vivaxy/react-native-auto-height-image

**Comment by EsdrasEtrenne** [comment]
would be super sweet!

**Comment by DylanVann** [comment]
The reason `Image` doesn't do this is because it will create UI jank by pushing everything down when the image is loaded (since you don't know the dimensions / ratio before hand).

**Comment by DylanVann** [comment]
Yeah I think it's best for user experience to not do this. I also think it's out of scope for now.

**Comment by timurridjanovic** [comment]
dude.. this is a necessary feature.. You can't always know the height of the image beforehand, especially if it's user generated images...

**Comment by drewandre** [comment]
I agree that this is a necessary feature not just for this library, but for React-Native's `<Image />` component as well. I just switched to fast-image from auto-height-image (super happy with the switch -- this lib is amazing), but I do miss the flexibility of having auto height. We're building an instagram-style feed with user generated photos that are of varying, unknown heights when the initial /GET photos response is returned.

**Comment by rawris** [comment]
Any update on this issue? I'm using FastImage on Production level app and this feature is very necessary
