### ISSUE TITLE
resizeMode=FastImage.resizeMode.stretch does not work

### ISSUE THREAD

**Issue by pingxiaodou** [DylanVann/react-native-fast-image#57]
There is my code, when I set resizeMode={FastImage.resizeMode.stretch},the images does not show as expected,bu other resizeMode works well, why I got this issue?
`<FastImage
                        style={{
                            width: Global.width,
                            height: Global.width * 0.45,
                            borderWidth: 1,
                        }}
                        source={{
                            uri: "xxx.jpg"
                        }}
                        resizeMode={FastImage.resizeMode.stretch}
                    />`
![image](https://user-images.githubusercontent.com/23648004/30052186-425ab5e4-9257-11e7-9b1f-46df97d0e95e.png)

**Comment by witalobenicio** [comment]
@pingxiaodou how did you solve that?

**Comment by cuongchau93** [comment]
i encounter this issue today, 
Later I found out the problem is due to I have fallback turn on
Removing that props solve the issue image not stretch
