### ISSUE TITLE
v8.0.0 not released on npm

### ISSUE THREAD

**Issue by steobrien** [DylanVann/react-native-fast-image#593]
**Describe the bug**
Version 8.0.0 is not available through NPM

**To Reproduce**
1. Go to https://www.npmjs.com/package/react-native-fast-image
2. Version is 7.0.2

**Expected behavior**
Version should be 8.0.0, as per the releases tab here

**Screenshots**
![image](https://user-images.githubusercontent.com/1694410/67775874-eb55f300-fa35-11e9-89b5-f5ee960b85b9.png)

**Comment by DylanVann** [comment]
Sorry, this was a two-factor-auth issue. It's released now 🎊
