### ISSUE TITLE
SDWebImage pod issue 

### ISSUE THREAD

**Issue by eyu0415** [DylanVann/react-native-fast-image#596]
SDWebImage 5.3.1 released 2days ago

https://github.com/SDWebImage/SDWebImage/releases

react-native-fast-image has SDWebImage & SDWebImageWebPCoder

recently SDWebImage has no file called 'SDWebImage.h'

but SDWebImageWebPCoder has import 'SDWebImage.h'

so it occured import error

If I set SDWebImage pod version to 5.2.5 the error resolved

**Comment by taschik** [comment]
I am seeing the same in my build:

```
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
--
  | In snapshot (Podfile.lock):
  | SDWebImage (= 5.3.1, ~> 5.0)
  |  
  | In Podfile:
  | RNFastImage (from `../node_modules/react-native-fast-image`) was resolved to 7.0.2, which depends on
  | SDWebImage (~> 5.0)
  |  
  |  
  | You have either:
  | * changed the constraints of dependency `SDWebImage` inside your development pod `RNFastImage`.
  | You should run `pod update SDWebImage` to apply changes you've made.

```

Isn't there a better way than manually overwriting the dependency version?

**Comment by joelfsreis** [comment]
Any progress on this? Also happens with my project, using SDWebImage 5.3.1 don't work but if I use version 5.2.3 it works fine...

**Comment by dreampiggy** [comment]
Is this issue still re-producable ?

I guess this because of the hard-coded path for react-native-fast-image. SDWebImage 5.3 seems does not change anything related to project...Only new added source files ?

**Comment by joebernard** [comment]
I just upgraded `react-native-fast-image` from ^7.0.2 to ^8.1.5 I get this issue. It happened after I ran `pod install`. I rolled back to ^7.0.2 and the problem went away.

**Comment by dreampiggy** [comment]
> I just upgraded `react-native-fast-image` from ^7.0.2 to ^8.1.5 I get this issue. It happened after I ran `pod install`. I rolled back to ^7.0.2 and the problem went away.

Can anyone provide a reproducable demo ? Which I can `pod install` on it.

Provide the SDWebImageWebPCoder version is better

**Comment by pankajgupta1** [comment]
This worked for me [](https://github.com/DylanVann/react-native-fast-image/blob/master/docs/troubleshooting.md)

**Comment by pankajgupta1** [comment]
I followed the steps on following link. These worked perfectly for me [https://github.com/DylanVann/react-native-fast-image/blob/master/docs/troubleshooting.md](url)

**Comment by everfire130** [comment]
1. remove ios/Podfile.lock
2. and `pod install`

It will be fine!

**Comment by huapeng222** [comment]
I have edit ```../node_modules/react-native-fast-image/RNFastImage.podspec```
change
```
s.dependency 'SDWebImage', '~> 5.0'
s.dependency 'SDWebImageWebPCoder', '~> 0.4.1'
```
to
```
s.dependency 'SDWebImage'
s.dependency 'SDWebImageWebPCoder'
```

It's work fine to me.

**Comment by ajaymarathe9** [comment]
> 1. remove ios/Podfile.lock
> 2. and `pod install`
> 
> It will be fine!

It's working thanks :)

**Comment by tchesa** [comment]
> I have edit `../node_modules/react-native-fast-image/RNFastImage.podspec` change
> 
> ```
> s.dependency 'SDWebImage', '~> 5.0'
> s.dependency 'SDWebImageWebPCoder', '~> 0.4.1'
> ```
> 
> to
> 
> ```
> s.dependency 'SDWebImage'
> s.dependency 'SDWebImageWebPCoder'
> ```
> 
> It's work fine to me.

It worked for me, but it can't be done on CI/CD, can it? Definitely the problem is there. Repoen the issue please.
