### ISSUE TITLE
Could not resolve all artifacts for configuration ':react-native-fast-image:classpath'.    > Could not download kotlin-reflect.jar

### ISSUE THREAD

**Issue by zhonggithub** [DylanVann/react-native-fast-image#599]

**Comment by ttylikl** [comment]
> _No description provided._

为啥关闭啦？我也遇到这个问题了。不是翻墙能解决的

**Comment by EliseiNicolae** [comment]
Why this one is closed? I have the same problem.

`A problem occurred configuring project ':react-native-fast-image'.
> Could not resolve all artifacts for configuration ':react-native-fast-image:classpath'.
   > Could not resolve com.android.tools.build:builder:3.4.0.
     Required by:
         project :react-native-fast-image > com.android.tools.build:gradle:3.4.0
      > Could not resolve com.android.tools.build:builder:3.4.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/builder/3.4.0/builder-3.4.0.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/builder/3.4.0/builder-3.4.0.pom'.
               > Read timed out
   > Could not resolve com.android.tools.analytics-library:crash:26.4.0.
     Required by:
         project :react-native-fast-image > com.android.tools.build:gradle:3.4.0
      > Could not resolve com.android.tools.analytics-library:crash:26.4.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/analytics-library/crash/26.4.0/crash-26.4.0.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/analytics-library/crash/26.4.0/crash-26.4.0.pom'.
               > Read timed out
   > Could not resolve com.android.tools.build:gradle-api:3.4.0.
     Required by:
         project :react-native-fast-image > com.android.tools.build:gradle:3.4.0
         project :react-native-fast-image > com.android.tools.build:gradle:3.4.0 > com.android.tools.lint:lint-gradle-api:26.4.0
      > Could not resolve com.android.tools.build:gradle-api:3.4.0.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle-api/3.4.0/gradle-api-3.4.0.pom'.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle-api/3.4.0/gradle-api-3.4.0.pom'.
               > Read timed out`
