### ISSUE TITLE
Support pinch to zoom, panning of images

### ISSUE THREAD

**Issue by srameshr** [DylanVann/react-native-fast-image#60]
If you are looking for this features, please emoji vote this comment instead of +1

**Comment by tikkichan4** [comment]
Seeking for this feature too !

**Comment by pewh** [comment]
+1

**Comment by Najibsaurus** [comment]
+1

**Comment by dotansimha** [comment]
As a workaround, you can use `react-native-image-pan-zoom` package. it supports a third-party `Image` components.

**Comment by hoorsa** [comment]
+1

**Comment by DylanVann** [comment]
I think it's out of the scope of this package.

https://www.npmjs.com/package/react-native-image-pan-zoom looks pretty great.

**Comment by bobber205** [comment]
Would love this feature built in natively.

The pan zoom library at least for me so far in "compatible" with fast image but it's a bit hard to manage the gestures for both using a carousel (like react-native-swiper) and fast image.

**Comment by ramon90** [comment]
Would be great to have zooming natively. Zooming on JS side is extremely slow, especially with long list of images.

**Comment by salhotra** [comment]
One solution to this is to have a zoomable parent View. Zooming and caching both will work. This can be implemented using react-native-gesture-handler or a couple of well-maintained packages are also available.

But, considering a very common scenario where multiple images are shown inside a Modal > ViewPager (swipeable), zooming will work just fine here. But if we want to drag around the zoomed image, pan handler of the swiper will take charge. So in this very common scenario, native zooming will do the job. This package https://github.com/alwx/react-native-photo-view does exactly this, but there is no caching available there :(

**Comment by crushy26** [comment]
Try this guys https://github.com/oblador/react-native-pinchable
