### ISSUE TITLE
[Android] Update build tools version

### ISSUE THREAD

**Issue by tdekoning** [DylanVann/react-native-fast-image#61]
New android projects will use `buildToolsVersion` 26 in combination with gradle build tools v3. This is incompatible with the current `buildToolsVersion` used in this library.
This basicly means that new android projects will not be able to use this library.

To fix this, the `build.gradle` needs to have a `buildToolsVersion` of at least `25.0.2`.

**Comment by DylanVann** [comment]
I believe this would break backwards compatibility with people using older versions of gradle and the built tools.

Using the latest Gradle I do see the warning about the build tools version. For now I'm going to leave the version as is, probably at least until React Native produces projects which use Gradle 3.
