### ISSUE TITLE
`react-native link` is still required?

### ISSUE THREAD

**Issue by GollyJer** [DylanVann/react-native-fast-image#611]
Hi! Came back to check on this project and was a little excited to see `react-native link` no longer part of the instructions.

Sadly, I get the `"FastImageView" was not found in UIManager` error when trying to run an Expo app.

Does this means linking is still required?

**Comment by StagasaurusRex** [comment]
I had the same issue but all I had to do was rebuild the project.

**Comment by GollyJer** [comment]
@StagasaurusRex Are you using [Expo](https://expo.io/learn)?
I deleted `node_modules` and ran `yarn install` with `react-native-link` inside `package.json` dependencies.
Still got the same error.

**Comment by StagasaurusRex** [comment]
I am not using expo, and I didn't run `react-native link`

**Comment by ardyfeb** [comment]
> I am not using expo, and I didn't run `react-native link`

You should eject expo before using package with native code, this link maybe help you https://docs.expo.io/versions/latest/expokit/eject/

**Comment by GollyJer** [comment]
Thanks @ardyfeb. All the packages I've run into in the past that required ejected needed to run `react-native link`.
This is the first time I've seen one that didn't.

Closing... 👍
