### ISSUE TITLE
Peer dependency warning

### ISSUE THREAD

**Issue by ahce** [DylanVann/react-native-fast-image#612]
**Describe the bug**
```
npm WARN react-native-fast-image@7.0.2 requires a peer of react-native@^0.60.0 but none is installed. You must install peer dependencies yourself.
```

**To Reproduce**
1. npm i --save react-native-fast-image

**Expected behavior**
No peer warn.

**Dependency versions**

- React Native version: 0.61.5
- React version: 16.9.0
- React Native Fast Image version: 7.0.2

**Comment by curiousdustin** [comment]
Can we get this in the next release?
