### ISSUE TITLE
blureRadius is not supported

### ISSUE THREAD

**Issue by nimamyscreen** [DylanVann/react-native-fast-image#62]
blurerRaduis Image is supported in react-native 46 and your RN version is 45 , plz upgrade your RN version to at least 46.

**Comment by chrise86** [comment]
Duplicate of https://github.com/DylanVann/react-native-fast-image/issues/50

**Comment by DylanVann** [comment]
Upgrading the version of RN will not fix this as this does not use the RN Image component.

Dupe https://github.com/DylanVann/react-native-fast-image/issues/50
