### ISSUE TITLE
problem with HEIC

### ISSUE THREAD

**Issue by ramyareye** [DylanVann/react-native-fast-image#621]
Hello, well done :)

**Describe the bug**
I cannot work with HEIC in fast-image

any chance to make it work ?

**Comment by dreampiggy** [comment]
For iOS 11+ it should support. SDWebImage’s built-in coder handle this format.

If not, add `SDImageHEICCoder` in AppDelegate may fix this issue, also with the Animates HEIC(HEIC Sequence) support.

**Comment by ramyareye** [comment]
thanks @dreampiggy 
how about android? is there anyway other than converting image to show?

**Comment by dreampiggy** [comment]
Android need open source implementation, such as this libheif.

Ask the Android framework author (seems Glide ?) to integrate this third party codec.

SDWebImage can also disply heif in iOS8~iOS 10, you must use the externel codec as well, see

**Comment by ramyareye** [comment]
Thanks I searched and I found some discussions on android. I will try to find a way make it.
