### ISSUE TITLE
onProgress no longer working

### ISSUE THREAD

**Issue by nica0012** [DylanVann/react-native-fast-image#633]
This was working fine before, but now I can't even get the onProgress value to log...

I noticed this on v7.0.2, then reverted to v6.1.1 and am still having the same problem.

```
        <FastImage
          resizeMode={ratio ? 'contain' : 'cover'}
          source={{uri: this.state.fullResImage}}
          // onProgress={this.onProgressImage}
          onProgress={e => console.log(e.nativeEvent.loaded / e.nativeEvent.total)}
          style={[
            styles.imageStyle,
            {
              width: undefined,
              height: ratio ? ratio * deviceWidth : 1 * deviceWidth,
              zIndex: this.state.imgLoaded ? 99999999 : -99999999,
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              bottom: 0,
            },
          ]}
          onLoad={this.onLoadImage(ratio)}
          onLoadEnd={this.onImageLoaded}
        />
```

**Comment by nica0012** [comment]
Silly me... Images were cached, therefore they're already loaded...

**Comment by someAndroidDeveloper** [comment]
It's happening to me with the main react-native's **Image** component. 
I suspected about the cache and also cleared it. plus, I changed my URL as well.
In both cases function not getting called.

**Comment by karansoni725** [comment]
HI All,  any solution of this issue  ?

**Comment by ManushivamD11** [comment]
Have changed the URL, have tried many heavy size URLs as well but onPrgress isn't getting called. Is there a bug?
