### ISSUE TITLE
Invalid `RNFastImage.podspec` file: syntax error, unexpected tIDENTIFIER, expecting '}'

### ISSUE THREAD

**Issue by dagouzhi** [DylanVann/react-native-fast-image#644]
**Describe the bug**

[!] Invalid `Podfile` file: 
[!] Invalid `RNFastImage.podspec` file: syntax error, unexpected tIDENTIFIER, expecting '}'
  s.source_files  = "./ios/**/*.{h,m}"

**Comment by dagouzhi** [comment]
`
s.source        = { :git => "https://github.com/DylanVann/react-native-fast-image.git", :tag => "v#{s.version} }
`

**Comment by jason11ac** [comment]
I have the same issue!

**Comment by DylanVann** [comment]
Thank you! Should have had a closing `"`. Fixed in `8.1.2`.
