### ISSUE TITLE
iOS Error since 8.1.0 commit.

### ISSUE THREAD

**Issue by jrz** [DylanVann/react-native-fast-image#645]
This version gives me a file-not-found for "src". It seems this changed since 8.1.0

Metro Bundler has encountered an error: ENOENT: no such file or directory, lstat ......../react-native-fast-image/src.

8.0.0 works properly

**Comment by DylanVann** [comment]
How are you importing? You should not have `src` in your import path.

```diff
- import FastImage from 'react-native-fast-image/src/index.js'
+ import FastImage from 'react-native-fast-image'
```

The `8.1.0` release uses TypeScript, so the `main` file is now `dist/index.js`, not `src/index.js`, but as mentioned above, this location should not usually be relied on anyways.

**Comment by jrz** [comment]
import FastImage from 'react-native-fast-image';

Using RN 0.61 + TS.  I simply updated to 8.1.0. Not sure why it’s referring to src/, but I’ll let you know later this week.

**Comment by DylanVann** [comment]
Try clearing your metro cache.

```
react-native start --reset-cache
```

https://github.com/DylanVann/react-native-fast-image/blob/master/docs/troubleshooting.md

**Comment by jrz** [comment]
Removing node_modules seems to have worked.. 
Hopefully one day npm/yarn will be stable/usable

**Comment by DylanVann** [comment]
I don’t think it’s an npm/yarn issue, it’s a Metro Bundler issue, stale cache. Anyways, glad it’s working now 👍.
