### ISSUE TITLE
JSX element type 'FastImage' does not have any construct or call signatures

### ISSUE THREAD

**Issue by celucode** [DylanVann/react-native-fast-image#646]
**Describe the bug**
When I try to use the imported FastImage package, I get the following error in the component: "JSX element type 'FastImage' does not have any construct or call signatures."

**To Reproduce**
1. Create a ReactNative project with typescript
2. In a .tsx file, type import the package using the following: import FastImage from 'react-native-fast-image';
3. Try to use the component, you will get the error in the declaration.

**Expected behavior**
Not showing any error

**Screenshots**
![Screenshot_2](https://user-images.githubusercontent.com/23288172/76367408-87e8a580-62f2-11ea-9103-9d7e62b37046.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/23288172/76367409-89b26900-62f2-11ea-8827-1867f0ea9547.jpg)

**Dependency versions**

- React Native version: 0.61.1
- React version: 16.8.1
- React Native Fast Image version: 8.1.2

**Comment by mtakac** [comment]
Same thing is happens to me. Didn't really have time to look into it, but in v7.0.2 the import works as documented.

**Comment by celucode** [comment]
I just added `declare module 'react-native-fast-image';` to a .d.ts file and the error is gone, but also the types. Will be using it like this while finding a better solution.

I want to avoid downgrading to an older version, but thanks for the hint @mtakac

**Comment by DylanVann** [comment]
Types should be better in the future. The source and example are now both in TypeScript.

**Comment by pvshum** [comment]
The issue still exist. Any hints on how to fix?

**Dependency versions**
- "react": "17.0.2",
- "react-native": "0.68.2",
- "react-native-fast-image": "8.5.11",
-  "typescript": "^3.8.3"

 <img width="644" alt="Screenshot 2022-06-27 at 11 13 13" src="https://user-images.githubusercontent.com/995412/175904596-c4c4097d-a25f-4a69-a815-dbfc3dc22773.png">

**Comment by forbesgillikin** [comment]
This is an issue with the `@types/react` package. Adding

```
"resolutions": {
    "@types/react": "17.0.43"
  }
```

to your package.json if using yarn will solve this.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/59765#issuecomment-1092891129
