### ISSUE TITLE
Build failing on XCode 9

### ISSUE THREAD

**Issue by aidenwallis** [DylanVann/react-native-fast-image#66]
Build doesn't seem to exceed because of SDWebImage - maybe it's something like an out of date dependency?

http://prntscr.com/gn86ro

If you can give me any advice/some sort of fix ASAP that would be appreciated :)

**Comment by flikQ** [comment]
Getting same issue here. Any help would be awesome.

**Comment by lewisbye** [comment]
Same issue here! Needing help on this ASAP!

**Comment by chrise86** [comment]
I found that it only fails when using `react-native run-ios`; running via Xcode _seems_ to work fine. Oddly though, even when running the CLI command it still builds and runs the app in the simulator...

**Comment by aidenwallis** [comment]
I've always ran through xcode, so not sure why I'm getting an issue then.

**Comment by jsteiner** [comment]
Cleaning the build folder solved this for me.

**Comment by hkung77** [comment]
Cleaning the build worked to get the build on the simulator. However the errors for SDWebImage still exist.

**Comment by aidenwallis** [comment]
I managed to fix this by doing Project -> Clean in XCode, gonna close this, hope this works for you all!

**Comment by taiki-t** [comment]
Also doing `rm -rf ~/Library/Developer/Xcode/DerivedData/*` solved problem with running simulator with `react-native run-ios`

**Comment by cooleagle8837** [comment]
Cleaning XCode would work for sure.
