### ISSUE TITLE
[iOS][react-native 0.62.1] Crash app when use source uri base64 or file:///

### ISSUE THREAD

**Issue by vuongductuanktmt** [DylanVann/react-native-fast-image#662]
**Describe the bug**
Crash app when use source={{uri: 'data:image/png;base64...'}} or  source={{uri: 'file:///...'}} after choose file, but when using react-native Image, there are no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/25997663/78486707-78357300-7771-11ea-8088-b50e006280fc.png)

**Dependency versions**

- React Native version: 0.62.1
- React Native Fast Image version: 8.1.5

**Comment by mariasiuvlad** [comment]
Running into the same issue

Dependency versions
React Native version: 0.62.1
React Native Fast Image version: 8.1.5

**Comment by Skullcan** [comment]
I think it's a bug on the React 0.62 version.
Ppl recommended updating to 0.62.1. Nothing changed. still having problems.

**Comment by excitedcat** [comment]
Same problem on debug mode

React Native 0.62

**Comment by excitedcat** [comment]
Do you have a solution @vuongductuanktmt @Skullcan @mariasiuvlad

**Comment by Skullcan** [comment]
Not that I know off.
What I'm doing right now is converting your data:image base64 to a temporary png/jpg in to disk and using it to display the image.

**Comment by dreampiggy** [comment]
On iOS, the backend SDWebImage framework can handle any of this cases `base64:// or file://`. I think it's bug of the react-native-fast-image caller code itself...

**Comment by dreampiggy** [comment]
![image](https://user-images.githubusercontent.com/6919743/79041304-5c264b80-7c21-11ea-8a77-c3d004510ac2.png)

**Comment by sharifhh** [comment]
The problem is from flipper, please update flipper to version 0.37.0 from Podfile

**Comment by vuongductuanktmt** [comment]
> The problem is from flipper, please update flipper to version 0.37.0 from Podfile

@sharifhh thank you, it work

**Comment by rcferreira** [comment]
> The problem is from flipper, please update flipper to version 0.37.0 from Podfile

Work! great, thanks
