### ISSUE TITLE
[NSURLResponse allHeaderFields]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by joebernard** [DylanVann/react-native-fast-image#667]
**Describe the bug**
When passing a local file URL to FastImage, my iOS app crashes with the following error:

<details>
<summary>-[NSURLResponse allHeaderFields]: unrecognized selector sent to instance</summary>
NSInvalidArgumentException -[NSURLResponse allHeaderFields]: unrecognized selector sent to instance 0x60000bdf1880 
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRootFrameworks/CoreFoundation.framework/CoreFoundation __exceptionPreprocess
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/libobjc.A.dylib objc_exception_throw
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRootFrameworks/CoreFoundation.framework/CoreFoundation -[NSObject(NSObject) doesNotRecognizeSelector:]
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRootFrameworks/CoreFoundation.framework/CoreFoundation ___forwarding___
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRootFrameworks/CoreFoundation.framework/CoreFoundation _CF_forwarding_prep_0
    juncture +[SKResponseInfo shouldStripReponseBodyWithResponse:]
</details>

I'm using react-native-camera to take pictures, and the local content URL of a captured picture is in the form of

"file:///Users/joebernard/Library/Developer/CoreSimulator/Devices/64C2F041-8C0A-4B46-91B6-3A4BBE68A5C5/data/Containers/Data/Application/F1C6E8B3-CA4F-44B7-899D-F2ACB9AECB44/Library/Caches/Camera/7286B0AB-2B79-4067-A8DF-2FEB7A23DEAD.jpg"

Passing that into `source.uri` causes the crash. Passing remote `https://` URLs works.

I noticed this started occurring after I upgraded to RN 0.62.2.

Loading local URLs works in a regular RN `<Image/>` component.

**To Reproduce**
Pass a `file:///` URL to FastImage.

**Expected behavior**
Load the local image.

**Dependency versions**

- React Native version: 0.62.2
- React version: 16.11.0
- React Native Fast Image version: 8.1.5

**Comment by joebernard** [comment]
If I pass `fallback={true}` to FastImage (fallback to RN `<Image/>`) the problem goes away.

**Comment by vuongductuanktmt** [comment]
@joebernard same issue [#662](https://github.com/DylanVann/react-native-fast-image/issues/662)

**Comment by joebernard** [comment]
Closing as duplicate
