### ISSUE TITLE
The .measure method is not accessible from FastImage

### ISSUE THREAD

**Issue by Gabri3l** [DylanVann/react-native-fast-image#69]
I am using the `FastImage` in a scenario where I save a reference to the component and, later on, access the `.measure` method to retrieve its width, height, pageX, pageY and so on. Unfortunately this worked well when using a simple `Image` component but fails with `FastImage` as the method is not available. I will try to make a PR with a fix for this, in the mean time I thought it was worth it to report the issue.

Now I can access the method through `_root.measure` but it would be nice if we didn't have to do that and we would be able to access it directly.

**Comment by skizzo** [comment]
@Gabri3l could you share to code to get the `.measure ()` function working? I can't get it right.
