### ISSUE TITLE
[iOS] Headers for one request are sent for all subsequent requests, even if no headers specified

### ISSUE THREAD

**Issue by andreialecu** [DylanVann/react-native-fast-image#690]
**Describe the bug**

When an image with `source={{uri: "...", headers: { host: "somehost.com", authorization: "..." }}` is loaded, all other subsequent images will use the same headers.

This can lead to images not showing, because the `host` header is wrong, and web servers will return 404 errors for the request.

**To Reproduce**
Steps to reproduce the behavior if possible, or a link to a reproduction repo:
1. Go to https://hookbin.com/ and create a new endpoint
2. Add an image with `source={{ uri: "hookbin endpoint #1", headers: { foo: "bar" } }}`.
3. Create another endpoint at hookbin
4. Add another image with `source={{ uri: "hookbin endpoint #2" }}`, ensure it loads after image 2.

The request for image on endpoint `#2` will include the `foo`: `bar` headers.

This is probably the reason of a lot of errors with images not properly showing in this repository.

**Additionally, this is a serious security issue, as signing credentials or other session tokens could be leaked to other servers. See screenshot below.**

**Expected behavior**

Headers should not be reused.

**Screenshots**

<img width="428" alt="image" src="https://user-images.githubusercontent.com/697707/83863179-aa406280-a72b-11ea-8fc6-c1c44218c3ac.png">

Notice how headers are leaked to other servers. The headers were only supposed to be used for images from the s3 bucket, but they are attached to every request.

**Dependency versions**

- React Native version: 0.62.1
- React version: 16.11.0
- React Native Fast Image version: 8.1.5

**Comment by andreialecu** [comment]
Issue acknowledged by upstream SDWebImage contributor @dreampiggy at:

https://github.com/SDWebImage/SDWebImage/issues/3031#issuecomment-639376964

**Comment by dreampiggy** [comment]
Not the issue of upstream dependency, this is a bug of react-native-fast-image implementation. Should use the correct API to do **Per-image-level-header-setup**.

**Comment by andreialecu** [comment]
Fix is available at #691

**Comment by andreialecu** [comment]
Closing since #691 was merged, and the fix is in version 8.3.0 as per https://github.com/DylanVann/react-native-fast-image/pull/691#issuecomment-659864093
