### ISSUE TITLE
Error in android 

### ISSUE THREAD

**Issue by tybq93** [DylanVann/react-native-fast-image#7]
when i use this libary on Android, it show an error:
"android.widget.imageview cannot be cast to android.view.viewgroup".
but on ios is work fine.

react-native: 0.44.2
react: 16.0.0-alpha.6
react-native-fast-image: 0.0.10

anyone can help me? :(

**Comment by GeekRishabh** [comment]
@tybq93  seems to work fine if you use on <FastImage /> 
If you are using any other component inside fastImage then it exist .

**Comment by DylanVann** [comment]
Yes, there isn't support for children on android. You'll have to use
another technique, like absolute positioning.

**Comment by DylanVann** [comment]
See #15 .
