### ISSUE TITLE
Is it possible to set the placeholder image while loading the image from url?

### ISSUE THREAD

**Issue by yuriiKur** [DylanVann/react-native-fast-image#73]
I already used this library, and it works well.. but while loading the image from url, I wanna set the placeholder image.
Please let me know if it is possible or not.

**Comment by edmundito** [comment]
One way to do this is by wrapping it in a component that displays a local `<Image />` while the fast image is loading, then replace it once the image is loaded. You may be able use the `display: 'none'` or `height: 0, opacity: 0` style on the `FastImage` component while it loads, then update the component to only show the `FastImage`.

**Comment by pavanmehta91** [comment]
Can you show it with an example @edmundito ? Should we use onLoadEnd handler here?
What if I've 100+ images do I setState 100 times?

**Comment by hoanganhbk94** [comment]
+1

**Comment by aMarCruz** [comment]
@DylanVann , it would be great if react-native-fast-image would support the [placeholder feature](http://bumptech.github.io/glide/doc/placeholders.html) that Glide supports.

**Comment by DylanVann** [comment]
Duplicate: https://github.com/DylanVann/react-native-fast-image/issues/5

It's super easy to implement this currently using a local `Image` behind `FastImage`. This will probably be added eventually though.

**Comment by deepakkumardk** [comment]
It's been 2 years still no progress are we going to add this feature in the near future?
