### ISSUE TITLE
CocoaPods could not find compatible versions for pod "SDWebImage"

### ISSUE THREAD

**Issue by ryoid** [DylanVann/react-native-fast-image#731]
**Describe the bug**
Unable to do pod install. I have tried using an older version and I am able to use up to 8.1.9.

**To Reproduce**
1. npx pod-install
2. See error

**Expected behavior**
Install pods.

**Screenshots**
![image](https://user-images.githubusercontent.com/18044529/93748564-0ff92180-fc2b-11ea-951f-9c18501998b5.png)

**Dependency versions**

- React Native version: 0.63.2
- React version: 16.13.1
- React Native Fast Image version: 8.3.2
- Cocoapods: 1.9.3

**Comment by chengsam** [comment]
Try run `pod repo update`

**Comment by ryoid** [comment]
> Try run `pod repo update`

That did it for me, thank you so much didn't realise was an issue with my cocoapod.

**Comment by code-by** [comment]
not help for solve same issue
RN: 0.60.5

**Comment by JimTeva** [comment]
@code-by, I fixed it with:
```
rm Podfile.lock
pod install --repo-update
```

**Comment by Subomi-olagoke** [comment]
None of the solutions above fixed it for me

**Comment by Subomi-olagoke** [comment]
I am building a react native app , I have tried updating both expo and react native , still nothing , any ideas ?

**Comment by aleena-adnan1** [comment]
did you solve it @Subomi-olagoke ?

**Comment by almeidapaulooliveira** [comment]
Not working for me as welL, using Expo:
```
[Hermes] Using the release tarball from Maven Central
[!] CocoaPods could not find compatible versions for pod "SDWebImage":
  In Podfile:
    ExpoImage (from `../node_modules/expo-image/ios`) was resolved to 1.3.5, which depends on
      SDWebImage (~> 5.15.8)

    RNFastImage (from `../node_modules/react-native-fast-image`) was resolved to 8.6.3, which depends on
      SDWebImage (~> 5.11.1)
```

**Comment by michelazzam** [comment]
> Not working for me as welL, using Expo:
> 
> ```
> [Hermes] Using the release tarball from Maven Central
> [!] CocoaPods could not find compatible versions for pod "SDWebImage":
>   In Podfile:
>     ExpoImage (from `../node_modules/expo-image/ios`) was resolved to 1.3.5, which depends on
>       SDWebImage (~> 5.15.8)
> 
>     RNFastImage (from `../node_modules/react-native-fast-image`) was resolved to 8.6.3, which depends on
>       SDWebImage (~> 5.11.1)
> ```

This error occurred after upgrading Cocoapods, right ?

Same issue occurring with me and I am using expo as well - @almeidapaulooliveira

**Comment by Relie9828** [comment]
Try removing `react-native-fast-image` if you have it install then run: 
```
rm Podfile.lock
pod install --repo-update
```

**Comment by abduaddis1** [comment]
> Try removing `react-native-fast-image` if you have it install then run:
> 
> ```
> rm Podfile.lock
> pod install --repo-update
> ```

Does this mean react-native-fast-image is incompatible with expo, considering I have to remove it in order for pod-install to work?

**Comment by abduaddis1** [comment]
> Try removing `react-native-fast-image` if you have it install then run:
> 
> ```
> rm Podfile.lock
> pod install --repo-update
> ```

Does this mean react-native-fast-image is incompatible with an expo project, considering I have to remove it if I want `pod install` to work?

**Comment by immi-10** [comment]
after doing 
```
rm Podfile.lock
pod install --repo-update
```

 i still get:

```
[!] CocoaPods could not find compatible versions for pod "SDWebImageWebPCoder":
  In Podfile:
    ExpoImage (from `../node_modules/expo-image/ios`) was resolved to 1.3.2, which depends on
      SDWebImageWebPCoder (~> 0.11.0)

    RNFastImage (from `../node_modules/react-native-fast-image`) was resolved to 8.6.3, which depends on
      SDWebImageWebPCoder (~> 0.8.4)

```

**Comment by MishalButt777** [comment]
Remove  ^ from  "react-native-fast-image": "^8.6.3" in package.json
Delete node modules and install again
Then run cd ios && pod install

**Comment by tchesa** [comment]
Try this one https://www.npmjs.com/package/@tchesa/react-native-fast-image
