### ISSUE TITLE
Is it possible to use SVG ?

### ISSUE THREAD

**Issue by moduval** [DylanVann/react-native-fast-image#78]
Is it possible to use SVG image with this lib? When i try to display an SVG image, it dosen't work.

**Comment by DylanVann** [comment]
That's not supported by `SDWebImage` or `Glide`.

You may want to look into just including svgs with your app directly if possible, or using a dedicated svg package for React Native.

**Comment by lapcchan** [comment]
@DylanVann will u consider bundle [this component](https://github.com/chitezh/react-native-svg-image) into react-native-fast-image? so we can have the cache ability.

**Comment by vishu-daffodil** [comment]
Hi, I am having the same problem. This component is awesome but I am having issues loading SVG images. Can you please try to integrate [https://github.com/brentvatne/react-native-svgkit](https://github.com/brentvatne/react-native-svgkit)

**Comment by DylanVann** [comment]
Turning this into a feature request. It would be nice to have.

**Comment by lorran-xo** [comment]
Shouldn't this be open since we still don't have any updates regarding having svg files into react-native-fast-image?

**Comment by cristiano-linvix** [comment]
Have support now?

**Comment by ethanneff** [comment]
svgs still don't work

**Comment by hizbullaharif** [comment]
svg still does not Work?

**Comment by rckm** [comment]
Why this issue is closed if this library does not support SVG images?

**Comment by adgang** [comment]
Request to reopen this. This is a feature request. At least the documentation should say prominently that svg does not work.

**Comment by mohcenesegouat** [comment]
Please add SVG support; it would be great to have this feature!
