### ISSUE TITLE
¿use it in production?

### ISSUE THREAD

**Issue by DanMCX** [DylanVann/react-native-fast-image#789]
This is NOT a BUG. 

Please put the label that you consider best.

```
Question: 

It is "still" safe to use react-native-fast-image in production with a react-native typescript project ? 

Any common problems on IOS/Android ? 
```

**Comment by wmonecke** [comment]
This is a pretty vague question. You can take a look at the current open/closed issues and see any major bugs.

**Comment by DylanVann** [comment]
People are using it in production.

This library is not particularly large or complex.

The most common "issues" people have is that they want more control over the native libraries this integrates (`Glide` and `SDWebImage`), or just more features generally.
