### ISSUE TITLE
Add SDWebImage to project is not a good idea.

### ISSUE THREAD

**Issue by OceanHorn** [DylanVann/react-native-fast-image#79]
Maybe you need to suggest users to run `pod init` in folder `ios` and add `pod 'SDWebImage', '~> 3.7.5'` in `Podfile`, then `pod install`.  Because `SDWebImage` is very likely to be already used in user's project.
for this, you need to add `$(BUILT_PRODUCTS_DIR)` to `Header Search Paths`.

**Comment by DylanVann** [comment]
It seems like most apps being built with RN are greenfield projects so it's not that common that they already use `SDWebImage`.

We could look at adding some documentation on that though.

**Comment by OceanHorn** [comment]
rn 0.51 now is supporting including 3rd dependency by pod.
adding a 'react-native-fast-image.podspec' file and making SDWebImage as a dependency is considerable.

**Comment by OceanHorn** [comment]
When would this repository support pod？

**Comment by DylanVann** [comment]
It supports CocoaPods now. Thanks for the help

**Comment by hfqf** [comment]
How to add react-native-fast-image into podfile?Thanks.

**Comment by hfqf** [comment]
![image](https://user-images.githubusercontent.com/6100695/38596552-bd6723c0-3d84-11e8-8041-f39d9edf86d5.png)

**Comment by hfqf** [comment]
![image](https://user-images.githubusercontent.com/6100695/38596748-d8bbfb90-3d85-11e8-87ce-30aa5e275c8d.png)

**Comment by OceanHorn** [comment]
@hfqf 
pod "react-native-fast-image", :path => "#{node_modules_path}/react-native-fast-image"

**Comment by hfqf** [comment]
@OceanHorn   haha! I love u
