### ISSUE TITLE
ios - 'SDWebImage/SDWebImage.h' file not found

### ISSUE THREAD

**Issue by oleg-moseyko** [DylanVann/react-native-fast-image#800]
**Dependency versions**

- React Native version:   "react-native": "^0.63.4",
- React version:  "react": "16.11.0",
- React Native Fast Image version:  "react-native-fast-image": "^7.0.2",

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
    RubyGems : 3.2.3
        Host : macOS 11.0.1 (20B50)
       Xcode : 12.5 (12E262)

platform :ios, '13.0'
```
<img width="1523" alt="2021-07-09 в 20 06 04" src="https://user-images.githubusercontent.com/25344716/125113351-3b34fa80-e0f1-11eb-87e0-fe9dc95b4f54.png">

**Comment by DylanVann** [comment]
You probably need to clear some sort of cache or run `pod install` inside the `ios` folder.
