### ISSUE TITLE
Will cache be removed when app is swipe closed?

### ISSUE THREAD

**Issue by Yandamuri** [DylanVann/react-native-fast-image#804]
When app is swipe closed and then opened, Image is reloaded from server from. Usually is cleared either manually by user or by uninstalling the app. But in this library scenario cache seems to be cleared when app is swipe closed.

Is this library's cache different from app's usual cache?

**Comment by DylanVann** [comment]
I believe the disk cache of Glide/SDWebImage is maintained across sessions. Memory cache will be cleared.
