### ISSUE TITLE
pre-load doesn't work (iOS and Android)

### ISSUE THREAD

**Issue by KevinColemanInc** [DylanVann/react-native-fast-image#805]
If you set the cache control to `FastImage.cacheControl.web`, then the `Fastlane.preload(..)` function doesn't work as expected, especially if the image headers don't have cache information.

Not sure what the fix should be. But maybe update the documentation or write a warning in the logs if a preloaded image is re-loaded due to the cache flag.

**Comment by DylanVann** [comment]
This makes sense, it's how web caching works.

I can add to the readme that `FastImage.cacheControl.immutable` is the recommended cache control mode, and you won't get the best performance if you use other cache control modes.
