### ISSUE TITLE
web image cache on android

### ISSUE THREAD

**Issue by ezha86** [DylanVann/react-native-fast-image#87]
Hi guys.
ios cache works fine, all image after first load from web are cached and then load from cache.
but android in same scenario continue load image from web, not from cache.
at first screen have:
  <FastImage
          style={styles.topImage}
          source={{
            uri: 'IMAGE URL',
            priority: FastImage.priority.normal,
          }}
          resizeMode={FastImage.resizeMode.cover}
        />
then i go to second screen and try to show same image in same way  - ios works fine, bit android not
Did i miss something ?

**Comment by bomblet2** [comment]
I have the same issue. It works on iOS but doesn't work on Android.

**Comment by bomblet2** [comment]
Resolved, accoreding to issue #61  , the build.gradle needs to have a buildToolsVersion of at least 25.0.2.

**Comment by ezha86** [comment]
thanks, but im on react-native": "0.44.2"for now and using "react-native-fast-image": "0.0.11"

**Comment by jslok** [comment]
Is this the same issue? https://github.com/DylanVann/react-native-fast-image/issues/68

How do you test if the image is loaded from web or cache?

**Comment by ezha86** [comment]
i tested it as described above. 
i have news feed (image + news short text)
i click on single news and go to the next screen with same image url

on android image flickering (ios works fine and image displayed immediately)
if click one more time on same news on android - image not flickering and seems to be cached

thats kind of weird
Thanks

**Comment by brunolemos** [comment]
@ezha86  I think this can be closed now, just upgrade react-native and react-native-fast-image.
https://github.com/DylanVann/react-native-fast-image/issues/68#issuecomment-362132380

**Comment by ezha86** [comment]
seems yes.

**Comment by ezha86** [comment]
also my problem was because of the RNFI component had higher priority on the page which it should render from cache
page 1 (priority: FastImage.priority.normal) > page 2 (priority: FastImage.priority.high)
ios does work this way, but android doesnt
so i changed it to - 
page 1 (priority: FastImage.priority.normal) > page 2 (priority: FastImage.priority.low)
and android started caching correctly
