### ISSUE TITLE
how does fast-image release glide cache?

### ISSUE THREAD

**Issue by kingweiliu** [DylanVann/react-native-fast-image#88]
hi, guys,
    I am newer to RN. I'm trying to make a App using fast-image. Many Images will be loaded in different Tab when it runing.  It crashed if I switch any tabs with OOM error. May be Glide not releaseing the image cache cause this. Two questiones I don't clear:
1. fast-image using Glide.with(view.context), does this context is the only  one instance ?  
2. How to release Glide cache in fast-image activily?

**Comment by DylanVann** [comment]
Duplicate: https://github.com/DylanVann/react-native-fast-image/issues/42
