### ISSUE TITLE
Task :react-native-fast-image:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by DuongVuongUTE** [DylanVann/react-native-fast-image#881]
**Describe the bug**
when I raise the compileSdkVersion, minSdkVersion and targetSdkVersion 
minSdkVersion = 23
compileSdkVersion = 31
targetSdkVersion = 31
when I run the app again, the error appears as shown

![Screen Shot 2022-02-22 at 14 11 27](https://user-images.githubusercontent.com/70870745/155080837-e265a3b6-955a-457f-991b-d45457622361.png)

**Dependency versions**

- React Native version: 0.67.2
- React version: 17.0.2
- React Native Fast Image version: 8.5.11

**Comment by anhquan291** [comment]
Facing the same issue on Android Mac M1. However, it works on Intel. Any suggestions please? Thanks

**Comment by coneforapine** [comment]
Can confirm, I also have the same issue on M1 Mac.

**Comment by coneforapine** [comment]
Upon further inspection, I found my java version was 1.8.0. I updated to OpenJDK 17.0.2 and that fixed the issue for me.

**Comment by wdospinal** [comment]
I also have the same issue with 

Dependency versions

React Native version: 0.66.3
React version: 17.0.2
React Native Fast Image version: 8.5.11

**Comment by longb1997** [comment]
+1

**Comment by longb1997** [comment]
> Facing the same issue on Android Mac M1. However, it works on Intel. Any suggestions please? Thanks

I also met it on Intel Mac

**Comment by gamingumar** [comment]
@DuongVuongUTE how did you resolve the issue?

**Comment by DuongVuongUTE** [comment]
> I updated openjdk1.8 to openjdk11

**Comment by DuongVuongUTE** [comment]
@gamingumar I updated openjdk1.8 to openjdk11

**Comment by gamingumar** [comment]
Hi @DuongVuongUTE I believe I already have openjdk11. Can you please confirm how you updated it?

**Comment by anhquan291** [comment]
@gamingumar 
brew tap homebrew/cask-versions
brew install --cask zulu11

**Comment by DuongVuongUTE** [comment]
@gamingumar clean jdk android studio -> I have reinstalled the environment according to the instructions from the homepage https://reactnative.dev/docs/environment-setup and created a new project and it fixed the error 
![image](https://user-images.githubusercontent.com/70870745/168047452-c27571f6-86d0-4050-8200-127c9969d8da.png)
this is the project I just create here https://www.mediafire.com/file/1ary7n60qophtf4/fastimage.rar/file
