### ISSUE TITLE
Low quality for vertical images!

### ISSUE THREAD

**Issue by Omelyan** [DylanVann/react-native-fast-image#887]
**Describe the bug**
Vertical images are rendered at low resolution in horizontal container when loaded from cache. At the same time, everything is ok when filling the vertical container.
This problem has been around for a long time. See #658, #545, #850...
An image display component that cannot properly display an image. Hey!

**Screenshots**
```javascript
<FastImage
  source={{ uri }}
  resizeMode={FastImage.resizeMode.cover}
  style={{ height: 160, width: 320 }}
/>
```
![image](https://user-images.githubusercontent.com/18326050/160302885-97ee44dc-fafc-431f-b472-797fad48123f.png)

****
```javascript
<FastImage
  source={{ uri }}
  resizeMode={FastImage.resizeMode.cover}
  style={{ height: 500, width: 320 }}
/>
```
![image](https://user-images.githubusercontent.com/18326050/160302890-092c566b-b147-431f-a81c-8e8f8f120165.png)

**Dependency versions**

- React Native version: 0.66.4
- React Native Fast Image version: 8.5.11
- Android API 29

**Comment by xiaowl** [comment]
@Omelyan I believe this issue is caused by that the order of property updates is RANDOM as RN using Maps to pass properties. `soruce` always being set before `resizeMode`, then Glide will using `FIT_CENTER` to loading and later the `ImageView` using `CENTER_CROP` to display.

Workaround I used:

```javascript
const [uri, setUri] = useState('');
useEffect(() => {
    setUri(item.uri);
}, []);

<FastImage
  source={{uri: uri}}
  ....
/>
```

**Comment by Omelyan** [comment]
> @Omelyan I believe this issue is caused by that the order of property updates is RANDOM as RN using Maps to pass properties. `soruce` always being set before `resizeMode`, then Glide will using `FIT_CENTER` to loading and later the `ImageView` using `CENTER_CROP` to display.
> 
> Workaround I used:
> 
> ```js
> const [uri, setUri] = useState('');
> useEffect(() => {
>     setUri(item.uri);
> }, []);
> 
> <FastImage
>   source={{uri: uri}}
>   ....
> />
> ```

**Comment by xiaowl** [comment]
Maybe I can make a pull request trying to fix this isse.

**Comment by bodrius** [comment]
same issue

**Comment by apapalillo** [comment]
I have exactly the same issue

**Comment by AlanWen2016** [comment]
same issue

**Comment by pierroo** [comment]
By any chance, is that "displaying image component" react-native-lightbox-v2 @Omelyan ?
I am facing the same issue with this library when it contains a fastImage, and for some reason when I close the ligthbox view, re-open it right away: then the image is no longer "low quality looking". Magic.

**Comment by VinnieMaen** [comment]
> @Omelyan I believe this issue is caused by that the order of property updates is RANDOM as RN using Maps to pass properties. `soruce` always being set before `resizeMode`, then Glide will using `FIT_CENTER` to loading and later the `ImageView` using `CENTER_CROP` to display.
> 
> Workaround I used:
> 
> ```js
> const [uri, setUri] = useState('');
> useEffect(() => {
>     setUri(item.uri);
> }, []);
> 
> <FastImage
>   source={{uri: uri}}
>   ....
> />
> ```

Thanks this worked for me!
