### ISSUE TITLE
Replacing Animated.Image

### ISSUE THREAD

**Issue by flikQ** [DylanVann/react-native-fast-image#89]
Hi,

I am currently working on an animation using the standard Image tag, I would like to use FastImage for these images however Animated.FastImage obviously doesn't work.

Doesn't anyone know a way to get this working?

**Comment by ahanriat** [comment]
```javascript
const AnimatedFastImage = Animated.createAnimatedComponent(FastImage);
```

**Comment by tyeon95** [comment]
@ahanriat I've tried this but I was not able to make it work - it shows blank.
```
<AnimatedFastImage
  style={[styles.image, { opacity: this.state.imageOpacity }, this.props.style]}
  source={{
    uri: this.props.imageSource,
    priority: FastImage.priority.normal,
  }}
  resizeMode={FastImage.resizeMode.cover}
  onLoad={() => this.onLoadImage()} //function call to Animated.timing on this.state.imageOpacity
/>
```

**Comment by ahanriat** [comment]
@tyeon95 Did you set height or width to your image style?

**Comment by mikehuebner** [comment]
There is a deeper issue with this where if the image is cached onLoad will not be called at all.

**Comment by digitaledge** [comment]
This actually works for me like this:

`const AnimatedImage = Animated.createAnimatedComponent(FastImage);
<AnimatedImage
                        style={[
                            styles.backgroundImage,
                            {
                                opacity: imageOpacity,
                                transform: [{ translateY: imageTranslate }],
                            },
                        ]}
                        source={{
                            uri: image,
                            priority: FastImage.priority.high
                        }}
                        resizeMode={FastImage.resizeMode.cover}
                    />

backgroundImage: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        width: null,
        height: HEADER_MAX_HEIGHT,
        resizeMode: 'cover',
    }
`

**Comment by DylanVann** [comment]
I believe all the involved issues have been resolved.

**Comment by tarangill** [comment]
It works, but when you change height and width with animation, the image is pixelated.

**Comment by faerylay** [comment]
`in typescript u need to use like this const AnimatedFastImage: any = Animated.createAnimatedComponent(
	FastImage as any
) `

**Comment by ShaunLWM** [comment]
> `in typescript u need to use like this const AnimatedFastImage: any = Animated.createAnimatedComponent( FastImage as any ) `

I believe we can use this for better typings
```typescript
const AnimatedFastImage = Animated.createAnimatedComponent(FastImage as FC<FastImageProps>);
```

Correct me if I'm wrong. Thanks

**Comment by elmaxe** [comment]
`const AnimatedFastImage = Animated.createAnimatedComponent(FastImage);`

Gave error:
`The signature (component: typeof FlatList, options?: Options | undefined): ComponentClass>, any> of Animated.createAnimatedComponent is deprecated.`

Solved by: 
`const AnimatedFastImage = Animated.createAnimatedComponent<FastImageProps>(FastImage as any);`

saw no difference between `any` and `FC<FastImageProps>`
