### ISSUE TITLE
Add progress image loading spinner / ActivityIndicator.

### ISSUE THREAD

**Issue by GeekRishabh** [DylanVann/react-native-fast-image#9]
Please add the feature of the [Progress Image](https://github.com/oblador/react-native-image-progress) . in the upcoming release if possible . Sometime we need to show the Activity indicator or progressBar . even though if we use Fast Image .

**Comment by wangshijun** [comment]
may reference: https://github.com/kfiroo/react-native-cached-image

**Comment by DylanVann** [comment]
At the moment this is more of a lower level library. Currently you can detect when loading is done with `onLoad` so it isn't too difficult to wrap this component in a component that will show a loading spinner.

If this was included it would need to be something like `LoadingIndicatorComponent` so that it could be customized. I'm not a fan of how`ActivityIndicator` looks but if you wanted to use it you could then use:

```js
<FastImage {...otherProps} LoadingIndicatorComponent={ActivityIndicator} />
```

**Comment by bang88** [comment]
Really needs this function, eg we have a image 2M, we should display the progress bar like @GeekRishabh said.  and i also need fast Image too, at this moment i can't combine Fast Image with https://github.com/oblador/react-native-image-progress, could you have a look ,that would be awesome to support this feature

Thanks

**Comment by dioxide** [comment]
+1

**Comment by DylanVann** [comment]
Ok I'll add it later tonight. 👍

**Comment by bang88** [comment]
Ping @DylanVann , are you planning support these features this week, we have an app using your library and will be publish to app store  next week. if have these feature builtin will be more good to our clients.

I am very sorry to say that but its important for us ,thanks again.

**Comment by DylanVann** [comment]
@bang88 Unfortunately it's more difficult than I thought. Glide doesn't expose an easy way to get progress events. I'm looking into how it can be done but idk when I'll have a new release with this in it.

If you want indeterminate progress that would be easy to implement as is.

**Comment by bang88** [comment]
@DylanVann If you have a new version please ping me.

Thanks

**Comment by oblador** [comment]
Hey, I've added custom image component support to `react-native-image-progress` in the latest version, so you can at least use it with indeterminate progress and if the `onProgress` callback is implemented, it should work out of the box.

**Comment by bang88** [comment]
@oblador  Thank you.

**Comment by ragnorc** [comment]
Now FastImage keeps showing the progress indicator when using  as custom image component  in react-native-image-progress. Is onLoad not implemented?

**Comment by srameshr** [comment]
@ragnorc Any solutions?

**Comment by DylanVann** [comment]
✨ New version with progress, give it a try and let me know if you have any issues! ✨

**Comment by bang88** [comment]
Well done, will try it later.

**Comment by DylanVann** [comment]
It has the same callbacks as React Native's image, so it should work with `react-native-image-progress`. Fingers crossed.

**Comment by AlmogRnD** [comment]
I have the following code but not seeing the indicator={ProgressCircle}

```
<Swiper
                    cards={selectedPhotos}
                    renderCard={(image) => {
                        return (
                            <FastImage
                                style={{width: 300, height: 300}}
                                source={{
                                    uri: 'https://s3-ap-southeast-2.amazonaws.com/ccapp-compressed-images/' + image.filename,
                                    priority: FastImage.priority.normal,
                                }}
                                indicator={ProgressCircle}
                                resizeMode={FastImage.resizeMode.contain}
                            />

                        )
                    }}
                    cardIndex={0}
                    backgroundColor={'#FFF'}>
                </Swiper>
```

Am I doing something wrong

**Comment by DylanVann** [comment]
@AlmogRnD I didn't add any functionality for displaying an indicator, only for reporting events.

@oblador has a module that will wrap `FastImage` with a view that shows progress based on those events. Its looks like:

```js
// react-native-progress exports views that show progress.
import * as Progress from 'react-native-progress';
// That's this module.
import FastImage from 'react-native-fast-image';
// react-native-image-progress is a bridge between the image component,
// or react-native-fast-image, and the progress views in react-native-progress. 
// Or you can use it to render a custom progress indicator.
import { createImageProgress } from 'react-native-image-progress';
// Wrap FastImage with react-native-image-progress.
const Image = createImageProgress(FastImage);

// In your component.
<Image
  source={{ uri: 'https://cdn-images-1.medium.com/max/1600/1*-CY5bU4OqiJRox7G00sftw.gif' }}
  style={{ width: 100, height: 100 }}
  indicator={Progress.Pie}
/>
```

**Comment by AlmogRnD** [comment]
@DylanVann thanks I have it working I'm getting some wired issue opening a different ticket for it

**Comment by bitshadow** [comment]
Looks like this is still an issue.

In case of already loaded image it infinitely keeps showing indicator on image. Any idea how to fix it?

**Comment by Amurmurmur** [comment]
@bitshadow Same problem

**Comment by Amurmurmur** [comment]
@DylanVann Seems like its an issue with the fast-image
I've tested with the standard Image component that comes with React-Native and it wasnt an issue :/

**Comment by B4UGUYS** [comment]
Hello there, onProgress callback in not working on android. Any idea for that ??

**Comment by jhoanborges** [comment]
Same problem

**Comment by henr** [comment]
onProgress callback in not working on android @DylanVann

**Comment by henr** [comment]
remove this in android/build.gradle then ok.
project.ext {
    excludeAppGlideModule = true
}

@jhoanborges @kashsbd

**Comment by NemyaNation** [comment]
Anything on the roadmap to just display a spinner instead of the progress components from the library you posted.
