### ISSUE TITLE
FastImage not working

### ISSUE THREAD

**Issue by ChanhTran255** [DylanVann/react-native-fast-image#90]
After apply FastImage. It not working for me only show border with color red. Please help me thanks.

### My  code
` <FastImage
                    style={{height:100, width:100}}
                    source={{
                    uri: 'https://unsplash.it/400/400?image=1',
                    headers:{ Authorization: 'someAuthToken' },
                    priority: FastImage.priority.normal,
                    }}
                    resizeMode={FastImage.resizeMode.contain}
                />`

**Comment by tiberiumihai** [comment]
You installed the library via `npm install react-native-fast-image --save`, probably run `react-native link` but you didn't add the libFastImage.a to your .plist configuration, which may be different from the one that the link command uses. That was my case.

![image](https://user-images.githubusercontent.com/12754525/33240343-62729fd0-d2bd-11e7-8c00-a06895d0018d.png)

**Comment by DylanVann** [comment]
We have a winner! Thanks @tiberiumihai

**Comment by Unlighten** [comment]
What if you are using expo?

**Comment by gogogous88** [comment]
using expo 2, please help to make it compatible
