### ISSUE TITLE
resizeMode behaviour is inconsistent between 8.5.12 and 8.6.0

### ISSUE THREAD

**Issue by Dimous** [DylanVann/react-native-fast-image#922]
**Describe the bug**
Image resize behaviour is inconsistent between versions.

**To Reproduce**
```
<FastImage 
resizeMode={
FastImage.resizeMode.cover
}
source={
{
uri: "https://azbykamebeli.ru/upload/resize_cache/iblock/04d/748_900_1/04d58535526351ab165c5c11983f2791.jpg",
cache: FastImage.cacheControl.web,
priority: FastImage.priority.high
}
}
style={
{
width: "100%",
minHeight: 469.40028989251283
}
}
/>
```

**Expected behavior**
Image resize behaviour to be consistent between versions.

**Screenshots**

**v8.5.12**

![Screenshot_20220829-215717_azbykamebeli](https://user-images.githubusercontent.com/283939/187197919-d64c8251-72cc-4c3a-b8e9-0153469d8d7c.jpg)

**v8.6.0**

![Screenshot_20220829-220403_azbykamebeli](https://user-images.githubusercontent.com/283939/187197950-b1b3fdc4-61ab-419d-9207-30a4f832b8f5.jpg)

**Dependency versions**

- React Native version: ^0.69.5
- React version: ^18.2.0
- React Native Fast Image version: ^8.6.0

---
Changing `FastImage.resizeMode.cover` to `FastImage.resizeMode.contain` solves the problem, but the point is that the behavior shouldn't have changed between versions.

**Comment by djMax** [comment]
Is this just a case of the default value changing? (agree it shouldn't have)

**Comment by djMax** [comment]
(I ask that because if all we need to do is specify contain everywhere there was no value, that's an easy-ish thing to do. But if the change in behavior is more complex...)

**Comment by jihokim2** [comment]
Same Problem.

**Comment by forkball** [comment]
Bump! This is happening in my project as well.

**Comment by esthefanielanza-sothebys** [comment]
I'm having the same issue on android devices

Dependency versions:
"react-native": "0.67.5"
"react": "17.0.2",
"react-native-fast-image": "^8.3.4"

**Comment by saif-o99** [comment]
anyone found a solution?

**Comment by Dimous** [comment]
This package is dead.

**Comment by saif-o99** [comment]
Just converted to [react-native-image-cache](https://github.com/georstat/react-native-image-cache) . seems alot better
