### ISSUE TITLE
Code magic ios build failed

### ISSUE THREAD

**Issue by fakhergh** [DylanVann/react-native-fast-image#935]
Hi folks, 

I tried to build the .ipa on CodeMagic, but I got the error below related to `react-native-fast-image` signin settings.

<img width="907" alt="Screen Shot 2022-10-08 at 3 10 08 AM" src="https://user-images.githubusercontent.com/32802712/194682932-8513e46b-c473-4079-8c57-b3fbbb45799d.png">

Does anyone faced this error before and solve it?

**Comment by majirosstefan** [comment]
<img width="1167" alt="Screen Shot 2022-10-17 at 3 07 11 AM" src="https://user-images.githubusercontent.com/44647381/196068943-77d9cdc2-8c54-455e-9f2f-7abc09cbccf0.png">

**Comment by majirosstefan** [comment]
https://github.com/codemagic-ci-cd/codemagic-docs/discussions/968

**Comment by fixerloop** [comment]
> [codemagic-ci-cd/codemagic-docs#968](https://github.com/orgs/codemagic-ci-cd/discussions/968)

Thank you so much @majirosstefan it works for me.

**Comment by fakhergh** [comment]
> [codemagic-ci-cd/codemagic-docs#968](https://github.com/orgs/codemagic-ci-cd/discussions/968)

Thank you so much @majirosstefan it works for me.
