### ISSUE TITLE
npm/yarn engine dependencies

### ISSUE THREAD

**Issue by farfromrefug** [DylanVann/react-native-fast-image#94]
You should remove those deps. Mostly all users will have different engine versions ;)

**Comment by ovaris** [comment]
Yep, also they make it very hard to build projects using react-native-fast-image on CI machines :(

**Comment by DylanVann** [comment]
Sorry about that. I forgot yarn actually enforces the version. I've removed it and published a new version.

**Comment by ovaris** [comment]
Thanks @DylanVann for fixing!
