### ISSUE TITLE
Android: onLoad, onLoadStart, onLoadEnd events not arriving in order

### ISSUE THREAD

**Issue by s77rt** [DylanVann/react-native-fast-image#975]
**Describe the bug**
`onLoad`, `onLoadStart`, `onLoadEnd` events not arriving in order on Android. This is happens more often with GIF images. Probably due to the events being emitted asynchronously. 

**To Reproduce**
1. On Android, choose a GIF Image
2. Notice that the order of `onLoad`, `onLoadStart`, `onLoadEnd` is not reliable

**Expected behavior**
`onLoadStart` to be called first then `onLoad` and finally `onLoadEnd`.

**Screenshots**
We have this issue for more details: https://github.com/Expensify/App/issues/15288

**Dependency versions**

- React Native version: 0.70.4
- React version: 18.1.0
- React Native Fast Image version: 8.6.3

**Comment by 2sem** [comment]
I can see image, but onLoad/onLoadEnd is never called

**Comment by s77rt** [comment]
I think the bug is not on `react-native-fast-image` turns out that we were using a patched version and we forgot about it. The bug is probably in that patch.

Closing.
