### ISSUE TITLE
FastImage not showing images

### ISSUE THREAD

**Issue by grkemtneri** [DylanVann/react-native-fast-image#980]
**Describe the bug**
Hello, I was using fast image on my Flatlist for a long time but lately it started not showing my images. 

I'm using react native's own image component, no problem, it's working

Also, when I put another image url in the source, it works. Only the data from the API works. It used to work. When I paste the url of the photo from the api in google chrome, it works too.

**Dependency versions**

- React Native version: 64.4
- React version: 17.0.1
- React Native Fast Image version: 8.6.3

**Comment by grkemtneri** [comment]
It started working now, I didn't change anything in the code. It worked on some phones it didn't work on some phones. very weird 🤔

**Comment by HERYORDEJY** [comment]
@grkemtneri Have you been able to solve this?
